In [23]:
import pandas as pd
import numpy as np

print("Pandas version:", pd.__version__)
print("NumPy version:", np.__version__)
print("Environment is working!")

Pandas version: 3.0.5
NumPy version: 2.5.3
Environment is working!

In [24]:
import pandas as pd

dxsum_path = "../data/DXSUM_26Aug2026.csv"

df = pd.read_csv(dxsum_path)

print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

display(df.head())

Rows: 16373
Columns: 41

,PHASE,PTID,RID,VISCODE,VISCODE2,EXAMDATE,DIAGNOSIS,DXNORM,DXNODEP,DXMCI,...,DXODES,DXCONFID,ID,SITEID,USERDATE,USERDATE2,DD_CRF_VERSION_LABEL,LANGUAGE_CODE,HAS_QC_ERROR,update_stamp
0,ADNI1,011_S_0002,2,bl,bl,2005-09-29,1.0,1.0,-4.0,-4.0,...,-4.0,4.0,2,107,2005-10-01,NaN,NaN,NaN,NaN,2005-10-01 00:00:00
1,ADNI1,011_S_0003,3,bl,bl,2005-09-30,3.0,-4.0,-4.0,-4.0,...,-4.0,3.0,4,107,2005-10-01,NaN,NaN,NaN,NaN,2005-10-01 00:00:00
2,ADNI1,011_S_0005,5,bl,bl,2005-09-30,1.0,1.0,-4.0,-4.0,...,-4.0,4.0,6,107,2005-10-01,NaN,NaN,NaN,NaN,2005-10-01 00:00:00
3,ADNI1,011_S_0008,8,bl,bl,2005-09-30,1.0,1.0,-4.0,-4.0,...,-4.0,3.0,8,107,2005-10-01,NaN,NaN,NaN,NaN,2005-10-01 00:00:00
4,ADNI1,022_S_0007,7,bl,bl,2005-10-06,3.0,-4.0,-4.0,-4.0,...,-4.0,4.0,10,10,2005-10-06,NaN,NaN,NaN,NaN,2005-10-06 00:00:00

In [25]:
print(df.columns.tolist())

['PHASE', 'PTID', 'RID', 'VISCODE', 'VISCODE2', 'EXAMDATE', 'DIAGNOSIS', 'DXNORM', 'DXNODEP', 'DXMCI', 'DXMDES', 'DXMPTR1', 'DXMPTR2', 'DXMPTR3', 'DXMPTR4', 'DXMPTR5', 'DXMPTR6', 'DXMDUE', 'DXMOTHET', 'DXDSEV', 'DXDDUE', 'DXAD', 'DXAPP', 'DXAPROB', 'DXAPOSS', 'DXPARK', 'DXPDES', 'DXPCOG', 'DXPATYP', 'DXDEP', 'DXOTHDEM', 'DXODES', 'DXCONFID', 'ID', 'SITEID', 'USERDATE', 'USERDATE2', 'DD_CRF_VERSION_LABEL', 'LANGUAGE_CODE', 'HAS_QC_ERROR', 'update_stamp']

In [26]:
print(df["DIAGNOSIS"].value_counts(dropna=False))
print(df["DXMCI"].value_counts(dropna=False))
print(df["DXAD"].value_counts(dropna=False))

DIAGNOSIS
2.0     6639
1.0     6613
3.0     3040
NaN       46
10.0      35
Name: count, dtype: int64
DXMCI
 NaN    12505
-4.0     2267
 1.0     1601
Name: count, dtype: int64
DXAD
 NaN    12505
-4.0     2739
 1.0     1129
Name: count, dtype: int64

In [27]:
df["DIAGNOSIS"].value_counts(dropna=False).sort_index()

DIAGNOSIS
1.0     6613
2.0     6639
3.0     3040
10.0      35
NaN       46
Name: count, dtype: int64

In [28]:
df[["DIAGNOSIS", "DXMCI", "DXAD"]].head(20)

    DIAGNOSIS  DXMCI  DXAD
0         1.0   -4.0  -4.0
1         3.0   -4.0   1.0
2         1.0   -4.0  -4.0
3         1.0   -4.0  -4.0
4         3.0   -4.0   1.0
5         1.0   -4.0  -4.0
6         2.0    1.0  -4.0
7         1.0   -4.0  -4.0
8         1.0   -4.0  -4.0
9         1.0   -4.0  -4.0
10        1.0   -4.0  -4.0
11        1.0   -4.0  -4.0
12        1.0   -4.0  -4.0
13        2.0    1.0  -4.0
14        3.0   -4.0   1.0
15        2.0    1.0  -4.0
16        2.0    1.0  -4.0
17        2.0    1.0  -4.0
18        2.0    1.0  -4.0
19        1.0   -4.0  -4.0

In [29]:
df[["DIAGNOSIS", "DXMCI", "DXAD"]].drop_duplicates().sort_values(
    ["DIAGNOSIS", "DXMCI", "DXAD"]
)

       DIAGNOSIS  DXMCI  DXAD
0            1.0   -4.0  -4.0
3875         1.0    NaN   NaN
924          2.0   -4.0  -4.0
6            2.0    1.0  -4.0
3872         2.0    NaN   NaN
2283         3.0   -4.0  -4.0
1            3.0   -4.0   1.0
3868         3.0    NaN   NaN
16338       10.0    NaN   NaN
10483        NaN    NaN   NaN

In [30]:
for col in ["DIAGNOSIS", "DXMCI", "DXAD"]:
    print("\n", col)
    print(df[col].value_counts(dropna=False))

 DIAGNOSIS
DIAGNOSIS
2.0     6639
1.0     6613
3.0     3040
NaN       46
10.0      35
Name: count, dtype: int64

 DXMCI
DXMCI
 NaN    12505
-4.0     2267
 1.0     1601
Name: count, dtype: int64

 DXAD
DXAD
 NaN    12505
-4.0     2739
 1.0     1129
Name: count, dtype: int64

In [31]:
pd.crosstab(
    df["DIAGNOSIS"],
    df["DXMCI"],
    dropna=False
    
)

DXMCI      -4.0   1.0   NaN
DIAGNOSIS
1.0        1130     0  5483
2.0           5  1601  5033
3.0        1132     0  1908
10.0          0     0    35
NaN           0     0    46

In [32]:
pd.crosstab(
    df["DIAGNOSIS"],
    df["DXAD"],
    dropna=False
)

DXAD       -4.0   1.0   NaN
DIAGNOSIS
1.0        1130     0  5483
2.0        1606     0  5033
3.0           3  1129  1908
10.0          0     0    35
NaN           0     0    46

In [33]:
df[["PTID", "RID", "VISCODE", "EXAMDATE", "DIAGNOSIS"]].head(20)

          PTID  RID VISCODE    EXAMDATE  DIAGNOSIS
0   011_S_0002    2      bl  2005-09-29        1.0
1   011_S_0003    3      bl  2005-09-30        3.0
2   011_S_0005    5      bl  2005-09-30        1.0
3   011_S_0008    8      bl  2005-09-30        1.0
4   022_S_0007    7      bl  2005-10-06        3.0
5   100_S_0015   15      bl  2005-10-18        1.0
6   023_S_0030   30      bl  2005-10-20        2.0
7   023_S_0031   31      bl  2005-10-24        1.0
8   011_S_0016   16      bl  2005-10-25        1.0
9   011_S_0021   21      bl  2005-11-01        1.0
10  011_S_0022   22      bl  2005-11-01        1.0
11  022_S_0014   14      bl  2005-11-04        1.0
12  100_S_0035   35      bl  2005-11-09        1.0
13  023_S_0042   42      bl  2005-11-10        2.0
14  067_S_0029   29      bl  2005-11-11        3.0
15  007_S_0041   41      bl  2005-11-14        2.0
16  022_S_0004    4      bl  2005-11-08        2.0
17  022_S_0044   44      bl  2005-11-30        2.0
18  100_S_0006    6      bl  2005-12-01        2.0
19  022_S_0066   66      bl  2005-12-07        1.0

In [34]:
print("Unique subjects:", df["PTID"].nunique())
print("Rows:", len(df))

Unique subjects: 3746
Rows: 16373

In [35]:
# Convert examination date to datetime
df["EXAMDATE"] = pd.to_datetime(df["EXAMDATE"], errors="coerce")

# Sort each participant's visits chronologically
df_long = df.sort_values(["PTID", "EXAMDATE"]).copy()

# Show participants who have more than one visit
visit_counts = df_long.groupby("PTID").size()

print("Participants with >1 visit:", (visit_counts > 1).sum())
print("Maximum visits for one participant:", visit_counts.max())

Participants with >1 visit: 2924
Maximum visits for one participant: 21

In [36]:
# Look at the longitudinal diagnosis history for the first 20 participants
df_long[
    ["PTID", "RID", "VISCODE", "EXAMDATE", "DIAGNOSIS"]
].head(50)

             PTID  RID VISCODE   EXAMDATE  DIAGNOSIS
202    002_S_0295  295      bl 2006-05-10        1.0
692    002_S_0295  295     m06 2006-11-08        1.0
1476   002_S_0295  295     m12 2007-05-25        1.0
2872   002_S_0295  295     m24 2008-08-04        1.0
3338   002_S_0295  295     m36 2009-05-26        1.0
3712   002_S_0295  295     m48 2010-05-13        1.0
4425   002_S_0295  295     v06 2011-06-02        1.0
5764   002_S_0295  295     v11 2012-05-10        1.0
201    002_S_0413  413      bl 2006-05-10        1.0
721    002_S_0413  413     m06 2006-11-22        1.0
1542   002_S_0413  413     m12 2007-06-14        1.0
2850   002_S_0413  413     m24 2008-07-31        1.0
3310   002_S_0413  413     m36 2009-05-05        1.0
3704   002_S_0413  413     m48 2010-05-06        1.0
4450   002_S_0413  413     v06 2011-06-16        1.0
5780   002_S_0413  413     v11 2012-05-15        1.0
7471   002_S_0413  413     v21 2013-05-14        1.0
8691   002_S_0413  413     v31 2014-05-01        1.0
9279   002_S_0413  413     v41 2015-06-02        1.0
10105  002_S_0413  413    init 2017-06-15        1.0
11816  002_S_0413  413      y2 2019-08-22        1.0
14653  002_S_0413  413  4_init 2025-02-10        1.0
16048  002_S_0413  413   4_m12 2026-04-14        1.0
315    002_S_0559  559      bl 2006-06-27        1.0
843    002_S_0559  559     m06 2006-12-27        1.0
2123   002_S_0559  559     m12 2007-07-20        1.0
2849   002_S_0559  559     m24 2008-08-25        1.0
3387   002_S_0559  559     m36 2009-07-09        1.0
314    002_S_0619  619      bl 2006-06-27        3.0
844    002_S_0619  619     m06 2006-12-27        3.0
1613   002_S_0619  619     m12 2007-06-26        3.0
2991   002_S_0619  619     m24 2008-11-04        3.0
365    002_S_0685  685      bl 2006-07-24        1.0
959    002_S_0685  685     m06 2007-01-30        1.0
1821   002_S_0685  685     m12 2007-08-20        1.0
2875   002_S_0685  685     m24 2008-08-22        1.0
3411   002_S_0685  685     m36 2009-07-28        1.0
3875   002_S_0685  685     m48 2010-07-15        1.0
4496   002_S_0685  685     v06 2011-07-05        1.0
6195   002_S_0685  685     v11 2012-07-24        1.0
391    002_S_0729  729      bl 2006-08-03        2.0
1207   002_S_0729  729     m06 2007-02-22        2.0
1913   002_S_0729  729     m12 2007-09-25        3.0
2813   002_S_0729  729     m18 2008-03-20        3.0
2938   002_S_0729  729     m24 2008-08-28        3.0
3434   002_S_0729  729     m36 2009-08-19        3.0
3877   002_S_0729  729     m48 2010-07-22        3.0
4572   002_S_0729  729     v06 2011-08-02        3.0
6255   002_S_0729  729     v11 2012-08-07        3.0
7817   002_S_0729  729     v21 2013-08-08        3.0

In [37]:
# Show the diagnosis history for a sample of participants

df[["PTID", "VISCODE", "EXAMDATE", "DIAGNOSIS"]].sort_values(
    ["PTID", "EXAMDATE"]
).head(100)

             PTID VISCODE   EXAMDATE  DIAGNOSIS
202    002_S_0295      bl 2006-05-10        1.0
692    002_S_0295     m06 2006-11-08        1.0
1476   002_S_0295     m12 2007-05-25        1.0
2872   002_S_0295     m24 2008-08-04        1.0
3338   002_S_0295     m36 2009-05-26        1.0
...           ...     ...        ...        ...
11643  002_S_1155      y2 2019-05-13        2.0
15311  002_S_1155  4_init 2025-06-16        2.0
16243  002_S_1155   4_m12 2026-05-04        2.0
1102   002_S_1261      bl 2007-02-27        1.0
1854   002_S_1261     m06 2007-09-04        1.0

[100 rows x 4 columns]

In [38]:
# Check the diagnosis codes and their frequencies

print("Unique DIAGNOSIS values:")
print(sorted(df["DIAGNOSIS"].dropna().unique()))

print("\nDiagnosis counts:")
print(df["DIAGNOSIS"].value_counts(dropna=False).sort_index())

Unique DIAGNOSIS values:
[np.float64(1.0), np.float64(2.0), np.float64(3.0), np.float64(10.0)]

Diagnosis counts:
DIAGNOSIS
1.0     6613
2.0     6639
3.0     3040
10.0      35
NaN       46
Name: count, dtype: int64

In [39]:
# Examine AD-related diagnostic fields among MCI and dementia observations

cols = ["DIAGNOSIS", "DXMCI", "DXAD", "DXAPP", "DXAPROB", "DXAPOSS"]

df[cols].value_counts(dropna=False).head(30)

DIAGNOSIS  DXMCI  DXAD  DXAPP  DXAPROB  DXAPOSS
1.0         NaN    NaN   NaN   NaN      NaN        3438
2.0         NaN    NaN   NaN   NaN      -4         2931
                                        NaN        2102
1.0         NaN    NaN   NaN   NaN      -4         2045
2.0         1.0   -4.0  -4.0   -4       -4         1601
1.0        -4.0   -4.0  -4.0   -4       -4         1130
3.0         NaN    NaN   1.0   NaN      -4         1112
           -4.0    1.0   1.0   1        -4          990
            NaN    NaN   1.0   NaN      NaN         591
                         NaN   NaN      NaN         104
           -4.0    1.0   1.0   3        -4           70
NaN         NaN    NaN   NaN   NaN      NaN          46
10.0        NaN    NaN   NaN   NaN      NaN          35
3.0         NaN    NaN   2.0   NaN      7            26
                         NaN   NaN      -4           22
                         2.0   NaN      1            21
           -4.0    1.0   1.0   2        -4           15
                         2.0   -4       1            13
            NaN    NaN   2.0   NaN      2            13
           -4.0    1.0   1.0   7        -4           11
                         2.0   -4       7             7
2.0        -4.0   -4.0  -4.0   -4       -4            5
3.0         NaN    NaN   2.0   NaN      5             5
           -4.0    1.0   2.0   -4       3             4
                         1.0   5        -4            4
            NaN    NaN   2.0   NaN      3             4
           -4.0    1.0   2.0   -4       3|6           3
                  -4.0  -4.0   -4       -4            3
                   1.0   1.0   3|5      -4            3
                         2.0   -4       2             2
Name: count, dtype: int64

In [40]:
# Find participants who have both MCI and dementia diagnoses
diagnosis_by_subject = (
    df.groupby("PTID")["DIAGNOSIS"]
      .apply(lambda x: set(x.dropna()))
)

mci_to_dementia = diagnosis_by_subject[
    diagnosis_by_subject.apply(lambda x: 2.0 in x and 3.0 in x)
]

print("Number of participants with MCI and later dementia:",
      len(mci_to_dementia))

print("\nExample participant IDs:")
print(mci_to_dementia.head(10))

Number of participants with MCI and later dementia: 466

Example participant IDs:
PTID
002_S_0729          {2.0, 3.0}
002_S_0954          {2.0, 3.0}
002_S_1070          {2.0, 3.0}
002_S_1268          {2.0, 3.0}
002_S_4171          {2.0, 3.0}
002_S_4262     {1.0, 2.0, 3.0}
002_S_4521          {2.0, 3.0}
002_S_4746          {2.0, 3.0}
003_S_10426         {2.0, 3.0}
003_S_1057          {2.0, 3.0}
Name: DIAGNOSIS, dtype: object

In [41]:
subject_id = "002_S_0729"

df[df["PTID"] == subject_id][
    ["PTID", "VISCODE", "EXAMDATE",
     "DIAGNOSIS", "DXMCI", "DXAD",
     "DXAPP", "DXAPROB", "DXAPOSS"]
].sort_values("EXAMDATE")

,PTID,VISCODE,EXAMDATE,DIAGNOSIS,DXMCI,DXAD,DXAPP,DXAPROB,DXAPOSS
391,002_S_0729,bl,2006-08-03,2.0,1.0,-4.0,-4.0,-4,-4
1207,002_S_0729,m06,2007-02-22,2.0,1.0,-4.0,-4.0,-4,-4
1913,002_S_0729,m12,2007-09-25,3.0,-4.0,1.0,1.0,1,-4
2813,002_S_0729,m18,2008-03-20,3.0,-4.0,1.0,1.0,1,-4
2938,002_S_0729,m24,2008-08-28,3.0,-4.0,1.0,1.0,1,-4
3434,002_S_0729,m36,2009-08-19,3.0,-4.0,1.0,1.0,1,-4
3877,002_S_0729,m48,2010-07-22,3.0,NaN,NaN,1.0,NaN,-4
4572,002_S_0729,v06,2011-08-02,3.0,NaN,NaN,1.0,NaN,-4
6255,002_S_0729,v11,2012-08-07,3.0,NaN,NaN,1.0,NaN,-4
7817,002_S_0729,v21,2013-08-08,3.0,NaN,NaN,1.0,NaN,-4

In [42]:
# Identify MCI -> dementia participants
mci_to_dementia_ids = mci_to_dementia.index

# Look at AD-related diagnosis among those participants
conversion_check = df[
    df["PTID"].isin(mci_to_dementia_ids)
]

print("MCI -> dementia participants:", len(mci_to_dementia_ids))

print("\nDXAD values among these participants:")
print(conversion_check["DXAD"].value_counts(dropna=False).sort_index())

MCI -> dementia participants: 466

DXAD values among these participants:
DXAD
-4.0     890
 1.0     447
 NaN    1996
Name: count, dtype: int64

In [43]:
# Participants with MCI -> dementia who ever have DXAD = 1
ad_ids = conversion_check.loc[
    conversion_check["DXAD"] == 1,
    "PTID"
].unique()

print("Unique MCI -> dementia participants with DXAD = 1:",
      len(ad_ids))

print("\nFirst 20 participant IDs:")
print(ad_ids[:20])

Unique MCI -> dementia participants with DXAD = 1: 176

First 20 participant IDs:
<StringArray>
['123_S_0162', '128_S_0167', '023_S_0030', '123_S_0050', '011_S_0241',
 '027_S_0256', '098_S_0269', '023_S_0042', '094_S_0434', '033_S_0567',
 '067_S_0243', '067_S_0336', '137_S_0631', '033_S_0723', '023_S_0625',
 '035_S_0204', '021_S_0141', '099_S_0054', '099_S_0111', '100_S_1226']
Length: 20, dtype: str

In [44]:
# Check diagnosis progression for each participant

diag_progression = (
    df.groupby("PTID")["DIAGNOSIS"]
      .apply(lambda x: list(x.dropna()))
)

diag_progression.head(20)

PTID
002_S_0295              [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
002_S_0413     [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ...
002_S_0559                             [1.0, 1.0, 1.0, 1.0, 1.0]
002_S_0619                                  [3.0, 3.0, 3.0, 3.0]
002_S_0685              [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
002_S_0729     [2.0, 2.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, ...
002_S_0782                        [2.0, 2.0, 2.0, 2.0, 2.0, 2.0]
002_S_0816                                       [3.0, 3.0, 3.0]
002_S_0938                                  [3.0, 3.0, 3.0, 3.0]
002_S_0954                             [2.0, 2.0, 3.0, 3.0, 3.0]
002_S_0955                                            [3.0, 3.0]
002_S_1018                                  [3.0, 3.0, 3.0, 3.0]
002_S_1070                        [2.0, 2.0, 2.0, 3.0, 3.0, 3.0]
002_S_10814                                                [2.0]
002_S_1155     [2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, ...
002_S_1261     [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ...
002_S_1268         [2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 3.0]
002_S_1280     [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ...
002_S_2010                        [2.0, 1.0, 1.0, 1.0, 1.0, 1.0]
002_S_2043                                       [2.0, 2.0, 2.0]
Name: DIAGNOSIS, dtype: object

In [45]:
# Create diagnosis progression for each participant

def classify_progression(x):
    diagnoses = set(x.dropna())

    if 2.0 in diagnoses and 3.0 in diagnoses:
        return "MCI_to_dementia"
    elif 2.0 in diagnoses:
        return "MCI_only"
    else:
        return "Other"


progression = df.groupby("PTID")["DIAGNOSIS"].apply(classify_progression)

print("Participant progression:")
print(progression.value_counts())

Participant progression:
DIAGNOSIS
Other              1986
MCI_only           1294
MCI_to_dementia     466
Name: count, dtype: int64

In [46]:
# Convert EXAMDATE to datetime
df["EXAMDATE"] = pd.to_datetime(df["EXAMDATE"], errors="coerce")

# Get the first MCI visit for every participant
first_mci = (
    df[df["DIAGNOSIS"] == 2.0]
    .sort_values(["PTID", "EXAMDATE"])
    .groupby("PTID", as_index=False)
    .first()
)

print("Participants with at least one MCI visit:",
      first_mci["PTID"].nunique())

print("\nFirst MCI visits:")
print(
    first_mci[
        ["PTID", "VISCODE", "EXAMDATE", "DIAGNOSIS"]
    ].head(20)
)

Participants with at least one MCI visit: 1760

First MCI visits:
           PTID VISCODE   EXAMDATE  DIAGNOSIS
0    002_S_0729      bl 2006-08-03        2.0
1    002_S_0782      bl 2006-08-23        2.0
2    002_S_0954      bl 2006-11-22        2.0
3    002_S_1070      bl 2006-12-27        2.0
4   002_S_10814    4_sc        NaT        2.0
5    002_S_1155      bl 2007-01-10        2.0
6    002_S_1261    init 2017-03-14        2.0
7    002_S_1268      bl 2007-03-28        2.0
8    002_S_2010      bl 2010-07-08        2.0
9    002_S_2043      bl 2010-09-16        2.0
10   002_S_2073      bl 2010-09-21        2.0
11   002_S_4171     v01 2011-08-04        2.0
12   002_S_4219     v01 2011-08-30        2.0
13   002_S_4229     v01 2011-09-06        2.0
14   002_S_4237     v01 2011-09-08        2.0
15   002_S_4251     v01 2011-09-15        2.0
16   002_S_4262     v21 2013-10-24        2.0
17   002_S_4270     v41 2015-12-01        2.0
18   002_S_4374     v01 2011-11-10        2.0
19   002_S_4447     v01 2012-01-03        2.0

In [47]:
# Keep only MCI records with a valid examination date
mci_records = df[
    (df["DIAGNOSIS"] == 2.0) &
    (df["EXAMDATE"].notna())
].copy()

# Sort chronologically for each participant
mci_records = mci_records.sort_values(
    ["PTID", "EXAMDATE"]
)

# Take the first actual MCI visit for each participant
first_mci = (
    mci_records
    .drop_duplicates("PTID", keep="first")
    .copy()
)

print("Participants with a valid dated MCI visit:",
      first_mci["PTID"].nunique())

print("\nFirst 20 participants:")
print(
    first_mci[
        ["PTID", "VISCODE", "EXAMDATE", "DIAGNOSIS"]
    ].head(20)
)

Participants with a valid dated MCI visit: 1753

First 20 participants:
             PTID VISCODE   EXAMDATE  DIAGNOSIS
391    002_S_0729      bl 2006-08-03        2.0
440    002_S_0782      bl 2006-08-23        2.0
722    002_S_0954      bl 2006-11-22        2.0
850    002_S_1070      bl 2006-12-27        2.0
868    002_S_1155      bl 2007-01-10        2.0
10027  002_S_1261    init 2017-03-14        2.0
1242   002_S_1268      bl 2007-03-28        2.0
3873   002_S_2010      bl 2010-07-08        2.0
3895   002_S_2043      bl 2010-09-16        2.0
3900   002_S_2073      bl 2010-09-21        2.0
6274   002_S_4171     v01 2011-08-04        2.0
4651   002_S_4219     v01 2011-08-30        2.0
4673   002_S_4229     v01 2011-09-06        2.0
4678   002_S_4237     v01 2011-09-08        2.0
4705   002_S_4251     v01 2011-09-15        2.0
8091   002_S_4262     v21 2013-10-24        2.0
9544   002_S_4270     v41 2015-12-01        2.0
4910   002_S_4374     v01 2011-11-10        2.0
5080   002_S_4447     v01 2012-01-03        2.0
5096   002_S_4450     v01 2012-01-05        2.0

In [48]:
# Create a list of the 1,753 baseline MCI participants
baseline_mci_ids = set(first_mci["PTID"])

# Participants with evidence of DXAD = 1
ad_converter_ids = set(ad_ids)

# Intersection: baseline MCI participants who later have DXAD = 1
baseline_mci_converters = baseline_mci_ids.intersection(ad_converter_ids)

print("Baseline MCI participants:", len(baseline_mci_ids))
print("Potential AD converters:", len(baseline_mci_converters))
print("Potential non-converters:",
      len(baseline_mci_ids) - len(baseline_mci_converters))

Baseline MCI participants: 1753
Potential AD converters: 176
Potential non-converters: 1577

In [49]:
# Get the first MCI date for each participant
baseline_dates = first_mci[["PTID", "EXAMDATE"]].rename(
    columns={"EXAMDATE": "MCI_DATE"}
)

# Get all AD-positive observations
ad_events = df[df["DXAD"] == 1][
    ["PTID", "EXAMDATE", "VISCODE", "DIAGNOSIS", "DXAD"]
].copy()

# Add each participant's first MCI date
ad_events = ad_events.merge(
    baseline_dates,
    on="PTID",
    how="inner"
)

# Keep only AD events occurring AFTER first MCI
valid_ad_events = ad_events[
    ad_events["EXAMDATE"] > ad_events["MCI_DATE"]
].copy()

# Unique participants with a valid later AD event
valid_converter_ids = valid_ad_events["PTID"].unique()

print("Baseline MCI participants:",
      len(baseline_mci_ids))

print("Potential converters before time check:",
      len(baseline_mci_converters))

print("Converters with AD occurring AFTER first MCI:",
      len(valid_converter_ids))

print("Remaining potential non-converters:",
      len(baseline_mci_ids) - len(valid_converter_ids))

Baseline MCI participants: 1753
Potential converters before time check: 176
Converters with AD occurring AFTER first MCI: 174
Remaining potential non-converters: 1579

In [50]:
converter_events = valid_ad_events[
    valid_ad_events["PTID"].isin(valid_converter_ids)
].copy()

print("Number of converter event rows:", len(converter_events))
print("\nDiagnosis distribution:")
print(converter_events["DIAGNOSIS"].value_counts(dropna=False))

print("\nDXAD distribution:")
print(converter_events["DXAD"].value_counts(dropna=False))

print("\nFirst 10 converter events:")
display(
    converter_events[
        ["PTID", "MCI_DATE", "EXAMDATE", "VISCODE", "DIAGNOSIS", "DXAD"]
    ].sort_values(["PTID", "EXAMDATE"]).head(10)
)

Number of converter event rows: 439

Diagnosis distribution:
DIAGNOSIS
3.0    439
Name: count, dtype: int64

DXAD distribution:
DXAD
1.0    439
Name: count, dtype: int64

First 10 converter events:

           PTID   MCI_DATE   EXAMDATE VISCODE  DIAGNOSIS  DXAD
68   002_S_0729 2006-08-03 2007-09-25     m12        3.0   1.0
200  002_S_0729 2006-08-03 2008-03-20     m18        3.0   1.0
223  002_S_0729 2006-08-03 2008-08-28     m24        3.0   1.0
334  002_S_0729 2006-08-03 2009-08-19     m36        3.0   1.0
94   002_S_0954 2006-11-22 2007-10-19     m12        3.0   1.0
187  002_S_0954 2006-11-22 2008-06-20     m18        3.0   1.0
245  002_S_0954 2006-11-22 2008-11-25     m24        3.0   1.0
216  002_S_1070 2006-12-27 2008-09-22     m18        3.0   1.0
252  002_S_1070 2006-12-27 2008-12-15     m24        3.0   1.0
365  002_S_1070 2006-12-27 2009-12-18     m36        3.0   1.0

In [51]:
# Check the dementia-related diagnostic variables that actually exist
# in our converter event dataset

dementia_dx_cols = [
    "DXAD",
    "DXAPP",
    "DXAPROB",
    "DXAPOSS",
    "DXOTHDEM",
    "DXODES",
    "DXPARK",
    "DXPCOG",
    "DXDEP"
]

# Keep only columns that are actually present
available_cols = [
    col for col in dementia_dx_cols
    if col in converter_events.columns
]

print("Diagnostic columns available in converter_events:")
print(available_cols)

converter_dx_summary = (
    converter_events[available_cols]
    .apply(lambda col: (col == 1).sum())
    .sort_values(ascending=False)
)

print("\nNumber of converter event rows with value = 1:")
display(converter_dx_summary)

Diagnostic columns available in converter_events:
['DXAD']

Number of converter event rows with value = 1:

DXAD    439
dtype: int64

In [52]:
valid_ad_events = ad_events[ad_events["EXAMDATE"] > ad_events["MCI_DATE"]]

In [53]:
["PTID", "EXAMDATE", "VISCODE", "DIAGNOSIS", "DXAD"]

['PTID', 'EXAMDATE', 'VISCODE', 'DIAGNOSIS', 'DXAD']

In [54]:
# Get all diagnostic records from the original DXSUM data
# for the 174 participants identified as MCI -> AD converters.

converter_diagnostics = df[
    df["PTID"].isin(valid_converter_ids)
].copy()

# Diagnostic variables relevant to distinguishing AD from other dementias
diagnostic_cols = [
    "PTID",
    "EXAMDATE",
    "VISCODE",
    "DIAGNOSIS",
    "DXAD",
    "DXAPP",
    "DXAPROB",
    "DXAPOSS",
    "DXOTHDEM",
    "DXODES",
    "DXPARK",
    "DXPCOG",
    "DXDEP"
]

# Keep only columns that exist in the dataset
diagnostic_cols = [
    col for col in diagnostic_cols
    if col in converter_diagnostics.columns
]

print("Number of diagnostic records:", len(converter_diagnostics))

print("\nDiagnostic variables available:")
print(diagnostic_cols)

print("\nValues of diagnostic indicators among converter records:")
for col in diagnostic_cols[4:]:
    print(f"\n{col}:")
    print(converter_diagnostics[col].value_counts(dropna=False))

Number of diagnostic records: 1139

Diagnostic variables available:
['PTID', 'EXAMDATE', 'VISCODE', 'DIAGNOSIS', 'DXAD', 'DXAPP', 'DXAPROB', 'DXAPOSS', 'DXOTHDEM', 'DXODES', 'DXPARK', 'DXPCOG', 'DXDEP']

Values of diagnostic indicators among converter records:

DXAD:
DXAD
-4.0    533
 1.0    440
 NaN    166
Name: count, dtype: int64

DXAPP:
DXAPP
 1.0    574
-4.0    533
 2.0     27
 NaN      5
Name: count, dtype: int64

DXAPROB:
DXAPROB
-4     549
1      391
NaN    166
3       17
2        6
7        6
2|7      1
6        1
5        1
5|7      1
Name: count, dtype: int64

DXAPOSS:
DXAPOSS
-4     1108
1        12
2         5
NaN       4
3         3
5         2
7         1
6         1
1|3       1
1|5       1
5|7       1
Name: count, dtype: int64

DXOTHDEM:
DXOTHDEM
-4.0    973
 NaN    166
Name: count, dtype: int64

DXODES:
DXODES
-4.0    973
 NaN    165
 1.0      1
Name: count, dtype: int64

DXPARK:
DXPARK
-4.0    969
 0.0    153
 1.0     16
 NaN      1
Name: count, dtype: int64

DXPCOG:
DXPCOG
-4.0    969
 NaN    166
 3.0      3
 4.0      1
Name: count, dtype: int64

DXDEP:
DXDEP
NaN    1021
0.0      99
1.0      19
Name: count, dtype: int64

In [55]:
# Get the first AD-related event after the participant's first MCI date

first_ad_event = (
    valid_ad_events
    .sort_values(["PTID", "EXAMDATE"])
    .drop_duplicates("PTID", keep="first")
    .copy()
)

print("Unique converter participants:", first_ad_event["PTID"].nunique())

print("\nFirst AD event records:")
display(
    first_ad_event[
        ["PTID", "MCI_DATE", "EXAMDATE", "VISCODE",
         "DIAGNOSIS", "DXAD"]
    ].head(15)
)

print("\nTime from first MCI to first AD event:")
time_to_ad = (
    first_ad_event["EXAMDATE"] - first_ad_event["MCI_DATE"]
).dt.days / 365.25

print(time_to_ad.describe())

Unique converter participants: 174

First AD event records:

           PTID   MCI_DATE   EXAMDATE VISCODE  DIAGNOSIS  DXAD
68   002_S_0729 2006-08-03 2007-09-25     m12        3.0   1.0
94   002_S_0954 2006-11-22 2007-10-19     m12        3.0   1.0
216  002_S_1070 2006-12-27 2008-09-22     m18        3.0   1.0
293  003_S_1057 2007-02-09 2009-03-05     m24        3.0   1.0
23   005_S_0222 2006-03-17 2007-03-28     m12        3.0   1.0
290  005_S_0223 2006-09-15 2009-03-20     m36        3.0   1.0
48   005_S_0572 2006-07-06 2007-07-12     m12        3.0   1.0
402  005_S_1224 2007-02-13 2010-03-12     m36        3.0   1.0
250  006_S_0675 2006-10-18 2008-12-15     m24        3.0   1.0
188  006_S_1130 2007-01-04 2008-07-15     m18        3.0   1.0
36   007_S_0041 2005-11-14 2007-05-14     m18        3.0   1.0
111  007_S_0101 2006-01-05 2008-01-08     m24        3.0   1.0
58   007_S_0128 2006-02-06 2007-08-22     m18        3.0   1.0
28   007_S_0249 2006-03-14 2007-04-09     m12        3.0   1.0
166  007_S_0293 2006-03-28 2008-04-21     m24        3.0   1.0

Time from first MCI to first AD event:
count    174.000000
mean       1.697058
std        0.894383
min        0.421629
25%        1.016427
50%        1.512663
75%        2.024641
max        4.386037
dtype: float64

In [56]:
# Calculate the last available diagnostic follow-up date
# for each baseline MCI participant.

baseline_mci = first_mci[
    ["PTID", "EXAMDATE"]
].rename(columns={"EXAMDATE": "MCI_DATE"}).copy()

# Get all dated diagnostic visits for baseline MCI participants
followup = df[
    df["PTID"].isin(baseline_mci_ids) &
    df["EXAMDATE"].notna()
][["PTID", "EXAMDATE", "DIAGNOSIS"]].copy()

# Last observed diagnostic date for each participant
last_followup = (
    followup
    .groupby("PTID")["EXAMDATE"]
    .max()
    .reset_index()
    .rename(columns={"EXAMDATE": "LAST_DATE"})
)

# Add baseline MCI date
followup_summary = baseline_mci.merge(
    last_followup,
    on="PTID",
    how="left"
)

# Follow-up duration in years
followup_summary["FOLLOWUP_YEARS"] = (
    followup_summary["LAST_DATE"] -
    followup_summary["MCI_DATE"]
).dt.days / 365.25

# Identify converters
followup_summary["CONVERTER"] = (
    followup_summary["PTID"].isin(valid_converter_ids)
)

print("Overall follow-up duration:")
display(followup_summary["FOLLOWUP_YEARS"].describe())

print("\nFollow-up duration for converters:")
display(
    followup_summary.loc[
        followup_summary["CONVERTER"],
        "FOLLOWUP_YEARS"
    ].describe()
)

print("\nFollow-up duration for potential non-converters:")
display(
    followup_summary.loc[
        ~followup_summary["CONVERTER"],
        "FOLLOWUP_YEARS"
    ].describe()
)

Overall follow-up duration:

count    1753.000000
mean        3.323768
std         3.620578
min         0.000000
25%         0.205339
50%         2.162902
75%         5.002053
max        19.685147
Name: FOLLOWUP_YEARS, dtype: float64

Follow-up duration for converters:

count    174.000000
mean       3.902444
std        2.343219
min        0.421629
25%        2.088980
50%        3.070500
75%        5.008214
max       18.398357
Name: FOLLOWUP_YEARS, dtype: float64

Follow-up duration for potential non-converters:

count    1579.000000
mean        3.260000
std         3.729755
min         0.000000
25%         0.097194
50%         2.099932
75%         4.999316
max        19.685147
Name: FOLLOWUP_YEARS, dtype: float64

In [57]:
# Define a 2-year prediction horizon

HORIZON = 2.0

# Determine whether each participant converted to AD
# within 2 years of their first MCI visit.

first_ad_times = first_ad_event[
    ["PTID", "MCI_DATE", "EXAMDATE"]
].copy()

first_ad_times["TIME_TO_AD_YEARS"] = (
    first_ad_times["EXAMDATE"] -
    first_ad_times["MCI_DATE"]
).dt.days / 365.25

# Participants who converted within 2 years
converter_2yr_ids = set(
    first_ad_times.loc[
        first_ad_times["TIME_TO_AD_YEARS"] <= HORIZON,
        "PTID"
    ]
)

# Participants with no AD conversion within 2 years
# AND at least 2 years of follow-up
nonconverter_2yr_ids = set(
    followup_summary.loc[
        (~followup_summary["PTID"].isin(valid_converter_ids)) &
        (followup_summary["FOLLOWUP_YEARS"] >= HORIZON),
        "PTID"
    ]
)

# Participants excluded because they don't have enough follow-up
excluded_short_followup_ids = set(
    followup_summary.loc[
        (~followup_summary["PTID"].isin(valid_converter_ids)) &
        (followup_summary["FOLLOWUP_YEARS"] < HORIZON),
        "PTID"
    ]
)

print("2-year converters:", len(converter_2yr_ids))
print("2-year non-converters:", len(nonconverter_2yr_ids))
print("Excluded due to <2 years follow-up:", len(excluded_short_followup_ids))

print("\nTotal usable participants:",
      len(converter_2yr_ids) + len(nonconverter_2yr_ids))

print("\nClass distribution:")
print(
    "Converters:",
    len(converter_2yr_ids)
)
print(
    "Non-converters:",
    len(nonconverter_2yr_ids)
)

2-year converters: 119
2-year non-converters: 823
Excluded due to <2 years follow-up: 756

Total usable participants: 942

Class distribution:
Converters: 119
Non-converters: 823

In [58]:
# ---------------------------------------------------------
# Final 2-year MCI -> AD outcome definition
# ---------------------------------------------------------

HORIZON = 2.0

# First AD event for each participant
first_ad_times = first_ad_event[
    ["PTID", "MCI_DATE", "EXAMDATE"]
].copy()

first_ad_times["TIME_TO_AD_YEARS"] = (
    first_ad_times["EXAMDATE"] -
    first_ad_times["MCI_DATE"]
).dt.days / 365.25

# All baseline MCI participants with at least 2 years follow-up
eligible_2yr_ids = set(
    followup_summary.loc[
        followup_summary["FOLLOWUP_YEARS"] >= HORIZON,
        "PTID"
    ]
)

# Participants who converted within 2 years
converter_2yr_ids = set(
    first_ad_times.loc[
        first_ad_times["TIME_TO_AD_YEARS"] <= HORIZON,
        "PTID"
    ]
)

# Everyone with >=2 years follow-up who did NOT convert within 2 years
nonconverter_2yr_ids = (
    eligible_2yr_ids - converter_2yr_ids
)

# Participants with insufficient follow-up
excluded_short_followup_ids = (
    set(baseline_mci_ids) - eligible_2yr_ids
)

print("===== FINAL 2-YEAR COHORT CHECK =====")
print("Baseline MCI participants:", len(baseline_mci_ids))
print()
print("2-year converters:", len(converter_2yr_ids))
print("2-year non-converters:", len(nonconverter_2yr_ids))
print("Excluded (<2 years follow-up):", len(excluded_short_followup_ids))
print()
print("Total usable participants:",
      len(converter_2yr_ids) + len(nonconverter_2yr_ids))

print("\nExpected class ratio:")
print(
    "Converter percentage:",
    round(
        len(converter_2yr_ids) /
        (len(converter_2yr_ids) + len(nonconverter_2yr_ids)) * 100,
        2
    ),
    "%"
)

===== FINAL 2-YEAR COHORT CHECK =====
Baseline MCI participants: 1753

2-year converters: 119
2-year non-converters: 878
Excluded (<2 years follow-up): 787

Total usable participants: 997

Expected class ratio:
Converter percentage: 11.94 %

In [59]:
# ---------------------------------------------------------
# Construct the final participant-level 2-year cohort
# ---------------------------------------------------------

# Select only the baseline MCI participants in our final cohort
final_cohort = first_mci[
    first_mci["PTID"].isin(
        converter_2yr_ids | nonconverter_2yr_ids
    )
].copy()

# Rename the baseline examination date
final_cohort = final_cohort.rename(
    columns={"EXAMDATE": "MCI_DATE"}
)

# Create the binary outcome
final_cohort["AD_CONVERSION_2YR"] = (
    final_cohort["PTID"].isin(converter_2yr_ids)
).astype(int)

# Keep only the variables we need at this stage
final_cohort = final_cohort[
    ["PTID", "MCI_DATE", "AD_CONVERSION_2YR"]
].copy()

# Sort and reset the index
final_cohort = (
    final_cohort
    .sort_values("PTID")
    .reset_index(drop=True)
)

print("===== FINAL COHORT =====")
print("Number of participants:", len(final_cohort))

print("\nOutcome distribution:")
print(final_cohort["AD_CONVERSION_2YR"].value_counts())

print("\nMissing values:")
print(final_cohort.isna().sum())

print("\nFirst 10 participants:")
display(final_cohort.head(10))

===== FINAL COHORT =====
Number of participants: 997

Outcome distribution:
AD_CONVERSION_2YR
0    878
1    119
Name: count, dtype: int64

Missing values:
PTID                 0
MCI_DATE             0
AD_CONVERSION_2YR    0
dtype: int64

First 10 participants:

         PTID   MCI_DATE  AD_CONVERSION_2YR
0  002_S_0729 2006-08-03                  1
1  002_S_0782 2006-08-23                  0
2  002_S_0954 2006-11-22                  1
3  002_S_1070 2006-12-27                  1
4  002_S_1155 2007-01-10                  0
5  002_S_1268 2007-03-28                  0
6  002_S_2010 2010-07-08                  0
7  002_S_2073 2010-09-21                  0
8  002_S_4171 2011-08-04                  0
9  002_S_4229 2011-09-06                  0

In [60]:
from pathlib import Path

# Look for the ADNIMERGE2 folder inside our project
project_dir = Path("..")
adnimerge_dir = project_dir / "data" / "ADNIMERGE2"

print("ADNIMERGE2 path:")
print(adnimerge_dir.resolve())

print("\nFolder exists:", adnimerge_dir.exists())

if adnimerge_dir.exists():
    print("\nContents:")
    for item in adnimerge_dir.iterdir():
        print(item.name)

ADNIMERGE2 path:
C:\Users\anura\Desktop\MCI_AD_XAI_Project\Data\ADNIMERGE2

Folder exists: True

Contents:
ADNIMERGE2

In [61]:
from pathlib import Path

# Point to the inner ADNIMERGE2 folder
adnimerge_inner = adnimerge_dir / "ADNIMERGE2"

print("Inner ADNIMERGE2 path:")
print(adnimerge_inner.resolve())

print("\nFolder exists:", adnimerge_inner.exists())

if adnimerge_inner.exists():
    print("\nFiles and folders inside:")
    
    for item in sorted(adnimerge_inner.iterdir()):
        if item.is_dir():
            print(f"[FOLDER] {item.name}")
        else:
            print(f"[FILE]   {item.name}")

Inner ADNIMERGE2 path:
C:\Users\anura\Desktop\MCI_AD_XAI_Project\Data\ADNIMERGE2\ADNIMERGE2

Folder exists: True

Files and folders inside:
[FOLDER] build
[FOLDER] data
[FILE]   DESCRIPTION
[FOLDER] inst
[FILE]   LICENSE
[FOLDER] man
[FILE]   NAMESPACE
[FILE]   NEWS.md
[FOLDER] R
[FILE]   README.md
[FOLDER] tests
[FOLDER] vignettes

In [62]:
# List all datasets included in the ADNIMERGE2 package

data_dir = adnimerge_inner / "data"

print("Data folder:")
print(data_dir.resolve())

print("\nNumber of .rda files:")

rda_files = sorted(data_dir.glob("*.rda"))
print(len(rda_files))

print("\nAvailable datasets:")
for file in rda_files:
    print(file.name)

Data folder:
C:\Users\anura\Desktop\MCI_AD_XAI_Project\Data\ADNIMERGE2\ADNIMERGE2\data

Number of .rda files:
217

Available datasets:
ADAE.rda
ADAS.rda
ADDCOMM.rda
ADI.rda
ADNI2_ECG.rda
ADNI2_OTELGTAU.rda
ADNI2_VISITID.rda
ADQS.rda
ADRS.rda
ADSL.rda
ADSXLIST.rda
ADVERSE.rda
AE.rda
ALIQUOT_COUNT.rda
AMAS.rda
AMNART.rda
AMYDISC.rda
AMYMETA.rda
AMYQC.rda
AMYREAD.rda
ANTIAMYTX.rda
APOERES.rda
ARM.rda
AV45FOLLOW.rda
AV45META.rda
AV45QC.rda
AV45VITALS.rda
BACKMEDS.rda
BAIMRINMRC.rda
BAINMRC.rda
BAIPETNMRC.rda
BAIPETNMRCAV45.rda
BAIPETNMRCFDG.rda
BAIPETNMRCFTP.rda
batemanlab_20190621.rda
batemanlab_20221118.rda
BHR.rda
BHR_BASELINE_QUESTIONNAIRE.rda
BHR_EVERYDAY_COGNITION.rda
BHR_LONGITUDINAL_QUESTIONNAIRE.rda
BHR_MEMTRAX.rda
BHR_SP_ADL.rda
BHR_SP_CAREGIVER_BURDEN.rda
BHR_SP_EVERYDAY_COGNITION.rda
BHR_SP_FAQ.rda
BHR_SP_INITIAL.rda
BHR_SP_RELATIONSHIP.rda
BHR_SP_STUDY_CONFIRMATION.rda
BIOMARK.rda
BLCHANGE.rda
BLENNOWCSFNFL.rda
BLENNOWCSFNG.rda
BLENNOWPLASMANFL.rda
BLENNOWPLASMANFLLONG.rda
BLENNOWPLASMATAU.rda
BLSCHECK.rda
BSI.rda
C2N_PRECIVITYAD2_PLASMA.rda
CBBCOMP.rda
CBBRESULTS.rda
CCI.rda
CDR.rda
Changed_Study_ID_Listing.rda
CLIELG.rda
CONSENTS.rda
CROSSVAL.rda
CSSRSAD.rda
DATA_DOWNLOADED_DATE.rda
DATADIC.rda
DERIVED_DATADIC.rda
DM.rda
DTIROI_MEAN.rda
DTIROI_ROBUSTMEAN.rda
DTIROI_V1.rda
DXSUM.rda
EBISU.rda
ECOG12PT.rda
ECOG12SP.rda
ECOGPT.rda
ECOGSP.rda
EMBICDCB.rda
EMBICqCP.rda
EXCLUSIO.rda
FAMHXPAR.rda
FAMHXSIB.rda
FAQ.rda
FCI.rda
FHQ.rda
FNIHBC_BLOOD_BIOMARKER_TRAJECTORIES.rda
FOXLABBSI.rda
FUJIREBIOABETA.rda
FUJIREBIOABETAPLASMA.rda
GDSCALE.rda
GENETIC.rda
GF.rda
IES.rda
INCLUSIO.rda
INITHEALTH.rda
ITEM.rda
LABDATA.rda
LABTESTS.rda
LB.rda
LOCLAB.rda
MAYOADIRL_MRI_FMRI.rda
MAYOADIRL_MRI_FMRI_NFQ.rda
MAYOADIRL_MRI_MCH.rda
MAYOADIRL_MRI_QUALITY_ADNI3.rda
MAYOADIRL_MRI_TBMSYN.rda
MEDHIST.rda
METACORES.rda
MMSE.rda
MOCA.rda
MODHACH.rda
MRI3META.rda
MRI_INFARCTS.rda
MRIB1CALIB.rda
MRIFind.rda
MRIMETA.rda
MRIMPPRO.rda
MRIMPRANK.rda
MRINCLUSIO.rda
MRINFQ.rda
MRIPROT.rda
MRIQC.rda
MRIQSM.rda
MRIREAD.rda
MRISERIAL.rda
NEUROBAT.rda
NEUROEXM.rda
NEUROPATH.rda
NPI.rda
NPIQ.rda
NPSTATUS.rda
NV.rda
PACC.rda
PEDQCV.rda
PETC3.rda
PETMETA3.rda
PETMETA_ADNI1.rda
PETMETA_ADNIGO2.rda
PETQC.rda
PHYSICAL.rda
PIBMETA.rda
PIBPETSUVR.rda
PIBQC.rda
PICSLASHS.rda
POSAMYDISC.rda
PREAMYDISC.rda
PSS.rda
PTDEMOG.rda
PUBLICITY.rda
QS.rda
RECADV.rda
RECBLLOG.rda
RECCMEDS.rda
RECFHQ.rda
RECMHIST.rda
REGISTRY.rda
REMOTE_DATADIC.rda
RMT_APOERES.rda
RMT_ECOG12PT.rda
RMT_ECOG12SP.rda
RMT_PTDEMOG.rda
RMT_Screening.rda
RMT_STORYTELLER.rda
ROSTER.rda
RS.rda
RURALITY.rda
RYFF.rda
SC.rda
SPAP_AVID_FLORBETAPIR.rda
STAIAD.rda
STUDYSUM.rda
TAUMETA.rda
TAUQC.rda
TBM22.rda
TCV.rda
TREATDIS.rda
UASPMVBM.rda
UCBERKELEY_AMY_6MM.rda
UCBERKELEY_TAU_6MM.rda
UCBERKELEY_TAUPVC_6MM.rda
UCBERKELEYFDG_8mm.rda
UCD_ADNI1_WMH.rda
UCD_WMH.rda
UCSDVOL.rda
UCSFASLFS_V2.rda
UCSFASLFSCBF.rda
UCSFASLQC.rda
UCSFATRPHY.rda
UCSFFSL.rda
UCSFFSL51.rda
UCSFFSL51ALL.rda
UCSFFSL51Y1.rda
UCSFFSX.rda
UCSFFSX51.rda
UCSFFSX51_ADNI1_3T.rda
UCSFFSX6.rda
UCSFFSX7.rda
UCSFSNTVOL.rda
UGOTPTAU181.rda
UPENN_PLASMA_FUJIREBIO_QUANTERIX.rda
UPENNBIOMK_MASTER.rda
UPENNBIOMK_ROCHE_ELECSYS.rda
UPENNBIOMKADNIDIAN2017.rda
UPENNMSMSABETA2CRM.rda
UPENNPLASMA.rda
UPENNROI_MARS.rda
UPENNSPARE_AD.rda
UPENNSPARE_MCI.rda
URMC_LABDATA.rda
UUCACIR.rda
UWNPSYCHSUM.rda
VISITS.rda
VITALS.rda
VS.rda
WATC.rda

In [63]:
from pathlib import Path

readme_path = adnimerge_inner / "README.md"

print("README exists:", readme_path.exists())

if readme_path.exists():
    readme_text = readme_path.read_text(
        encoding="utf-8",
        errors="ignore"
    )

    print(readme_text[:12000])

README exists: True

<!-- README.md is generated from README.Rmd. Please edit that file -->

<!-- R package versioning: first two digits are for code; last digit is data release number  -->

# ADNIMERGE2 <a href="https://adni.loni.usc.edu/"><img src="man/figures/logo.png" align="right" height="138" /></a>

This is an R data package for the Alzheimer’s Disease Neuroimaging
Initiative (ADNI) study. All datasets are included as shared on
<https://adni.loni.usc.edu/>.

## Package Access

The ADNI study R data package, ADNIMERGE2, will be available on the data
sharing platform at [LONI website](https://adni.loni.usc.edu/). To
request access of the R package, it is required to submit an online
application via LONI website and acceptance of the ADNI Data Use
Agreement
[here](https://adni.loni.usc.edu/wp-content/uploads/how_to_apply/ADNI_Data_Use_Agreement.pdf).

## Installation

To install the package locally, run
`install.packages("path/to/ADNIMERGE2_0.1.1.tar.gz", repos = NULL, type = "source")`.

## Usage

Learn more about `ADNIMERGE2` at
[`Get Started`](https://atri-biostats.github.io/ADNIMERGE2/articles/ADNIMERGE2.html) page

In [64]:
from pathlib import Path

# Find the vignette files
vignette_dir = adnimerge_inner / "vignettes"

print("Vignette files:")
for file in sorted(vignette_dir.iterdir()):
    print(file.name)

Vignette files:
ADNI-Enrollment.Rmd
ADNI-Longitudinal.Rmd
ADNIMERGE2-Analysis-Data.Rmd
ADNIMERGE2-Analysis-Meta-Specs.Rmd
ADNIMERGE2-Derived-Data.Rmd
ADNIMERGE2-PACC.Rmd
ADNIMERGE2-Package-Building.Rmd
ADNIMERGE2.Rmd

In [65]:
# Read the ADNIMERGE2 Analysis Data documentation

analysis_vignette = (
    adnimerge_inner
    / "vignettes"
    / "ADNIMERGE2-Analysis-Data.Rmd"
)

print("File exists:", analysis_vignette.exists())

if analysis_vignette.exists():
    text = analysis_vignette.read_text(
        encoding="utf-8",
        errors="ignore"
    )

    print(text[:20000])

File exists: True
---
title: "ADNIMERGE2-Analysis-Data"
output:
   rmarkdown::html_vignette:
     toc: true
     code_folding: hide
date: "Last Updated: `r format(Sys.Date(), '%B %d, %Y')`"
vignette: >
  %\VignetteIndexEntry{ADNIMERGE2-Analysis-Data}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  warning = FALSE,
  message = FALSE,
  class.source = "fold-show"
)
options(rmarkdown.html_vignette.check_title = FALSE)
# Data print function
datatable <- function(data, paging = FALSE, searchable = TRUE, bInfo = FALSE, ...) {
  DT::datatable(
    data = data, ...,
    options = list(
      paging = paging, searchable = searchable, bInfo = bInfo,
      ...
    )
  )
}
```

# Introduction

This article describes creating derived analysis ready dataset using the [PHARMERVERSE](https://pharmaverse.org/) workflow. It uses some pre-generated standardized dataset and a metadata-specs as input. Please refer to the following articles to see how those derived dataset and metadata-specs were created, respectively.

* [ADNIMERGE2-Derived-Data]()
* [ADNIMERGE2-Analysis-Meta-Specs]()

In `ADNIMERGE2` R data package, the following selected derived analysis ready dataset will be created for illustration purpose.

* Subject-Level Analysis Dataset - ADSL
* Analysis Dataset of Adverse Events - ADAE
* Analysis Dataset of Questionnaire - ADQS
* Analysis Dataset of Clinical Classification - ADRS

**NOTE**

* *These derived analysis ready dataset may not be fully complied with the [CDISC-ADaM](https://www.cdisc.org/standards/foundational/adam) standardization.*

# Load Required R Packages

```{r setup-libraries}
library(tidyverse)
library(assertr)
library(metacore)
library(metatools)
library(admiral)
library(admiraldev)
library(xportr)
```

```{r study-library, purl = FALSE}
# ADNI study R data package
library(ADNIMERGE2)
```

The following r chuck loads some of study specific wrapper functions that are modified from [`metacore`](https://atorus-research.github.io/metacore/) and [`metatools`](https://pharmaverse.github.io/metatools/) R packages and stored in the `ADNIMERGE2` R package as system file.

```{r system-utils-summary, echo = FALSE}
bind_rows(
  c(
    fun_name = "convert_metacore_to_tibble",
    source = "metacore",
    text = "Convert R6-wrapper metacore object to tibble form"
  ),
  c(
    fun_name = "single_build_from_derived",
    source = "metatools",
    text = "Build from single derived data that required multiple datasets as input"
  ),
  c(
    fun_name = "convert_var_to_fct_wrapper",
    source = "metatools",
    text = "Convert multiple variables into factor - a wrapper function of `convert_var_to_fct`"
  ),
  c(
    fun_name = "create_amystatus_cols",
    source = "internal",
    text = "Create a common baseline amyloid status from multiple image tracer and resolutions"
  )
) %>%
  select(
    `Internal Function` = fun_name,
    `Package Source` = source,
    `Description` = text
  ) %>%
  datatable(searchable = FALSE, bInfo = FALSE)
```

```{r system-utils, purl = FALSE, echo = TRUE, eval = TRUE}
# Load utils function from package system file
utils_file_path <- system.file(
  "analysis-dataset-utils.R",
  package = "ADNIMERGE2",
  mustWork = TRUE
)
source(utils_file_path)
```

# Building Derived Analysis Ready Dataset

```{r prep-meta-data, echo = FALSE}
# Convert `R6-class` object into a data.frame
meta_data_dic <- convert_metacore_to_tibble(METACORES) %>%
  mutate(
    TYPE = str_to_upper(string = type),
    DERIVED = TRUE,
    FLDNAME = variable
  ) %>%
  select(
    TBLNAME = dataset, CRFNAME = dataset.label, structure,
    FLDNAME, LABEL = label, TYPE, DERIVED, type, variable
  )
```

## Subject-Level Analysis Dataset - ADSL

[`ADSL`](../reference/ADSL.html) dataset contains one record per subject. In the ADNI study, [`ADSL`](../reference/ADSL.html) dataset includes only the first record/baseline characteristics of subject when they were enrolled in the study as newly-enrollee or screened to the study for the first time.

<details>
<summary>Show `ADSL` Variables</summary>

```{r adsl-data-dic-print, class.source = NULL, echo = FALSE}
adsl_data_dic <- meta_data_dic %>%
  filter(TBLNAME == "ADSL")

adsl_data_dic %>%
  select(FLDNAME, LABEL, TYPE) %>%
  datatable(data, paging = TRUE)
```

</details>

```{r adsl-data-dic, echo = FALSE}
adsl_metacore <- METACORES %>%
  select_dataset(dataset = "ADSL", simplify = FALSE)
```

```{r generate-adsl0}
ADSL <- build_from_derived(
  metacore = adsl_metacore,
  ds_list = list("DM" = DM, "GF" = GF),
  predecessor_only = TRUE,
  keep = "ALL"
) %>%
  assert_uniq(USUBJID) %>%
  # Create AGE Group - creating categorical group from numeric
  create_cat_var(
    data = .,
    metacore = adsl_metacore,
    ref_var = AGE,
    grp_var = AGEGR1,
    num_grp_var = AGEGR1N
  ) %>%
  # Adjust for multiple race groups
  mutate(RACE = case_when(
    str_detect(RACE, "\\|") ~ "More than one race",
    str_detect(RACE, "Native Hawaiian$|^Other Pacific Islander") ~ "Native Hawaiian or Other Pacific Islander",
    TRUE ~ as.character(RACE)
  )) %>%
  # Re-code RACE
  create_var_from_codelist(
    data = .,
    metacore = adsl_metacore,
    input_var = RACE,
    out_var = RACEN,
    decode_to_code = TRUE
  ) %>%
  # Add baseline DX
  derive_vars_merged(
    dataset = .,
    dataset_add = RS,
    filter_add = RSTESTCD == "DX" & RSBLFL == "Y",
    new_vars = exprs(DX = RSORRES),
    order = exprs(VISITNUM),
    mode = "last",
    by_vars = exprs(STUDYID, USUBJID),
    check_type = "error",
    relationship = "one-to-one"
  ) %>%
  # Convert to factor with Control Terms (CT)
  convert_var_to_fct_wrapper(
    .data = .,
    metacore = adsl_metacore,
    var = c("ORIGPROT", "DX", "RACE")
  ) %>%
  # Add baseline education level and marital status
  call_derivation(
    dataset = .,
    dataset_add = SC,
    derivation = derive_vars_merged,
    variable_params = list(
      params(
        filter_add = SCTESTCD == "PTEDUCAT" & SCBLFL == "Y",
        new_vars = exprs(EDUC = SCSTRESN)
      ),
      params(
        filter_add = SCTESTCD == "PTMARRY" & SCBLFL == "Y",
        new_vars = exprs(MARISTAT = SCORRES)
      )
    ),
    order = exprs(VISITNUM),
    mode = "first",
    by_vars = exprs(STUDYID, USUBJID),
    check_type = "error",
    relationship = "one-to-one"
  ) %>%
  # Add baseline BMI derived from weight and height
  call_derivation(
    dataset = .,
    dataset_add = VS,
    derivation = derive_vars_merged,
    variable_params = list(
      params(
        filter_add = VSTESTCD == "WEIGHT" & VSBLFL == "Y",
        new_vars = exprs(WEIGHT = VSSTRESN)
      ),
      params(
        filter_add = VSTESTCD == "HEIGHT" & VSBLFL == "Y",
        new_vars = exprs(HEIGHT = VSSTRESN)
      )
    ),
    order = exprs(VISITNUM),
    mode = "first",
    by_vars = exprs(USUBJID),
    check_type = "error",
    relationship = "one-to-one"
  ) %>%
  mutate(
    BMI = round(compute_bmi(height = HEIGHT, weight = WEIGHT), 2),
    BMIBLU = ifelse(!is.na(BMI), "kg/m^2", NA_character_),
    AGEU = ifelse(!is.na(AGEU), "Years", NA_character_)
  )
```


```{r generate-adsl1}
# Add baseline amyloid status
NV_AMYSTAT_COLS <- NV %>%
  select(NVTESTCD, NVTEST, NVCAT, NVSCAT) %>%
  distinct() %>%
  filter(str_detect(NVTESTCD, "AMYSTAT")) %>%
  mutate(IMAGE_RES = str_extract_all(NVSCAT, "8MM$|6MM$")) %>%
  filter(str_detect(IMAGE_RES, "8|6")) %>%
  mutate(NVTESTCD_NVSCAT = paste0(NVTESTCD, "0", str_replace_all(NVSCAT, "-", "_")))

nv_params <- lapply(NV_AMYSTAT_COLS$NVTESTCD_NVSCAT, function(param) {
  params_cond <- admiral::params(
    filter_add = NVCAT == "AMYLOIDPET" &
      NVSCAT == stringr::str_replace(stringr::str_split(!!param, "0", simplify = TRUE)[2], "_", "-") &
      NVTESTCD == stringr::str_split(!!param, "0", simplify = TRUE)[1] &
      NVBLFL == "Y",
    new_vars = exprs(!!!exprs(param = NVSTRESC))
  )
  params_cond$new_vars <- substitute(
    exprs(param := NVSTRESC),
    list(param = as.name(param))
  )
  return(params_cond)
})

ADSL <- ADSL %>%
  call_derivation(
    dataset = .,
    dataset_add = NV,
    derivation = derive_vars_merged,
    variable_params = nv_params,
    order = exprs(VISITNUM), # For duplicated cases
    mode = "first",
    by_vars = exprs(USUBJID),
    check_type = "error",
    relationship = "one-to-one"
  )

# Required to create a common amyloid status variable from
# multiple image tracers and resolutions
ADSL <- ADSL %>%
  create_amystatus_cols(.) %>%
  select(-any_of(NV_AMYSTAT_COLS$NVTESTCD_NVSCAT))
```

```{r generate-adsl2}
# Add baseline questionnaire/assessment score
qs_params <- lapply(unique(QS$QSTESTCD), function(param) {
  params_cond <- admiral::params(
    filter_add = QSTESTCD == !!param & QSBLFL == "Y",
    new_vars = exprs(!!!exprs(param = QSORRES))
  )
  params_cond$new_vars <- substitute(
    exprs(param := as.numeric(QSORRES)),
    list(param = as.name(param))
  )
  return(params_cond)
})

ADSL <- ADSL %>%
  call_derivation(
    dataset = .,
    dataset_add = QS,
    derivation = derive_vars_merged,
    variable_params = qs_params,
    order = exprs(VISITNUM),
    mode = "first",
    by_vars = exprs(USUBJID),
    check_type = "error",
    relationship = "one-to-one"
  )
```

```{r generate-adsl3}
ADSL <- ADSL %>%
  # Create enrollment flag
  derive_var_merged_ef_msrc(
    dataset = .,
    by_vars = exprs(STUDYID, USUBJID),
    flag_events = list(
      flag_event(dataset_name = "DM", condition = !is.na(RFSTDTC))
    ),
    source_datasets = list(DM = DM),
    new_var = ENRLFL,
    true_value = "Y",
    false_value = NA_character_
  ) %>%
  # Imputation for death date and enrollment end date
  # Required partial date/time format/character format
  rename("EOSDTHC" = EOSDT) %>%
  select(-DTHDT) %>%
  mutate(
    ENRLDT = as.Date(ENRLDT),
    EOSDTHC = as.character(EOSDTHC),
    DTHDTC = as.character(DTHDTC)
  ) %>%
  call_derivation(
    dataset = .,
    derivation = derive_vars_dtm,
    variable_params = list(
      params(dtc = DTHDTC, new_vars_prefix = "DTH"),
      params(dtc = EOSDTHC, new_vars_prefix = "EOS")
    ),
    highest_imputation = "M",
    date_imputation = "mid",
    flag_imputation = "auto",
    min_dates = exprs(ENRLDT)
  ) %>%
  derive_vars_dtm_to_dt(
    dataset = .,
    source_vars = exprs(DTHDTM, EOSDTM)
  ) %>%
  # Remove any columns that are not specified in the meta-specs
  drop_unspec_vars(
    dataset = .,
    metacore = adsl_metacore
  ) %>%
  # Add variable labels
  metatools::set_variable_labels(
    data = .,
    metacore = adsl_metacore
  )
```

```{r checks-adsl1}
ADSL <- ADSL %>%
  # Check all variables specified are present and no more
  check_variables(
    data = .,
    metacore = adsl_metacore
  ) %>%
  # Checks all variables with CT only contain values within the CT
  check_ct_data(
    data = .,
    metacore = adsl_metacore,
    na_acceptable = TRUE,
    omit_vars = c("ENRLFL", "DTHFL")
  ) %>%
  # Orders the columns according to the spec
  order_cols(
    data = .,
    metacore = adsl_metacore
  ) %>%
  # Sort the dataset based on key columns
  sort_by_key(
    data = .,
    metacore = adsl_metacore
  ) %>%
  # Check uniqueness of record by key columns
  check_unique_keys(
    data = .,
    metacore = adsl_metacore
  )
```

```{r checks-adsl0}
ADSL <- ADSL %>%
  xportr_metadata(
    .df = .,
    metadata = adsl_metacore,
    domain = "ADSL",
    verbose = "stop"
  ) %>%
  # Check variable type with specs match
  # xportr_type() %>%
  # Assign variable value length from the meta specs
  xportr_length() %>%
  # Assign variable label from meta specs and
  # checks variable label length for max of 40 characters
  xportr_label() %>%
  # Checks variable format
  xportr_format()
```

## Analysis Dataset of Adverse Events - ADAE

[`ADAE`](../reference/ADAE.html) dataset contains one record per adverse events per subject with the following characteristics.

<details>
<summary>Show `ADAE` Variables</summary>

```{r adae-data-dic-print, class.source = NULL, echo = FALSE}
adae_data_dic <- meta_data_dic %>%
  filter(TBLNAME == "ADAE")

adae_data_dic %>%
  select(FLDNAME, LABEL, TYPE) %>%
  datatable(data, paging = TRUE)
```

</details>

```{r adae-data-dic}
adae_metacore <- METACORES %>%
  select_dataset(.data = ., dataset = "ADAE", simplify = FALSE)
```

```{r generate-adae}
# Modified user-defined function
ADAE <- build_from_derived(
  metacore = adae_metacore,
  ds_list = list("ADSL" = ADSL, "AE" = AE),
  predecessor_only = TRUE,
  keep = FALSE
) %>%
  # Only subject that had at least one adverse events experience
  filter(USUBJID %in% c(AE$USUBJID)) %>%
  verify(nrow(.) == nrow(AE)) %>%
  # Add adverse events onset and ended date
  derive_vars_merged(
    dataset = .,
    dataset_add = AE %>%
      select(USUBJID, AETERM, AESEQ, AESTDTC, AEENDTC),
    by_vars = exprs(USUBJID, AETERM, AESEQ),
    new_vars = NULL,
    check_type = "error",
    relationship = "one-to-one"
  ) %>%
  # AESTDTC and AEENDTC required to be a character variable
  mutate(
    ENRLDT = as.Date(ENRLDT),
    AESTDTC = as.character(AESTDTC),
    AEENDTC = as.character(AEENDTC)
  ) %>%
  # Add imputed date death date from ADSL
  derive_vars_merged(
    dataset = .,
    dataset_add = ADSL %>%
      select(USUBJID, STUDYID, DTHDT),
    by_vars = exprs(USUBJID, STUDYID),
    new_vars = NULL,
    check_type = "error",
    relationship = "many-to-one"
  ) %>%
  # Derive analysis start and end date
  call_derivation(
    dataset = .,
    derivation = derive_vars_dtm,
    variable_params = list(
      params(
        dtc = AESTDTC, new_vars_prefix = "AST", highest_imputation = "M",
        date_imputation = "first", time_imputation = "first"
      ),
      params(
        dtc = AEENDTC, new_vars_prefix = "AEN", highest_imputation = "M",
        date_imputation = "last", time_imputation = "last",
        max_dates = exprs(DTHDT)
      )
    ),
    flag_imputation = "auto",
    min_dates = exprs(ENRLDT)
  ) %>%
  # Convert into date format
  derive_vars_dtm_to_dt(
    dataset = .,
    source_vars = exprs(ASTDTM, AENDTM)
  ) %>%
  # Derive analysis start/end relative day and
  derive_vars_dy(
    reference_date = ENRLDT,
    source_vars = exprs(ASTDT, AENDT)
  ) %>%
  # Derive analysis duration (value and unit)
  derive_vars_duration(
    new_var = ADURN,
    new_var_unit = ADURU,
    start_date = ASTDT,
    end_date = AENDT,
    in_unit = "days",
    out_unit = "days",
    add_one = TRUE,
    trunc_out = FALSE
  ) %>%
  drop_unspec_vars(
    dataset = .,
    metacore = adae_metacore
  ) %>%
  metatools::set_variable_labels(
    data = .,
    metacore = adae_metacore
  )
```

```{r check-adae}
ADAE <- ADAE %>%
  check_variables(
    data = .,
    metacore = adae_metacore
  ) %>%
  # check_ct_data(
  #   data = .,
  #   metacore = adae_metacore,
  #   na_acceptable = TRUE
  # ) %>%
  order_cols(
    data = .,
    metacore = adae_metacore
  ) %>%
  sort_by_key(
    data = .,
    metacore = adae_metacore
  ) %>%
  check_unique_keys(
    data = .,
    metacore = adae_metacore
  ) %>%
  xportr_metadata(
    .df = .,
    metadata = adae_metacore,
    verbose = "stop"
  ) %>%
  # xportr_type() %>%
  xportr_length() %>%
  xportr_label() %>%
  xportr_format()
```

## Analysis Dataset of Questionnaires - ADQS

[`ADQS`](../reference/ADQS.html) dataset contains one record per questionnaire parameter per visit per subject with the following characteristics.

<details>
<summary>Show `ADQS` Variables</summary>

```{r adqs-data-dic-print, class.source = NULL, echo = FALSE}
adqs_data_dic <- meta_data_dic %>%
  filter(TBLNAME == "ADQS")

adqs_data_dic %>%
  select(FLDNAME, LABEL, TYPE) %>%
  datatable(data, paging = TRUE)
```

</details>

```{r adqs-data-dic}
adqs_metacore <- METACORES %>%
  select_dataset(dataset = "ADQS", simplify = FALSE)
```

```{r adqs-data-prep}
# Assumed all questionnaire parameters are continuous (numeric)
ADQS <- single_build_from_derived(
  metacore = adqs_metacore,
  dataset_name = "ADQS",
  ds_list = list("QS" = QS),
  predecessor_only = TRUE,
  keep = "ALL"
) %>%
  # Add variables from ADSL dataset
  derive_vars_merged(
    dataset = .,
    dataset_add = single_build_from_derived(
      metacore = adqs_metacore,
      dataset_name = "ADQS",
      ds_list = list("ADSL" = ADSL),
      predecessor_only = TRUE,
      keep = "ALL"
    ),
    by_vars = exprs(STUDYID, USUBJID),
    new_vars = NULL,
    check_type = "error",
    relationship = "many-to-one"
  ) %>%
  verify(nrow(.) == nrow(QS)) %>%
  mutate(ADT = as.Date(ADT)) %>%
  # Re-code PARAMN
  # Assumed all PARAMCD are coded in the meta-specs
  create_var_from_codelist(
    data = .,
    metacore = adqs_metacore,
    input_var = PARAMCD,
    out_var = PARAMN,
    decode_to_code = TRUE
  ) %>%
  # Add analysis timing variable
  derive_vars_dy(
    reference_date = ENRLDT,
    source_vars = exprs(ADT)
  ) %>%
  mutate(
    AVISIT = case_when(
      ADT <= ENRLDT | !is.na(ABLFL) ~ "BASELINE",
      TRUE ~ VISIT
    ),
    AVISITN = case_when(
      ADT <= ENRLDT | !is.na(ABLFL) ~ 0,
      TRUE ~ ADY
    )
  ) %>%
  # # Flag baseline records if the flag is not presented in QS derived dataset
  # restrict_derivation(
  #   derivation = derive_var_extreme_flag,
  #   args = params(
  #     by_vars = exprs(STUDYID, USUBJID, PARAMCD),
  #     order = exprs(ADT),
  #     new_var = ABLFL,
  #     mode = "last"
  #   ),
  #   filter = !is.na(AVAL) & ADT <= ENRLDT
  # ) %>%
  # Derive baseline and change from baseline variables
  # Only applicable for continuous parameters
  derive_var_base(
    by_vars = exprs(STUDYID, USUBJID, PARAMCD),
    source_var = AVAL,
    new_var = BASE
  ) %>%
  # Derive change for post-baseline records
  restrict_derivation(
    derivation = derive_var_chg,
    filter = AVISITN > 0
  ) %>%
  # Derive percentage change for post-baseline records
  restrict_derivation(
    derivation = derive_var_pchg,
    filter = AVISITN > 0
  ) %>%
  # Derive sequence number
  derive_var_obs_number(
    by_vars = exprs(STUDYID, USUBJID, PARAMCD),
    order = exprs(PARAMCD, ADT),
    new_var = ASEQ,
    check_type = "none" # "error"
  ) %>%
  drop_unspec_vars(
    dataset = .,
    metacore = adqs_metacore
  ) %>%
  metatools::set_variable_labels(
    data = .,
    metacore = adqs_metacore
  )
```

```{r check-adqs}
ADQS <- ADQS %>%
  check_variables(
    data = .,
    metacore = adqs_metacore
  ) %>%
  check_ct_data(
    data = .,
    metacore = adqs_metacore,
    na_acceptable = TRUE,
    omit_vars = c("ENRLFL", "ABLFL")
  ) %>%
  order_cols(
    data = .,
    metacore = adqs_metacore
  ) %>%
  sort_by_key(
    data = .,
    metacore = adqs_metacore
  ) %>%
  # check_unique_keys(
  #   data = .,
  #   metacore = adqs_metacore
  # ) %>%
  xportr_metadata(
    .df = .,
    metadata = adqs_metacore,
    verbose = "stop"
  ) %>%
  # xportr_type() %>%
  xportr_length() %>%
  xportr_label()
```

### Analysis Dataset of ADAS-Cog Behaviour - ADADAS

Suppose the ADAS Cognitive Behaviors item-13 total score (`ADASTT13`) was the primary outcome in the analysis, then ADAS-Cog Behavior Analysis Dataset (`ADADAS`) can be created either directly from [`ADQS`](../reference/ADQS.html) or with a dataset-specific metadata-specs (i.e. [adding here](../reference/METACORES.html)). The following chuck illustrate how the `ADADAS` can be created directly from pre-generated [`ADQS`](../reference/ADQS.html). More information is available in the [Longitudinal Clinical Cognitive Outcome Summaries]() article.

```{r generate-adadas}
ADADAS <- ADQS %>%
  filter(PARAMCD == "ADASTT13")
```

## Response Analysis Dataset (ADRS)

[`ADRS`](../reference/ADRS.html) dataset contains subject's clinical diagnostics summary per visits including death records.

<details>
<summary>Show `ADRS` Variables</summary>

```{r adrs-data-dic-print, class.source = NULL, echo = FALSE}
adrs_data_dic <- meta_data_dic %>%
  filter(TBLNAME == "ADRS")


In [66]:
# Find useful dataset-related sections in the Analysis Data vignette

keywords = [
    "ADSL",
    "ADRS",
    "ADQS",
    "APOE",
    "MRI",
    "demographic",
    "cognitive",
    "biomarker"
]

for keyword in keywords:
    print("\n" + "=" * 60)
    print("KEYWORD:", keyword)
    print("=" * 60)

    start = 0
    found = 0

    while True:
        pos = text.lower().find(keyword.lower(), start)

        if pos == -1 or found >= 3:
            break

        # Print context around each occurrence
        context_start = max(0, pos - 300)
        context_end = min(len(text), pos + 800)

        print(text[context_start:context_end])
        print("\n---")

        start = pos + len(keyword)
        found += 1

============================================================
KEYWORD: ADSL
============================================================
e derived dataset and metadata-specs were created, respectively.

* [ADNIMERGE2-Derived-Data]()
* [ADNIMERGE2-Analysis-Meta-Specs]()

In `ADNIMERGE2` R data package, the following selected derived analysis ready dataset will be created for illustration purpose.

* Subject-Level Analysis Dataset - ADSL
* Analysis Dataset of Adverse Events - ADAE
* Analysis Dataset of Questionnaire - ADQS
* Analysis Dataset of Clinical Classification - ADRS

**NOTE**

* *These derived analysis ready dataset may not be fully complied with the [CDISC-ADaM](https://www.cdisc.org/standards/foundational/adam) standardization.*

# Load Required R Packages

```{r setup-libraries}
library(tidyverse)
library(assertr)
library(metacore)
library(metatools)
library(admiral)
library(admiraldev)
library(xportr)
```

```{r study-library, purl = FALSE}
# ADNI study R data package
library(ADNIMERGE2)
```

The following r chuck loads some of study specific wrapper functions that are modified from [`metacore`](https://atorus-research.github.io/metacore/) and [`metatools`](https://pharmaverse.github.io/metatools/) R pac

---
e_to_tibble(METACORES) %>%
  mutate(
    TYPE = str_to_upper(string = type),
    DERIVED = TRUE,
    FLDNAME = variable
  ) %>%
  select(
    TBLNAME = dataset, CRFNAME = dataset.label, structure,
    FLDNAME, LABEL = label, TYPE, DERIVED, type, variable
  )
```

## Subject-Level Analysis Dataset - ADSL

[`ADSL`](../reference/ADSL.html) dataset contains one record per subject. In the ADNI study, [`ADSL`](../reference/ADSL.html) dataset includes only the first record/baseline characteristics of subject when they were enrolled in the study as newly-enrollee or screened to the study for the first time.

<details>
<summary>Show `ADSL` Variables</summary>

```{r adsl-data-dic-print, class.source = NULL, echo = FALSE}
adsl_data_dic <- meta_data_dic %>%
  filter(TBLNAME == "ADSL")

adsl_data_dic %>%
  select(FLDNAME, LABEL, TYPE) %>%
  datatable(data, paging = TRUE)
```

</details>

```{r adsl-data-dic, echo = FALSE}
adsl_metacore <- METACORES %>%
  select_dataset(dataset = "ADSL", simplify = FALSE)
```

```{r generate-adsl0}
ADSL <- build_from_derived(
  metacore = adsl_metacore,
  ds_list

---
ble(METACORES) %>%
  mutate(
    TYPE = str_to_upper(string = type),
    DERIVED = TRUE,
    FLDNAME = variable
  ) %>%
  select(
    TBLNAME = dataset, CRFNAME = dataset.label, structure,
    FLDNAME, LABEL = label, TYPE, DERIVED, type, variable
  )
```

## Subject-Level Analysis Dataset - ADSL

[`ADSL`](../reference/ADSL.html) dataset contains one record per subject. In the ADNI study, [`ADSL`](../reference/ADSL.html) dataset includes only the first record/baseline characteristics of subject when they were enrolled in the study as newly-enrollee or screened to the study for the first time.

<details>
<summary>Show `ADSL` Variables</summary>

```{r adsl-data-dic-print, class.source = NULL, echo = FALSE}
adsl_data_dic <- meta_data_dic %>%
  filter(TBLNAME == "ADSL")

adsl_data_dic %>%
  select(FLDNAME, LABEL, TYPE) %>%
  datatable(data, paging = TRUE)
```

</details>

```{r adsl-data-dic, echo = FALSE}
adsl_metacore <- METACORES %>%
  select_dataset(dataset = "ADSL", simplify = FALSE)
```

```{r generate-adsl0}
ADSL <- build_from_derived(
  metacore = adsl_metacore,
  ds_list = list(

---

============================================================
KEYWORD: ADRS
============================================================
DNIMERGE2` R data package, the following selected derived analysis ready dataset will be created for illustration purpose.

* Subject-Level Analysis Dataset - ADSL
* Analysis Dataset of Adverse Events - ADAE
* Analysis Dataset of Questionnaire - ADQS
* Analysis Dataset of Clinical Classification - ADRS

**NOTE**

* *These derived analysis ready dataset may not be fully complied with the [CDISC-ADaM](https://www.cdisc.org/standards/foundational/adam) standardization.*

# Load Required R Packages

```{r setup-libraries}
library(tidyverse)
library(assertr)
library(metacore)
library(metatools)
library(admiral)
library(admiraldev)
library(xportr)
```

```{r study-library, purl = FALSE}
# ADNI study R data package
library(ADNIMERGE2)
```

The following r chuck loads some of study specific wrapper functions that are modified from [`metacore`](https://atorus-research.github.io/metacore/) and [`metatools`](https://pharmaverse.github.io/metatools/) R packages and stored in the `ADNIMERGE2` R package as system file.

```{r system-utils-summary, echo = FALSE}
bind_rows(
  c(
    fun_name = "co

---
the `ADADAS` can be created directly from pre-generated [`ADQS`](../reference/ADQS.html). More information is available in the [Longitudinal Clinical Cognitive Outcome Summaries]() article.

```{r generate-adadas}
ADADAS <- ADQS %>%
  filter(PARAMCD == "ADASTT13")
```

## Response Analysis Dataset (ADRS)

[`ADRS`](../reference/ADRS.html) dataset contains subject's clinical diagnostics summary per visits including death records.

<details>
<summary>Show `ADRS` Variables</summary>

```{r adrs-data-dic-print, class.source = NULL, echo = FALSE}
adrs_data_dic <- meta_data_dic %>%
  filter(TBLNAME == "ADRS")

adrs_data_dic %>%
  select(FLDNAME, LABEL, TYPE) %>%
  datatable(data, paging = TRUE)
```

</details>

```{r adrs-data-dic}
adrs_metacore <- METACORES %>%
  select_dataset(dataset = "ADRS", simplify = FALSE)
```


```{r adrs-data-prep}
# Merge ADSL to RS
adsl_vars <- exprs(STUDYID, USUBJID, ENRLFL, ENRLDT, DTHFL)

ADRS_PREP <- RS %>%
  filter(RSTESTCD %in% "DX") %>%
  # Adjusting BLFL for subjects that have more than one flag
  group_by(STUDYID, USUBJID, RSTESTCD) %>%
  mutate(NUM_B

---
S` can be created directly from pre-generated [`ADQS`](../reference/ADQS.html). More information is available in the [Longitudinal Clinical Cognitive Outcome Summaries]() article.

```{r generate-adadas}
ADADAS <- ADQS %>%
  filter(PARAMCD == "ADASTT13")
```

## Response Analysis Dataset (ADRS)

[`ADRS`](../reference/ADRS.html) dataset contains subject's clinical diagnostics summary per visits including death records.

<details>
<summary>Show `ADRS` Variables</summary>

```{r adrs-data-dic-print, class.source = NULL, echo = FALSE}
adrs_data_dic <- meta_data_dic %>%
  filter(TBLNAME == "ADRS")

adrs_data_dic %>%
  select(FLDNAME, LABEL, TYPE) %>%
  datatable(data, paging = TRUE)
```

</details>

```{r adrs-data-dic}
adrs_metacore <- METACORES %>%
  select_dataset(dataset = "ADRS", simplify = FALSE)
```


```{r adrs-data-prep}
# Merge ADSL to RS
adsl_vars <- exprs(STUDYID, USUBJID, ENRLFL, ENRLDT, DTHFL)

ADRS_PREP <- RS %>%
  filter(RSTESTCD %in% "DX") %>%
  # Adjusting BLFL for subjects that have more than one flag
  group_by(STUDYID, USUBJID, RSTESTCD) %>%
  mutate(NUM_BLFL = sum(

---

============================================================
KEYWORD: ADQS
============================================================
d-Data]()
* [ADNIMERGE2-Analysis-Meta-Specs]()

In `ADNIMERGE2` R data package, the following selected derived analysis ready dataset will be created for illustration purpose.

* Subject-Level Analysis Dataset - ADSL
* Analysis Dataset of Adverse Events - ADAE
* Analysis Dataset of Questionnaire - ADQS
* Analysis Dataset of Clinical Classification - ADRS

**NOTE**

* *These derived analysis ready dataset may not be fully complied with the [CDISC-ADaM](https://www.cdisc.org/standards/foundational/adam) standardization.*

# Load Required R Packages

```{r setup-libraries}
library(tidyverse)
library(assertr)
library(metacore)
library(metatools)
library(admiral)
library(admiraldev)
library(xportr)
```

```{r study-library, purl = FALSE}
# ADNI study R data package
library(ADNIMERGE2)
```

The following r chuck loads some of study specific wrapper functions that are modified from [`metacore`](https://atorus-research.github.io/metacore/) and [`metatools`](https://pharmaverse.github.io/metatools/) R packages and stored in the `ADNIMERGE2` R package as system file.

```{r system-utils-summ

---

  ) %>%
  check_unique_keys(
    data = .,
    metacore = adae_metacore
  ) %>%
  xportr_metadata(
    .df = .,
    metadata = adae_metacore,
    verbose = "stop"
  ) %>%
  # xportr_type() %>%
  xportr_length() %>%
  xportr_label() %>%
  xportr_format()
```

## Analysis Dataset of Questionnaires - ADQS

[`ADQS`](../reference/ADQS.html) dataset contains one record per questionnaire parameter per visit per subject with the following characteristics.

<details>
<summary>Show `ADQS` Variables</summary>

```{r adqs-data-dic-print, class.source = NULL, echo = FALSE}
adqs_data_dic <- meta_data_dic %>%
  filter(TBLNAME == "ADQS")

adqs_data_dic %>%
  select(FLDNAME, LABEL, TYPE) %>%
  datatable(data, paging = TRUE)
```

</details>

```{r adqs-data-dic}
adqs_metacore <- METACORES %>%
  select_dataset(dataset = "ADQS", simplify = FALSE)
```

```{r adqs-data-prep}
# Assumed all questionnaire parameters are continuous (numeric)
ADQS <- single_build_from_derived(
  metacore = adqs_metacore,
  dataset_name = "ADQS",
  ds_list = list("QS" = QS),
  predecessor_only = TRUE,
  keep = "ALL"
) %>%
  #

---

  check_unique_keys(
    data = .,
    metacore = adae_metacore
  ) %>%
  xportr_metadata(
    .df = .,
    metadata = adae_metacore,
    verbose = "stop"
  ) %>%
  # xportr_type() %>%
  xportr_length() %>%
  xportr_label() %>%
  xportr_format()
```

## Analysis Dataset of Questionnaires - ADQS

[`ADQS`](../reference/ADQS.html) dataset contains one record per questionnaire parameter per visit per subject with the following characteristics.

<details>
<summary>Show `ADQS` Variables</summary>

```{r adqs-data-dic-print, class.source = NULL, echo = FALSE}
adqs_data_dic <- meta_data_dic %>%
  filter(TBLNAME == "ADQS")

adqs_data_dic %>%
  select(FLDNAME, LABEL, TYPE) %>%
  datatable(data, paging = TRUE)
```

</details>

```{r adqs-data-dic}
adqs_metacore <- METACORES %>%
  select_dataset(dataset = "ADQS", simplify = FALSE)
```

```{r adqs-data-prep}
# Assumed all questionnaire parameters are continuous (numeric)
ADQS <- single_build_from_derived(
  metacore = adqs_metacore,
  dataset_name = "ADQS",
  ds_list = list("QS" = QS),
  predecessor_only = TRUE,
  keep = "ALL"
) %>%
  # Add var

---

============================================================
KEYWORD: APOE
============================================================

============================================================
KEYWORD: MRI
============================================================

============================================================
KEYWORD: demographic
============================================================

============================================================
KEYWORD: cognitive
============================================================
ck_unique_keys(
  #   data = .,
  #   metacore = adqs_metacore
  # ) %>%
  xportr_metadata(
    .df = .,
    metadata = adqs_metacore,
    verbose = "stop"
  ) %>%
  # xportr_type() %>%
  xportr_length() %>%
  xportr_label()
```

### Analysis Dataset of ADAS-Cog Behaviour - ADADAS

Suppose the ADAS Cognitive Behaviors item-13 total score (`ADASTT13`) was the primary outcome in the analysis, then ADAS-Cog Behavior Analysis Dataset (`ADADAS`) can be created either directly from [`ADQS`](../reference/ADQS.html) or with a dataset-specific metadata-specs (i.e. [adding here](../reference/METACORES.html)). The following chuck illustrate how the `ADADAS` can be created directly from pre-generated [`ADQS`](../reference/ADQS.html). More information is available in the [Longitudinal Clinical Cognitive Outcome Summaries]() article.

```{r generate-adadas}
ADADAS <- ADQS %>%
  filter(PARAMCD == "ADASTT13")
```

## Response Analysis Dataset (ADRS)

[`ADRS`](../reference/ADRS.html) dataset contains subject's clinical diagnostics summary per visits including death records.

<details>
<summary>Show

---
/reference/ADQS.html) or with a dataset-specific metadata-specs (i.e. [adding here](../reference/METACORES.html)). The following chuck illustrate how the `ADADAS` can be created directly from pre-generated [`ADQS`](../reference/ADQS.html). More information is available in the [Longitudinal Clinical Cognitive Outcome Summaries]() article.

```{r generate-adadas}
ADADAS <- ADQS %>%
  filter(PARAMCD == "ADASTT13")
```

## Response Analysis Dataset (ADRS)

[`ADRS`](../reference/ADRS.html) dataset contains subject's clinical diagnostics summary per visits including death records.

<details>
<summary>Show `ADRS` Variables</summary>

```{r adrs-data-dic-print, class.source = NULL, echo = FALSE}
adrs_data_dic <- meta_data_dic %>%
  filter(TBLNAME == "ADRS")

adrs_data_dic %>%
  select(FLDNAME, LABEL, TYPE) %>%
  datatable(data, paging = TRUE)
```

</details>

```{r adrs-data-dic}
adrs_metacore <- METACORES %>%
  select_dataset(dataset = "ADRS", simplify = FALSE)
```


```{r adrs-data-prep}
# Merge ADSL to RS
adsl_vars <- exprs(STUDYID, USUBJID, ENRLFL, ENRLDT, DTHFL)

ADRS_PREP <- RS %>%


---

============================================================
KEYWORD: biomarker
============================================================

In [67]:
try:
    import pyreadr
    print("pyreadr is installed.")
except ImportError:
    print("pyreadr is NOT installed.")

pyreadr is installed.

In [68]:
from pathlib import Path
import pandas as pd

adsl_csv = Path("..") / "data" / "ADSL_from_R.csv"

print("File exists:", adsl_csv.exists())
print("File path:", adsl_csv.resolve())

adsl = pd.read_csv(adsl_csv)

print("\nADSL shape:", adsl.shape)

print("\nColumns:")
print(adsl.columns.tolist())

print("\nFirst 5 rows:")
display(adsl.head())

File exists: True
File path: C:\Users\anura\Desktop\MCI_AD_XAI_Project\Data\ADSL_from_R.csv

ADSL shape: (5146, 55)

Columns:
['STUDYID', 'USUBJID', 'SUBJID', 'SITEID', 'ORIGPROT', 'AGE', 'AGEU', 'AGEGR1N', 'AGEGR1', 'SEX', 'RACE', 'RACEN', 'ETHNIC', 'ENRLFL', 'DTHFL', 'ARM', 'ACTARM', 'ENRLDT', 'EOSDT', 'EOSDTF', 'DTHDT', 'DTHDTF', 'EDUC', 'MARISTAT', 'BMI', 'BMIBLU', 'DX', 'AMYSTAT', 'AMYSTATC', 'TRACER', 'IMAGERES', 'ADASTT11', 'ADASTT13', 'CDGLOBAL', 'CDRSB', 'ECOGPTTT', 'ECOGSPTT', 'FAQTOTAL', 'FCISCORE', 'GDTOTAL', 'MMSCORE', 'MOCA', 'NPITOTAL', 'NPIQTOTL', 'DIGITSCR', 'LDELTOTL', 'LIMMTOTL', 'RAVLTFG', 'RAVLTFGP', 'RAVLTIMM', 'RAVLTLRN', 'TRABSCOR', 'APOE', 'MPACCDIGIT', 'MPACCTRAILSB']

First 5 rows:

,STUDYID,USUBJID,SUBJID,SITEID,ORIGPROT,AGE,AGEU,AGEGR1N,AGEGR1,SEX,...,LDELTOTL,LIMMTOTL,RAVLTFG,RAVLTFGP,RAVLTIMM,RAVLTLRN,TRABSCOR,APOE,MPACCDIGIT,MPACCTRAILSB
0,ADNI,ADNI-001-00221,221,1,ADNI1,67.5,Years,2.0,>=65,Male,...,0.0,4.0,6.0,100.00,21.0,4.0,88.0,ε4/ε4,-16.485093,-15.467351
1,ADNI,ADNI-001-00222,222,1,ADNI1,85.9,Years,2.0,>=65,Male,...,5.0,5.0,6.0,85.71,26.0,5.0,75.0,ε3/ε3,-8.751593,-7.836709
2,ADNI,ADNI-001-00223,223,1,ADNI1,78.0,Years,2.0,>=65,Female,...,19.0,21.0,10.0,90.91,41.0,6.0,129.0,ε3/ε4,1.714571,1.704998
3,ADNI,ADNI-001-00323,323,1,ADNI1,83.2,Years,2.0,>=65,Male,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ε3/ε4,NaN,NaN
4,ADNI,ADNI-001-00324,324,1,ADNI1,75.3,Years,2.0,>=65,Female,...,1.0,7.0,6.0,66.67,42.0,2.0,104.0,ε3/ε3,-11.070588,-11.144506

In [69]:
print("ADSL shape:", adsl.shape)

print("\nNumber of unique subjects:")

for col in ["USUBJID", "SUBJID"]:
    if col in adsl.columns:
        print(col, "unique:", adsl[col].nunique())

print("\nFirst 10 SUBJID values:")
if "SUBJID" in adsl.columns:
    print(adsl["SUBJID"].head(10).tolist())

print("\nCurrent working directory:")
import os
print(os.getcwd())

print("\nADSL file being read:")
print(adsl_csv.resolve())

ADSL shape: (5146, 55)

Number of unique subjects:
USUBJID unique: 5146
SUBJID unique: 5146

First 10 SUBJID values:
[221, 222, 223, 323, 324, 448, 546, 553, 572, 602]

Current working directory:
c:\Users\anura\Desktop\MCI_AD_XAI_Project\Notebooks

ADSL file being read:
C:\Users\anura\Desktop\MCI_AD_XAI_Project\Data\ADSL_from_R.csv

In [70]:
print("ADSL shape:", adsl.shape)

print("\nNumber of unique subjects:")

for col in ["USUBJID", "SUBJID"]:
    if col in adsl.columns:
        print(col, "unique:", adsl[col].nunique())

print("\nFirst 10 SUBJID values:")
if "SUBJID" in adsl.columns:
    print(adsl["SUBJID"].head(10).tolist())

print("\nCurrent working directory:")
import os
print(os.getcwd())

print("\nADSL file being read:")
print(adsl_csv.resolve())

ADSL shape: (5146, 55)

Number of unique subjects:
USUBJID unique: 5146
SUBJID unique: 5146

First 10 SUBJID values:
[221, 222, 223, 323, 324, 448, 546, 553, 572, 602]

Current working directory:
c:\Users\anura\Desktop\MCI_AD_XAI_Project\Notebooks

ADSL file being read:
C:\Users\anura\Desktop\MCI_AD_XAI_Project\Data\ADSL_from_R.csv

In [71]:
# Inspect ADSL columns, data types, and missingness

import pandas as pd

adsl = pd.read_csv("../Data/ADSL_from_R.csv")

summary = pd.DataFrame({
    "Column": adsl.columns,
    "Data_Type": adsl.dtypes.astype(str).values,
    "Missing_Count": adsl.isna().sum().values,
    "Missing_Percent": (adsl.isna().mean() * 100).round(2).values,
    "Unique_Values": adsl.nunique(dropna=True).values
})

summary

          Column Data_Type  Missing_Count  Missing_Percent  Unique_Values
0        STUDYID       str              0             0.00              1
1        USUBJID       str              0             0.00           5146
2         SUBJID     int64              0             0.00           5146
3         SITEID     int64              0             0.00            112
4       ORIGPROT       str              0             0.00              5
5            AGE   float64            215             4.18            364
6           AGEU       str              0             0.00              1
7        AGEGR1N   float64            215             4.18              2
8         AGEGR1       str            215             4.18              2
9            SEX       str            211             4.10              2
10          RACE       str            229             4.45              7
11         RACEN   float64            229             4.45              7
12        ETHNIC       str            230             4.47              3
13        ENRLFL       str           2114            41.08              1
14         DTHFL       str           4887            94.97              1
15           ARM   float64           5146           100.00              0
16        ACTARM   float64           5146           100.00              0
17        ENRLDT       str           2114            41.08           1624
18         EOSDT       str           3967            77.09            794
19        EOSDTF       str           5008            97.32              1
20         DTHDT       str           4889            95.01             20
21        DTHDTF       str           4889            95.01              1
22          EDUC   float64           2117            41.14             16
23      MARISTAT       str           2118            41.16              6
24           BMI   float64           5107            99.24             39
25        BMIBLU       str           5107            99.24              1
26            DX       str           2116            41.12              3
27       AMYSTAT       str           3535            68.69              2
28      AMYSTATC       str           3535            68.69              2
29        TRACER       str           3535            68.69              2
30      IMAGERES       str           3535            68.69              1
31      ADASTT11   float64           2143            41.64            111
32      ADASTT13   float64           2155            41.88            150
33      CDGLOBAL   float64           2116            41.12              4
34         CDRSB   float64           2116            41.12             19
35      ECOGPTTT   float64           4459            86.65            167
36      ECOGSPTT   float64           4471            86.88            223
37      FAQTOTAL   float64           2164            42.05             31
38      FCISCORE   float64           4500            87.45             56
39       GDTOTAL   float64           3407            66.21              8
40       MMSCORE   float64           2119            41.18             17
41          MOCA   float64           3889            75.57             25
42      NPITOTAL   float64           3112            60.47             44
43      NPIQTOTL   float64           4192            81.46             18
44      DIGITSCR   float64           4332            84.18             68
45      LDELTOTL   float64           2117            41.14             24
46      LIMMTOTL   float64           2118            41.16             24
47       RAVLTFG   float64           2134            41.47             21
48      RAVLTFGP   float64           2141            41.61             87
49      RAVLTIMM   float64           2133            41.45             71
50      RAVLTLRN   float64           2133            41.45             18
51      TRABSCOR   float64           2195            42.65            254
52          APOE       str           2138            41.55              6
53    MPACCDIGIT   float64           4327            84.08            788
54  MPACCTRAILSB   float64           2114            41.08           2870

In [72]:
# Save the final 2-year MCI → AD cohort

final_cohort = first_mci[
    first_mci["PTID"].isin(converter_2yr_ids | nonconverter_2yr_ids)
].copy()

final_cohort = final_cohort.rename(
    columns={"EXAMDATE": "MCI_DATE"}
)

final_cohort["AD_CONVERSION_2YR"] = (
    final_cohort["PTID"].isin(converter_2yr_ids)
).astype(int)

final_cohort = final_cohort[
    ["PTID", "MCI_DATE", "AD_CONVERSION_2YR"]
].sort_values("PTID").reset_index(drop=True)

# Save
final_cohort.to_csv("../Data/final_cohort.csv", index=False)

print("Final cohort saved successfully.")
print("Shape:", final_cohort.shape)
print("\nOutcome distribution:")
print(final_cohort["AD_CONVERSION_2YR"].value_counts())

Final cohort saved successfully.
Shape: (997, 3)

Outcome distribution:
AD_CONVERSION_2YR
0    878
1    119
Name: count, dtype: int64

In [73]:
# Merge final cohort with ADSL

# Load the saved cohort
final_cohort = pd.read_csv("../Data/final_cohort.csv")

# Merge using SUBJID
merged_data = final_cohort.merge(
    adsl,
    left_on="PTID",
    right_on="USUBJID",
    how="left",
    indicator=True
)

print("Merged shape:", merged_data.shape)

print("\nMerge status:")
print(merged_data["_merge"].value_counts())

print("\nMatched participants:")
print((merged_data["_merge"] == "both").sum())

print("\nUnmatched participants:")
print((merged_data["_merge"] != "both").sum())

Merged shape: (997, 59)

Merge status:
_merge
left_only     997
right_only      0
both            0
Name: count, dtype: int64

Matched participants:
0

Unmatched participants:
997

In [74]:
# Compare identifiers between the final cohort and ADSL

print("FINAL COHORT identifiers:")
print(final_cohort["PTID"].head(10).tolist())

print("\nADSL USUBJID identifiers:")
print(adsl["USUBJID"].head(10).tolist())

print("\nADSL SUBJID identifiers:")
print(adsl["SUBJID"].head(10).tolist())

print("\nADSL STUDYID:")
print(adsl["STUDYID"].unique())

print("\nFinal cohort PTID data type:")
print(final_cohort["PTID"].dtype)

print("\nADSL USUBJID data type:")
print(adsl["USUBJID"].dtype)

FINAL COHORT identifiers:
['002_S_0729', '002_S_0782', '002_S_0954', '002_S_1070', '002_S_1155', '002_S_1268', '002_S_2010', '002_S_2073', '002_S_4171', '002_S_4229']

ADSL USUBJID identifiers:
['ADNI-001-00221', 'ADNI-001-00222', 'ADNI-001-00223', 'ADNI-001-00323', 'ADNI-001-00324', 'ADNI-001-00448', 'ADNI-001-00546', 'ADNI-001-00553', 'ADNI-001-00572', 'ADNI-001-00602']

ADSL SUBJID identifiers:
[221, 222, 223, 323, 324, 448, 546, 553, 572, 602]

ADSL STUDYID:
<StringArray>
['ADNI']
Length: 1, dtype: str

Final cohort PTID data type:
str

ADSL USUBJID data type:
str

In [75]:
from pathlib import Path

data_dir = Path("../Data/ADNIMERGE2/ADNIMERGE2/data")

# Find RDA files whose names may contain subject/demographic/enrollment information
rda_files = sorted(data_dir.glob("*.rda"))

keywords = [
    "DM", "DEM", "ENROLL", "SUBJ", "SUBJECT",
    "PARTICIP", "ADSL", "ADRS"
]

matching_files = [
    f.name for f in rda_files
    if any(k in f.stem.upper() for k in keywords)
]

print("Potential identifier/mapping datasets:")
for f in matching_files:
    print(f)

print("\nTotal RDA files:", len(rda_files))

Potential identifier/mapping datasets:
ADRS.rda
ADSL.rda
DM.rda
PTDEMOG.rda
RMT_PTDEMOG.rda

Total RDA files: 217

In [76]:
# Inspect PTDEMOG.rda using R

import subprocess

r_code = r"""
load("Data/ADNIMERGE2/ADNIMERGE2/data/PTDEMOG.rda")

print("Objects loaded:")
print(ls())

obj_name <- ls()[1]
obj <- get(obj_name)

print("\nObject class:")
print(class(obj))

print("\nDimensions:")
print(dim(obj))

print("\nColumn names:")
print(names(obj))

print("\nFirst 10 rows:")
print(head(obj, 10))
"""

result = subprocess.run(
    ["Rscript.exe", "-e", r_code],
    capture_output=True,
    text=True
)

print(result.stdout)

if result.stderr:
    print("\nR messages/warnings:")
    print(result.stderr)

R messages/warnings:
Error in readChar(con, 5L, useBytes = TRUE) : cannot open the connection
Calls: load -> readChar
In addition: Warning message:
In readChar(con, 5L, useBytes = TRUE) :
  cannot open compressed file 'Data/ADNIMERGE2/ADNIMERGE2/data/PTDEMOG.rda', probable reason 'No such file or directory'
Execution halted

In [77]:
# Inspect PTDEMOG.rda using its absolute path

import subprocess
from pathlib import Path

ptdemog_path = Path(
    "../Data/ADNIMERGE2/ADNIMERGE2/data/PTDEMOG.rda"
).resolve()

print("PTDEMOG path:")
print(ptdemog_path)

print("\nFile exists:", ptdemog_path.exists())

r_code = f'''
load("{ptdemog_path.as_posix()}")

print("Objects loaded:")
print(ls())

obj_name <- ls()[1]
obj <- get(obj_name)

print("\\nObject class:")
print(class(obj))

print("\\nDimensions:")
print(dim(obj))

print("\\nColumn names:")
print(names(obj))

print("\\nFirst 10 rows:")
print(head(obj, 10))
'''

result = subprocess.run(
    ["Rscript.exe", "-e", r_code],
    capture_output=True,
    text=True
)

print("\nR OUTPUT:")
print(result.stdout)

if result.stderr:
    print("\nR messages/warnings:")
    print(result.stderr)

PTDEMOG path:
C:\Users\anura\Desktop\MCI_AD_XAI_Project\Data\ADNIMERGE2\ADNIMERGE2\data\PTDEMOG.rda

File exists: True

R OUTPUT:
[1] "Objects loaded:"
[1] "PTDEMOG"
[1] "\nObject class:"
[1] "tbl_df"     "tbl"        "data.frame"
[1] "\nDimensions:"
[1] 6219   85
[1] "\nColumn names:"
 [1] "ORIGPROT"             "COLPROT"              "PTID"
 [4] "RID"                  "VISCODE"              "VISCODE2"
 [7] "VISDATE"              "PTSOURCE"             "PTGENDER"
[10] "PTDOB"                "PTDOBYY"              "PTHAND"
[13] "PTMARRY"              "PTEDUCAT"             "PTWORKHS"
[16] "PTWORK"               "PTNOTRT"              "PTRTYR"
[19] "PTHOME"               "PTTLANG"              "PTPLANG"
[22] "PTADBEG"              "PTCOGBEG"             "PTADDX"
[25] "PTETHCAT"             "PTRACCAT"             "PTIDENT"
[28] "PTORIENT"             "PTORIENTOT"           "PTENGSPK"
[31] "PTNLANG"              "PTENGSPKAGE"          "PTCLANG"
[34] "PTLANGSP"             "PTLANGWR"             "PTSPTIM"
[37] "PTSPOTTIM"            "PTLANGPR1"            "PTLANGSP1"
[40] "PTLANGRD1"            "PTLANGWR1"            "PTLANGUN1"
[43] "PTLANGPR2"            "PTLANGSP2"            "PTLANGRD2"
[46] "PTLANGWR2"            "PTLANGUN2"            "PTLANGPR3"
[49] "PTLANGSP3"            "PTLANGRD3"            "PTLANGWR3"
[52] "PTLANGUN3"            "PTLANGPR4"            "PTLANGSP4"
[55] "PTLANGRD4"            "PTLANGWR4"            "PTLANGUN4"
[58] "PTLANGPR5"            "PTLANGSP5"            "PTLANGRD5"
[61] "PTLANGWR5"            "PTLANGUN5"            "PTLANGPR6"
[64] "PTLANGSP6"            "PTLANGRD6"            "PTLANGWR6"
[67] "PTLANGUN6"            "PTLANGTTL"            "PTETHCATH"
[70] "PTASIAN"              "PTOPI"                "PTBORN"
[73] "PTBIRPL"              "PTIMMAGE"             "PTIMMWHY"
[76] "PTBIRPR"              "PTBIRGR"              "ID"
[79] "SITEID"               "USERDATE"             "USERDATE2"
[82] "DD_CRF_VERSION_LABEL" "LANGUAGE_CODE"        "HAS_QC_ERROR"
[85] "update_stamp"
[1] "\nFirst 10 rows:"
   ORIGPROT COLPROT       PTID RID VISCODE VISCODE2    VISDATE
1     ADNI1   ADNI1 011_S_0002   2      sc       sc 2005-08-17
2     ADNI1   ADNI1 022_S_0001   1       f        f 2005-08-18
3     ADNI1   ADNI1 011_S_0003   3      sc       sc 2005-08-18
4     ADNI1   ADNI1 022_S_0004   4      sc       sc 2005-08-18
5     ADNI1   ADNI1 011_S_0005   5      sc       sc 2005-08-23
6     ADNI1   ADNI1 022_S_0007   7      sc       sc 2005-08-25
7     ADNI1   ADNI1 022_S_0009   9       f        f 2005-08-26
8     ADNI1   ADNI1 011_S_0008   8      sc       sc 2005-08-29
9     ADNI1   ADNI1 011_S_0011  11       f        f 2005-09-07
10    ADNI1   ADNI1 022_S_0013  13       f        f 2005-09-09
            PTSOURCE PTGENDER   PTDOB PTDOBYY PTHAND PTMARRY PTEDUCAT PTWORKHS
1  Participant Visit     Male 04/1931    1931   Left Married       16     <NA>
2  Participant Visit   Female 12/1944    1944   <NA> Married       18     <NA>
3  Participant Visit     Male 05/1924    1924  Right Married       18     <NA>
4  Participant Visit     Male 01/1938    1938  Right Married       10     <NA>
5  Participant Visit     Male 12/1931    1931  Right Married       16     <NA>
6  Participant Visit     Male 04/1930    1930  Right Married       10     <NA>
7  Participant Visit   Female 01/1924    1924  Right Married       16     <NA>
8  Participant Visit   Female 03/1921    1921   Left Widowed       18     <NA>
9  Participant Visit   Female 08/1918    1918  Right Widowed       13     <NA>
10 Participant Visit   Female 09/1947    1947  Right Married       12     <NA>
   PTWORK PTNOTRT PTRTYR                  PTHOME PTTLANG PTPLANG PTADBEG
1    <NA>     Yes   1989 House (owned or rented) English English      NA
2    <NA>    <NA>     NA House (owned or rented)    <NA>    <NA>      NA
3    <NA>     Yes   1989      Apartment (rented) English English    1999
4    <NA>      No     NA House (owned or rented) Spanish Spanish      NA
5    <NA>     Yes   1987 House (owned or rented) English English      NA
6    <NA>     Yes   1995 House (owned or rented) Spanish Spanish    2002
7    <NA>     Yes   1955 House (owned or rented) English English    2001
8    <NA>     Yes   2000 House (owned or rented) English English      NA
9    <NA>      No     NA House (owned or rented) English English      NA
10   <NA>      No     NA      Apartment (rented) English English      NA
   PTCOGBEG PTADDX               PTETHCAT                  PTRACCAT PTIDENT
1        NA     NA Not Hispanic or Latino                     White    <NA>
2        NA     NA                   <NA>                      <NA>    <NA>
3        NA     NA Not Hispanic or Latino                     White    <NA>
4        NA     NA     Hispanic or Latino                     White    <NA>
5        NA     NA Not Hispanic or Latino                     White    <NA>
6        NA     NA     Hispanic or Latino        More than one race    <NA>
7        NA     NA Not Hispanic or Latino                     White    <NA>
8        NA     NA Not Hispanic or Latino                     White    <NA>
9        NA     NA Not Hispanic or Latino                     White    <NA>
10       NA     NA Not Hispanic or Latino Black or African American    <NA>
   PTORIENT PTORIENTOT PTENGSPK PTNLANG PTENGSPKAGE PTCLANG PTLANGSP PTLANGWR
1        NA       <NA>     <NA>    <NA>          NA    <NA>     <NA>     <NA>
2        NA       <NA>     <NA>    <NA>          NA    <NA>     <NA>     <NA>
3        NA       <NA>     <NA>    <NA>          NA    <NA>     <NA>     <NA>
4        NA       <NA>     <NA>    <NA>          NA    <NA>     <NA>     <NA>
5        NA       <NA>     <NA>    <NA>          NA    <NA>     <NA>     <NA>
6        NA       <NA>     <NA>    <NA>          NA    <NA>     <NA>     <NA>
7        NA       <NA>     <NA>    <NA>          NA    <NA>     <NA>     <NA>
8        NA       <NA>     <NA>    <NA>          NA    <NA>     <NA>     <NA>
9        NA       <NA>     <NA>    <NA>          NA    <NA>     <NA>     <NA>
10       NA       <NA>     <NA>    <NA>          NA    <NA>     <NA>     <NA>
   PTSPTIM PTSPOTTIM PTLANGPR1 PTLANGSP1 PTLANGRD1 PTLANGWR1 PTLANGUN1
1       NA        NA      <NA>      <NA>      <NA>      <NA>      <NA>
2       NA        NA      <NA>      <NA>      <NA>      <NA>      <NA>
3       NA        NA      <NA>      <NA>      <NA>      <NA>      <NA>
4       NA        NA      <NA>      <NA>      <NA>      <NA>      <NA>
5       NA        NA      <NA>      <NA>      <NA>      <NA>      <NA>
6       NA        NA      <NA>      <NA>      <NA>      <NA>      <NA>
7       NA        NA      <NA>      <NA>      <NA>      <NA>      <NA>
8       NA        NA      <NA>      <NA>      <NA>      <NA>      <NA>
9       NA        NA      <NA>      <NA>      <NA>      <NA>      <NA>
10      NA        NA      <NA>      <NA>      <NA>      <NA>      <NA>
   PTLANGPR2 PTLANGSP2 PTLANGRD2 PTLANGWR2 PTLANGUN2 PTLANGPR3 PTLANGSP3
1       <NA>      <NA>      <NA>      <NA>      <NA>      <NA>      <NA>
2       <NA>      <NA>      <NA>      <NA>      <NA>      <NA>      <NA>
3       <NA>      <NA>      <NA>      <NA>      <NA>      <NA>      <NA>
4       <NA>      <NA>      <NA>      <NA>      <NA>      <NA>      <NA>
5       <NA>      <NA>      <NA>      <NA>      <NA>      <NA>      <NA>
6       <NA>      <NA>      <NA>      <NA>      <NA>      <NA>      <NA>
7       <NA>      <NA>      <NA>      <NA>      <NA>      <NA>      <NA>
8       <NA>      <NA>      <NA>      <NA>      <NA>      <NA>      <NA>
9       <NA>      <NA>      <NA>      <NA>      <NA>      <NA>      <NA>
10      <NA>      <NA>      <NA>      <NA>      <NA>      <NA>      <NA>
   PTLANGRD3 PTLANGWR3 PTLANGUN3 PTLANGPR4 PTLANGSP4 PTLANGRD4 PTLANGWR4
1       <NA>      <NA>      <NA>      <NA>      <NA>      <NA>      <NA>
2       <NA>      <NA>      <NA>      <NA>      <NA>      <NA>      <NA>
3       <NA>      <NA>      <NA>      <NA>      <NA>      <NA>      <NA>
4       <NA>      <NA>      <NA>      <NA>      <NA>      <NA>      <NA>
5       <NA>      <NA>      <NA>      <NA>      <NA>      <NA>      <NA>
6       <NA>      <NA>      <NA>      <NA>      <NA>      <NA>      <NA>
7       <NA>      <NA>      <NA>      <NA>      <NA>      <NA>      <NA>
8       <NA>      <NA>      <NA>      <NA>      <NA>      <NA>      <NA>
9       <NA>      <NA>      <NA>      <NA>      <NA>      <NA>      <NA>
10      <NA>      <NA>      <NA>      <NA>      <NA>      <NA>      <NA>
   PTLANGUN4 PTLANGPR5 PTLANGSP5 PTLANGRD5 PTLANGWR5 PTLANGUN5 PTLANGPR6
1       <NA>      <NA>      <NA>      <NA>      <NA>      <NA>      <NA>
2       <NA>      <NA>      <NA>      <NA>      <NA>      <NA>      <NA>
3       <NA>      <NA>      <NA>      <NA>      <NA>      <NA>      <NA>
4       <NA>      <NA>      <NA>      <NA>      <NA>      <NA>      <NA>
5       <NA>      <NA>      <NA>      <NA>      <NA>      <NA>      <NA>
6       <NA>      <NA>      <NA>      <NA>      <NA>      <NA>      <NA>
7       <NA>      <NA>      <NA>      <NA>      <NA>      <NA>      <NA>
8       <NA>      <NA>      <NA>      <NA>      <NA>      <NA>      <NA>
9       <NA>      <NA>      <NA>      <NA>      <NA>      <NA>      <NA>
10      <NA>      <NA>      <NA>      <NA>      <NA>      <NA>      <NA>
   PTLANGSP6 PTLANGRD6 PTLANGWR6 PTLANGUN6 PTLANGTTL PTETHCATH PTASIAN PTOPI
1       <NA>      <NA>      <NA>      <NA>        NA      <NA>    <NA>  <NA>
2       <NA>      <NA>      <NA>      <NA>        NA      <NA>    <NA>  <NA>
3       <NA>      <NA>      <NA>      <NA>        NA      <NA>    <NA>  <NA>
4       <NA>      <NA>      <NA>      <NA>        NA      <NA>    <NA>  <NA>
5       <NA>      <NA>      <NA>      <NA>        NA      <NA>    <NA>  <NA>
6       <NA>      <NA>      <NA>      <NA>        NA      <NA>    <NA>  <NA>
7       <NA>      <NA>      <NA>      <NA>        NA      <NA>    <NA>  <NA>
8       <NA>      <NA>      <NA>      <NA>        NA      <NA>    <NA>  <NA>
9       <NA>      <NA>      <NA>      <NA>        NA      <NA>    <NA>  <NA>
10      <NA>      <NA>      <NA>      <NA>        NA      <NA>    <NA>  <NA>
   PTBORN PTBIRPL PTIMMAGE PTIMMWHY PTBIRPR PTBIRGR ID SITEID   USERDATE
1    <NA>    <NA>       NA     <NA>    <NA>    <NA> 18    107 2005-08-17
2    <NA>    <NA>       NA     <NA>    <NA>    <NA> 20     10 2005-08-18
3    <NA>    <NA>       NA     <NA>    <NA>    <NA> 22    107 2005-08-18
4    <NA>    <NA>       NA     <NA>    <NA>    <NA> 24     10 2005-08-18
5    <NA>    <NA>       NA     <NA>    <NA>    <NA> 26    107 2005-08-23
6    <NA>    <NA>       NA     <NA>    <NA>    <NA> 28     10 2005-08-25
7    <NA>    <NA>       NA     <NA>    <NA>    <NA> 30     10 2005-08-26
8    <NA>    <NA>       NA     <NA>    <NA>    <NA> 32    107 2005-08-30
9    <NA>    <NA>       NA     <NA>    <NA>    <NA> 34    107 2005-09-07
10   <NA>    <NA>       NA     <NA>    <NA>    <NA> 36     10 2005-09-09
   USERDATE2 DD_CRF_VERSION_LABEL LANGUAGE_CODE HAS_QC_ERROR update_stamp
1       <NA>                 <NA>          <NA>         <NA>   2005-08-17
2       <NA>                 <NA>          <NA>         <NA>   2005-08-18
3       <NA>                 <NA>          <NA>         <NA>   2005-08-18
4       <NA>                 <NA>          <NA>         <NA>   2005-08-18
5       <NA>                 <NA>          <NA>         <NA>   2005-08-23
6       <NA>                 <NA>          <NA>         <NA>   2005-08-25
7       <NA>                 <NA>          <NA>         <NA>   2005-08-26
8       <NA>                 <NA>          <NA>         <NA>   2005-08-30
9       <NA>                 <NA>          <NA>         <NA>   2005-09-07
10      <NA>                 <NA>          <NA>         <NA>   2005-09-09

In [78]:
# Extract PTID → RID mapping from PTDEMOG

import subprocess
from pathlib import Path

ptdemog_path = Path(
    "../Data/ADNIMERGE2/ADNIMERGE2/data/PTDEMOG.rda"
).resolve()

output_csv = Path("../Data/PTDEMOG_from_R.csv").resolve()

r_code = f'''
load("{ptdemog_path.as_posix()}")

write.csv(
    PTDEMOG[, c("PTID", "RID", "VISCODE", "VISCODE2", "VISDATE")],
    "{output_csv.as_posix()}",
    row.names = FALSE
)

cat("PTDEMOG exported successfully\\n")
cat("Rows:", nrow(PTDEMOG), "\\n")
'''

result = subprocess.run(
    ["Rscript.exe", "-e", r_code],
    capture_output=True,
    text=True
)

print(result.stdout)

if result.stderr:
    print("\nR messages/warnings:")
    print(result.stderr)

PTDEMOG exported successfully
Rows: 6219

In [79]:
# Load PTDEMOG mapping
ptdemog = pd.read_csv("../Data/PTDEMOG_from_R.csv")

# Match final cohort with PTDEMOG
cohort_ptdemog = final_cohort.merge(
    ptdemog[["PTID", "RID"]],
    on="PTID",
    how="left",
    indicator=True
)

print("Final cohort:", len(final_cohort))
print("Matched to PTDEMOG:", (cohort_ptdemog["_merge"] == "both").sum())
print("Unmatched:", (cohort_ptdemog["_merge"] == "left_only").sum())

print("\nDuplicate PTID matches:")
print(
    cohort_ptdemog["PTID"]
    .value_counts()
    .loc[lambda x: x > 1]
    .head(10)
)

Final cohort: 997
Matched to PTDEMOG: 1727
Unmatched: 0

Duplicate PTID matches:
PTID
003_S_1122    6
094_S_1417    6
003_S_0908    5
005_S_0448    5
014_S_0548    5
023_S_0061    5
100_S_0069    5
126_S_0605    5
002_S_0729    4
002_S_1155    4
Name: count, dtype: int64

In [80]:
# Convert dates to datetime
final_cohort["MCI_DATE"] = pd.to_datetime(final_cohort["MCI_DATE"])
ptdemog["VISDATE"] = pd.to_datetime(ptdemog["VISDATE"])

# Keep only PTDEMOG records whose visit date matches the participant's MCI date
baseline_demo = final_cohort.merge(
    ptdemog,
    left_on=["PTID", "MCI_DATE"],
    right_on=["PTID", "VISDATE"],
    how="left"
)

print("Final cohort:", len(final_cohort))
print("After baseline-date matching:", len(baseline_demo))

print("\nParticipants with a matched baseline demographic record:")
print(baseline_demo["RID"].notna().sum())

print("\nParticipants without a matched baseline demographic record:")
print(baseline_demo["RID"].isna().sum())

print("\nDuplicate PTIDs after baseline matching:")
print(
    baseline_demo["PTID"]
    .value_counts()
    .loc[lambda x: x > 1]
    .head(20)
)

Final cohort: 997
After baseline-date matching: 997

Participants with a matched baseline demographic record:
226

Participants without a matched baseline demographic record:
771

Duplicate PTIDs after baseline matching:
Series([], Name: count, dtype: int64)

In [81]:
# Inspect visit/date relationship only

sample_ids = final_cohort["PTID"].head(10).tolist()

sample_ptdemog = ptdemog[
    ptdemog["PTID"].isin(sample_ids)
].copy()

sample_ptdemog = sample_ptdemog.merge(
    final_cohort[["PTID", "MCI_DATE"]],
    on="PTID",
    how="left"
)

sample_ptdemog["DATE_DIFFERENCE_DAYS"] = (
    sample_ptdemog["VISDATE"] - sample_ptdemog["MCI_DATE"]
).dt.days

sample_ptdemog = sample_ptdemog.sort_values(
    ["PTID", "VISDATE"]
)

print(sample_ptdemog[
    [
        "PTID",
        "RID",
        "VISCODE",
        "VISCODE2",
        "VISDATE",
        "MCI_DATE",
        "DATE_DIFFERENCE_DAYS"
    ]
].to_string(index=False))

      PTID  RID VISCODE VISCODE2    VISDATE   MCI_DATE  DATE_DIFFERENCE_DAYS
002_S_0729  729      sc       sc 2006-07-06 2006-08-03                   -28
002_S_0729  729      sc       sc 2010-07-22 2006-08-03                  1449
002_S_0729  729     m54      m54 2011-02-07 2006-08-03                  1649
002_S_0729  729     v06      m60 2011-08-02 2006-08-03                  1825
002_S_0782  782      sc       sc 2006-07-26 2006-08-23                   -28
002_S_0954  954      sc       sc 2006-09-26 2006-11-22                   -57
002_S_1070 1070      sc       sc 2006-11-14 2006-12-27                   -43
002_S_1155 1155      sc       sc 2006-12-04 2007-01-10                   -37
002_S_1155 1155      sc       sc 2011-01-06 2007-01-10                  1457
002_S_1155 1155     v06      m60 2011-12-23 2007-01-10                  1808
002_S_1155 1155  4_init     m222 2025-05-14 2007-01-10                  6699
002_S_1268 1268      sc       sc 2007-01-24 2007-03-28                   -63
002_S_1268 1268      sc       sc 2011-04-13 2007-03-28                  1477
002_S_1268 1268     m48      m48 2011-04-21 2007-03-28                  1485
002_S_1268 1268     v06      m60 2012-03-13 2007-03-28                  1812
002_S_2010 2010      sc       sc 2010-06-10 2010-07-08                   -28
002_S_2010 2010     v06      m12 2011-07-07 2010-07-08                   364
002_S_2073 2073      sc       sc 2010-08-26 2010-09-21                   -26
002_S_2073 2073     v06      m12 2011-09-29 2010-09-21                   373
002_S_4171 4171     v01       sc 2011-08-04 2011-08-04                     0
002_S_4229 4229     v01       sc 2011-09-06 2011-09-06                     0

In [82]:
# Find the latest PTDEMOG visit on or before each participant's MCI date

baseline_demo_candidates = ptdemog[
    ["PTID", "RID", "VISCODE", "VISCODE2", "VISDATE"]
].copy()

baseline_demo_candidates = baseline_demo_candidates.merge(
    final_cohort[["PTID", "MCI_DATE"]],
    on="PTID",
    how="inner"
)

# Only records occurring on or before MCI baseline
baseline_demo_candidates = baseline_demo_candidates[
    baseline_demo_candidates["VISDATE"] <= baseline_demo_candidates["MCI_DATE"]
].copy()

# Select the latest available demographic record before/on MCI date
baseline_demo = (
    baseline_demo_candidates
    .sort_values(["PTID", "VISDATE"])
    .drop_duplicates("PTID", keep="last")
    .reset_index(drop=True)
)

print("Final cohort:", len(final_cohort))
print("Baseline demographic records found:", len(baseline_demo))
print("Participants without a record:", len(final_cohort) - len(baseline_demo))

print("\nSelected visit types:")
print(baseline_demo["VISCODE2"].value_counts().head(15))

Final cohort: 997
Baseline demographic records found: 993
Participants without a record: 4

Selected visit types:
VISCODE2
sc     960
m72     14
m60     10
m48      3
bl       3
m30      1
m03      1
m24      1
Name: count, dtype: int64

In [83]:
# Find ADNIMERGE2 datasets likely to contain our clinical/cognitive predictors

from pathlib import Path

data_dir = Path("../Data/ADNIMERGE2/ADNIMERGE2/data")

rda_files = sorted(data_dir.glob("*.rda"))

keywords = [
    "ADAS",
    "CDR",
    "MMSE",
    "MOCA",
    "FAQ",
    "RAVLT",
    "DIGIT",
    "TRAIL",
    "NPIT",
    "MEMORY",
    "COG",
    "PACC",
    "NEURO"
]

matching_files = sorted({
    f.name for f in rda_files
    if any(k in f.stem.upper() for k in keywords)
})

print("Potential clinical/cognitive datasets:")
for f in matching_files:
    print(f)

print("\nNumber found:", len(matching_files))

Potential clinical/cognitive datasets:
ADAS.rda
BHR_EVERYDAY_COGNITION.rda
BHR_SP_EVERYDAY_COGNITION.rda
BHR_SP_FAQ.rda
CDR.rda
ECOG12PT.rda
ECOG12SP.rda
ECOGPT.rda
ECOGSP.rda
FAQ.rda
MMSE.rda
MOCA.rda
NEUROBAT.rda
NEUROEXM.rda
NEUROPATH.rda
PACC.rda
RMT_ECOG12PT.rda
RMT_ECOG12SP.rda

Number found: 18

In [84]:
# Inspect the structure of the main clinical datasets

import subprocess
from pathlib import Path

data_dir = Path("../Data/ADNIMERGE2/ADNIMERGE2/data").resolve()

datasets = [
    "ADAS.rda",
    "CDR.rda",
    "MMSE.rda",
    "MOCA.rda",
    "FAQ.rda"
]

for filename in datasets:
    path = data_dir / filename

    r_code = f'''
load("{path.as_posix()}")

cat("\\n==================== {filename} ====================\\n")
cat("Objects:", paste(ls(), collapse=", "), "\\n")

obj_name <- ls()[1]
obj <- get(obj_name)

cat("Class:", paste(class(obj), collapse=", "), "\\n")
cat("Dimensions:", paste(dim(obj), collapse=" x "), "\\n")
cat("Columns:\\n")
print(names(obj))
'''

    result = subprocess.run(
        ["Rscript.exe", "-e", r_code],
        capture_output=True,
        text=True
    )

    print(result.stdout)

    if result.stderr:
        print("R messages/warnings:")
        print(result.stderr)

==================== ADAS.rda ====================
Objects: ADAS
Class: tbl_df, tbl, data.frame
Dimensions: 12868 x 17
Columns:
 [1] "ORIGPROT"             "COLPROT"              "PTID"
 [4] "RID"                  "VISCODE"              "VISCODE2"
 [7] "VISDATE"              "TOTSCORE"             "TOTAL13"
[10] "ID"                   "SITEID"               "USERDATE"
[13] "USERDATE2"            "DD_CRF_VERSION_LABEL" "LANGUAGE_CODE"
[16] "HAS_QC_ERROR"         "update_stamp"


==================== CDR.rda ====================
Objects: CDR
Class: tbl_df, tbl, data.frame
Dimensions: 14617 x 26
Columns:
 [1] "ORIGPROT"             "COLPROT"              "PTID"
 [4] "RID"                  "VISCODE"              "VISCODE2"
 [7] "VISDATE"              "CDSOURCE"             "CDVERSION"
[10] "SPID"                 "CDMEMORY"             "CDORIENT"
[13] "CDJUDGE"              "CDCOMMUN"             "CDHOME"
[16] "CDCARE"               "CDGLOBAL"             "CDRSB"
[19] "ID"                   "SITEID"               "USERDATE"
[22] "USERDATE2"            "DD_CRF_VERSION_LABEL" "LANGUAGE_CODE"
[25] "HAS_QC_ERROR"         "update_stamp"


==================== MMSE.rda ====================
Objects: MMSE
Class: tbl_df, tbl, data.frame
Dimensions: 14599 x 59
Columns:
 [1] "ORIGPROT"             "COLPROT"              "PTID"
 [4] "RID"                  "VISCODE"              "VISCODE2"
 [7] "VISDATE"              "DONE"                 "NDREASON"
[10] "SOURCE"               "MMDATE"               "MMYEAR"
[13] "MMMONTH"              "MMDAY"                "MMSEASON"
[16] "MMHOSPIT"             "MMFLOOR"              "MMCITY"
[19] "MMAREA"               "MMSTATE"              "WORDLIST"
[22] "WORD1"                "WORD2"                "WORD3"
[25] "MMTRIALS"             "MMD"                  "MML"
[28] "MMR"                  "MMO"                  "MMW"
[31] "MMLTR1"               "MMLTR2"               "MMLTR3"
[34] "MMLTR4"               "MMLTR5"               "MMLTR6"
[37] "MMLTR7"               "WORLDSCORE"           "WORD1DL"
[40] "WORD2DL"              "WORD3DL"              "MMWATCH"
[43] "MMPENCIL"             "MMREPEAT"             "MMHAND"
[46] "MMFOLD"               "MMONFLR"              "MMREAD"
[49] "MMWRITE"              "MMDRAW"               "MMSCORE"
[52] "ID"                   "SITEID"               "USERDATE"
[55] "USERDATE2"            "DD_CRF_VERSION_LABEL" "LANGUAGE_CODE"
[58] "HAS_QC_ERROR"         "update_stamp"


==================== MOCA.rda ====================
Objects: MOCA
Class: tbl_df, tbl, data.frame
Dimensions: 8962 x 59
Columns:
 [1] "ORIGPROT"             "COLPROT"              "PTID"
 [4] "RID"                  "VISCODE"              "VISCODE2"
 [7] "VISDATE"              "TRAILS"               "CUBE"
[10] "CLOCKCON"             "CLOCKNO"              "CLOCKHAN"
[13] "LION"                 "RHINO"                "CAMEL"
[16] "IMMT1W1"              "IMMT1W2"              "IMMT1W3"
[19] "IMMT1W4"              "IMMT1W5"              "IMMT2W1"
[22] "IMMT2W2"              "IMMT2W3"              "IMMT2W4"
[25] "IMMT2W5"              "DIGFOR"               "DIGBACK"
[28] "LETTERS"              "SERIAL1"              "SERIAL2"
[31] "SERIAL3"              "SERIAL4"              "SERIAL5"
[34] "REPEAT1"              "REPEAT2"              "FFLUENCY"
[37] "ABSTRAN"              "ABSMEAS"              "DELW1"
[40] "DELW2"                "DELW3"                "DELW4"
[43] "DELW5"                "DATE"                 "MONTH"
[46] "YEAR"                 "DAY"                  "PLACE"
[49] "CITY"                 "MOCA"                 "SOURCE"
[52] "ID"                   "SITEID"               "USERDATE"
[55] "USERDATE2"            "DD_CRF_VERSION_LABEL" "LANGUAGE_CODE"
[58] "HAS_QC_ERROR"         "update_stamp"


==================== FAQ.rda ====================
Objects: FAQ
Class: tbl_df, tbl, data.frame
Dimensions: 13272 x 28
Columns:
 [1] "ORIGPROT"             "COLPROT"              "PTID"
 [4] "RID"                  "VISCODE"              "VISCODE2"
 [7] "VISDATE"              "SOURCE"               "FAQFINAN"
[10] "FAQFORM"              "FAQSHOP"              "FAQGAME"
[13] "FAQBEVG"              "FAQMEAL"              "FAQEVENT"
[16] "FAQTV"                "FAQREM"               "FAQTRAVL"
[19] "FAQTOTAL"             "SPID"                 "ID"
[22] "SITEID"               "USERDATE"             "USERDATE2"
[25] "DD_CRF_VERSION_LABEL" "LANGUAGE_CODE"        "HAS_QC_ERROR"
[28] "update_stamp"

In [85]:
# Check how many participants have clinical measurements
# available on or before their first MCI date

clinical_datasets = {
    "ADAS": "../Data/ADNIMERGE2/ADNIMERGE2/data/ADAS.rda",
    "CDR": "../Data/ADNIMERGE2/ADNIMERGE2/data/CDR.rda",
    "MMSE": "../Data/ADNIMERGE2/ADNIMERGE2/data/MMSE.rda",
    "MOCA": "../Data/ADNIMERGE2/ADNIMERGE2/data/MOCA.rda",
    "FAQ": "../Data/ADNIMERGE2/ADNIMERGE2/data/FAQ.rda"
}

# We only need the number of records for now.
# R will inspect each dataset and count participants
# having at least one visit on/before their MCI date.

for name, path in clinical_datasets.items():

    r_code = f'''
    load("{Path(path).resolve().as_posix()}")

    obj <- get(ls()[1])

    # Export only the necessary identifying/date fields temporarily
    tmp <- obj[, c("PTID", "RID", "VISDATE")]

    write.csv(
        tmp,
        "temp_{name}.csv",
        row.names = FALSE
    )

    cat("{name}:", nrow(tmp), "records exported\\n")
    '''

    result = subprocess.run(
        ["Rscript.exe", "-e", r_code],
        capture_output=True,
        text=True
    )

    print(result.stdout)

    if result.stderr:
        print(result.stderr)

ADAS: 12868 records exported

CDR: 14617 records exported

MMSE: 14599 records exported

MOCA: 8962 records exported

FAQ: 13272 records exported

In [86]:
# Calculate baseline availability for each clinical dataset

clinical_files = {
    "ADAS": "temp_ADAS.csv",
    "CDR": "temp_CDR.csv",
    "MMSE": "temp_MMSE.csv",
    "MOCA": "temp_MOCA.csv",
    "FAQ": "temp_FAQ.csv"
}

availability_results = []

for name, filename in clinical_files.items():

    temp = pd.read_csv(filename)
    temp["VISDATE"] = pd.to_datetime(temp["VISDATE"])

    # Match each clinical record to our cohort's MCI date
    temp = temp.merge(
        final_cohort[["PTID", "MCI_DATE"]],
        on="PTID",
        how="inner"
    )

    # Keep only measurements available on or before MCI baseline
    temp_baseline = temp[
        temp["VISDATE"] <= temp["MCI_DATE"]
    ].copy()

    # One participant = one baseline record
    baseline_records = (
        temp_baseline
        .sort_values(["PTID", "VISDATE"])
        .drop_duplicates("PTID", keep="last")
    )

    availability_results.append({
        "Dataset": name,
        "Cohort_Participants": len(final_cohort),
        "Participants_With_Baseline_Record": baseline_records["PTID"].nunique(),
        "Missing_Baseline_Record": (
            len(final_cohort) -
            baseline_records["PTID"].nunique()
        )
    })

availability_table = pd.DataFrame(availability_results)

availability_table["Availability_Percent"] = (
    availability_table["Participants_With_Baseline_Record"]
    / availability_table["Cohort_Participants"] * 100
).round(2)

availability_table

,Dataset,Cohort_Participants,Participants_With_Baseline_Record,Missing_Baseline_Record,Availability_Percent
0,ADAS,997,535,462,53.66
1,CDR,997,993,4,99.60
2,MMSE,997,993,4,99.60
3,MOCA,997,194,803,19.46
4,FAQ,997,526,471,52.76

In [87]:
# Inspect actual baseline measurement availability and missingness

clinical_data = {}

for name, filename in {
    "ADAS": "ADAS.rda",
    "CDR": "CDR.rda",
    "MMSE": "MMSE.rda",
    "MOCA": "MOCA.rda",
    "FAQ": "FAQ.rda"
}.items():

    path = (data_dir / filename).resolve()

    # R code: export the complete dataset
    output_file = Path(f"../Data/{name}_from_R.csv").resolve()

    r_code = f'''
    load("{path.as_posix()}")
    obj <- get(ls()[1])
    write.csv(obj, "{output_file.as_posix()}", row.names=FALSE)
    cat("{name} exported:", nrow(obj), "rows\\n")
    '''

    result = subprocess.run(
        ["Rscript.exe", "-e", r_code],
        capture_output=True,
        text=True
    )

    print(result.stdout)

    if result.stderr:
        print(result.stderr)

print("\nAll clinical datasets exported.")

ADAS exported: 12868 rows

CDR exported: 14617 rows

MMSE exported: 14599 rows

MOCA exported: 8962 rows

FAQ exported: 13272 rows


All clinical datasets exported.

In [88]:
# Extract baseline clinical measurements for the 997-person cohort

# Load the clinical datasets
adas = pd.read_csv("../Data/ADAS_from_R.csv")
cdr = pd.read_csv("../Data/CDR_from_R.csv")
mmse = pd.read_csv("../Data/MMSE_from_R.csv")
faq = pd.read_csv("../Data/FAQ_from_R.csv")

# Convert dates
for df in [adas, cdr, mmse, faq]:
    df["VISDATE"] = pd.to_datetime(df["VISDATE"])

# Make sure cohort date is datetime
final_cohort["MCI_DATE"] = pd.to_datetime(final_cohort["MCI_DATE"])


def get_baseline_measurements(df, value_columns):
    """
    Select the latest available measurement on or before
    each participant's first MCI date.
    """

    temp = df[
        ["PTID", "RID", "VISDATE"] + value_columns
    ].copy()

    # Attach MCI baseline date
    temp = temp.merge(
        final_cohort[["PTID", "MCI_DATE"]],
        on="PTID",
        how="inner"
    )

    # Only information available at or before prediction time
    temp = temp[
        temp["VISDATE"] <= temp["MCI_DATE"]
    ].copy()

    # Latest available assessment
    temp = (
        temp
        .sort_values(["PTID", "VISDATE"])
        .drop_duplicates("PTID", keep="last")
        .reset_index(drop=True)
    )

    return temp


# Extract baseline values
baseline_adas = get_baseline_measurements(
    adas,
    ["TOTSCORE", "TOTAL13"]
)

baseline_cdr = get_baseline_measurements(
    cdr,
    ["CDGLOBAL", "CDRSB"]
)

baseline_mmse = get_baseline_measurements(
    mmse,
    ["MMSCORE"]
)

baseline_faq = get_baseline_measurements(
    faq,
    ["FAQTOTAL"]
)


# Keep only the variables we need
baseline_adas = baseline_adas[
    ["PTID", "TOTSCORE", "TOTAL13"]
]

baseline_cdr = baseline_cdr[
    ["PTID", "CDGLOBAL", "CDRSB"]
]

baseline_mmse = baseline_mmse[
    ["PTID", "MMSCORE"]
]

baseline_faq = baseline_faq[
    ["PTID", "FAQTOTAL"]
]


# Merge everything into the final cohort
clinical_baseline = final_cohort.merge(
    baseline_adas, on="PTID", how="left"
)

clinical_baseline = clinical_baseline.merge(
    baseline_cdr, on="PTID", how="left"
)

clinical_baseline = clinical_baseline.merge(
    baseline_mmse, on="PTID", how="left"
)

clinical_baseline = clinical_baseline.merge(
    baseline_faq, on="PTID", how="left"
)


# Report availability
feature_columns = [
    "TOTSCORE",
    "TOTAL13",
    "CDGLOBAL",
    "CDRSB",
    "MMSCORE",
    "FAQTOTAL"
]

availability = pd.DataFrame({
    "Feature": feature_columns,
    "Available": [
        clinical_baseline[col].notna().sum()
        for col in feature_columns
    ],
    "Missing": [
        clinical_baseline[col].isna().sum()
        for col in feature_columns
    ]
})

availability["Availability_%"] = (
    availability["Available"] / len(clinical_baseline) * 100
).round(2)

print("Clinical baseline dataset shape:")
print(clinical_baseline.shape)

print("\nFeature availability:")
print(availability.to_string(index=False))

Clinical baseline dataset shape:
(997, 9)

Feature availability:
 Feature  Available  Missing  Availability_%
TOTSCORE        535      462           53.66
 TOTAL13        532      465           53.36
CDGLOBAL        992        5           99.50
   CDRSB        991        6           99.40
 MMSCORE        993        4           99.60
FAQTOTAL        520      477           52.16

In [89]:
# Extract demographic variables from PTDEMOG at MCI baseline

from pathlib import Path
import subprocess

ptdemog_path = Path(
    "../Data/ADNIMERGE2/ADNIMERGE2/data/PTDEMOG.rda"
).resolve()

output_file = Path(
    "../Data/PTDEMOG_demographics_from_R.csv"
).resolve()

r_code = f'''
load("{ptdemog_path.as_posix()}")

demo <- PTDEMOG[, c(
    "PTID",
    "RID",
    "VISCODE",
    "VISCODE2",
    "VISDATE",
    "PTGENDER",
    "PTEDUCAT",
    "PTETHCAT",
    "PTRACCAT"
)]

write.csv(
    demo,
    "{output_file.as_posix()}",
    row.names = FALSE
)

cat("Exported:", nrow(demo), "rows\\n")
'''

result = subprocess.run(
    ["Rscript.exe", "-e", r_code],
    capture_output=True,
    text=True
)

print(result.stdout)

if result.stderr:
    print("\nR messages/warnings:")
    print(result.stderr)

Exported: 6219 rows

In [90]:
# Select baseline demographic record for each participant

demo = pd.read_csv("../Data/PTDEMOG_demographics_from_R.csv")
demo["VISDATE"] = pd.to_datetime(demo["VISDATE"])
final_cohort["MCI_DATE"] = pd.to_datetime(final_cohort["MCI_DATE"])

# Attach each participant's MCI date
demo = demo.merge(
    final_cohort[["PTID", "MCI_DATE"]],
    on="PTID",
    how="inner"
)

# Only use demographic information available on/before MCI baseline
demo_baseline = demo[
    demo["VISDATE"] <= demo["MCI_DATE"]
].copy()

# Select the latest available demographic record
demo_baseline = (
    demo_baseline
    .sort_values(["PTID", "VISDATE"])
    .drop_duplicates("PTID", keep="last")
    .reset_index(drop=True)
)

# Merge demographics with final cohort
demo_baseline = final_cohort.merge(
    demo_baseline[
        [
            "PTID",
            "RID",
            "VISCODE",
            "VISCODE2",
            "VISDATE",
            "PTGENDER",
            "PTEDUCAT",
            "PTETHCAT",
            "PTRACCAT"
        ]
    ],
    on="PTID",
    how="left"
)

print("Final cohort:", len(final_cohort))
print("Demographic records:", len(demo_baseline))

print("\nMissing demographic values:")
print(
    demo_baseline[
        ["PTGENDER", "PTEDUCAT", "PTETHCAT", "PTRACCAT"]
    ].isna().sum()
)

print("\nDemographic availability (%):")

for col in ["PTGENDER", "PTEDUCAT", "PTETHCAT", "PTRACCAT"]:
    available = demo_baseline[col].notna().sum()
    percentage = available / len(final_cohort) * 100
    print(f"{col}: {available}/997 ({percentage:.2f}%)")

Final cohort: 997
Demographic records: 997

Missing demographic values:
PTGENDER    11
PTEDUCAT    11
PTETHCAT    11
PTRACCAT    11
dtype: int64

Demographic availability (%):
PTGENDER: 986/997 (98.90%)
PTEDUCAT: 986/997 (98.90%)
PTETHCAT: 986/997 (98.90%)
PTRACCAT: 986/997 (98.90%)

In [91]:
# Inspect ADSL AGE for our 997-person cohort
# using the PTID → RID mapping

age_check = final_cohort.merge(
    demo_baseline[["PTID", "RID"]],
    on="PTID",
    how="left"
)

age_check = age_check.merge(
    adsl[["SUBJID", "AGE", "EDUC", "SEX", "RACE", "ETHNIC", "APOE"]],
    left_on="RID",
    right_on="SUBJID",
    how="left"
)

print("Shape:", age_check.shape)

print("\nAGE availability:")
print("Available:", age_check["AGE"].notna().sum())
print("Missing:", age_check["AGE"].isna().sum())

print("\nAGE summary:")
print(age_check["AGE"].describe())

print("\nFirst 10 participants:")
print(
    age_check[
        ["PTID", "RID", "MCI_DATE", "AGE", "EDUC", "SEX", "RACE", "ETHNIC", "APOE"]
    ].head(10).to_string(index=False)
)

Shape: (997, 11)

AGE availability:
Available: 993
Missing: 4

AGE summary:
count    993.000000
mean      72.814602
std        7.307407
min       55.000000
25%       68.000000
50%       73.000000
75%       78.100000
max       91.400000
Name: AGE, dtype: float64

First 10 participants:
      PTID    RID   MCI_DATE  AGE  EDUC    SEX               RACE                 ETHNIC  APOE
002_S_0729  729.0 2006-08-03 65.2  16.0 Female              White Not Hispanic or Latino ε3/ε4
002_S_0782  782.0 2006-08-23 81.6  16.0   Male              White Not Hispanic or Latino ε3/ε3
002_S_0954  954.0 2006-11-22 69.4  14.0 Female              White Not Hispanic or Latino ε3/ε4
002_S_1070 1070.0 2006-12-27 73.7  14.0   Male              White Not Hispanic or Latino ε3/ε3
002_S_1155 1155.0 2007-01-10 57.9  20.0   Male              White Not Hispanic or Latino ε3/ε3
002_S_1268 1268.0 2007-03-28 82.7  20.0   Male              White Not Hispanic or Latino ε3/ε4
002_S_2010 2010.0 2010-07-08 62.9  20.0 Female More than one race Not Hispanic or Latino ε3/ε4
002_S_2073 2073.0 2010-09-21 63.4  20.0 Female              White Not Hispanic or Latino ε3/ε3
002_S_4171 4171.0 2011-08-04 69.4  16.0   Male              White Not Hispanic or Latino ε3/ε3
002_S_4229 4229.0 2011-09-06 66.4  15.0   Male              White Not Hispanic or Latino ε3/ε3

In [92]:
# Check APOE availability and distribution in the final cohort

print("APOE availability:")
print("Available:", age_check["APOE"].notna().sum())
print("Missing:", age_check["APOE"].isna().sum())
print(
    "Availability:",
    round(age_check["APOE"].notna().mean() * 100, 2),
    "%"
)

print("\nAPOE distribution:")
print(
    age_check["APOE"]
    .value_counts(dropna=False)
    .sort_index()
)

APOE availability:
Available: 991
Missing: 6
Availability: 99.4 %

APOE distribution:
APOE
ε2/ε3     64
ε2/ε4     23
ε3/ε3    462
ε3/ε4    349
ε4/ε4     93
NaN        6
Name: count, dtype: int64

In [93]:
# Find MRI / neuroimaging datasets already available in ADNIMERGE2

keywords = [
    "MRI",
    "FREESURFER",
    "FS",
    "MORPH",
    "VOLUME",
    "IMAGE",
    "NEURO"
]

mri_files = sorted({
    f.name for f in rda_files
    if any(k in f.stem.upper() for k in keywords)
})

print("Potential MRI/neuroimaging datasets:")
for f in mri_files:
    print(f)

print("\nNumber found:", len(mri_files))

Potential MRI/neuroimaging datasets:
BAIMRINMRC.rda
MAYOADIRL_MRI_FMRI.rda
MAYOADIRL_MRI_FMRI_NFQ.rda
MAYOADIRL_MRI_MCH.rda
MAYOADIRL_MRI_QUALITY_ADNI3.rda
MAYOADIRL_MRI_TBMSYN.rda
MRI3META.rda
MRIB1CALIB.rda
MRIFind.rda
MRIMETA.rda
MRIMPPRO.rda
MRIMPRANK.rda
MRINCLUSIO.rda
MRINFQ.rda
MRIPROT.rda
MRIQC.rda
MRIQSM.rda
MRIREAD.rda
MRISERIAL.rda
MRI_INFARCTS.rda
NEUROBAT.rda
NEUROEXM.rda
NEUROPATH.rda
UCSFASLFSCBF.rda
UCSFASLFS_V2.rda
UCSFFSL.rda
UCSFFSL51.rda
UCSFFSL51ALL.rda
UCSFFSL51Y1.rda
UCSFFSX.rda
UCSFFSX51.rda
UCSFFSX51_ADNI1_3T.rda
UCSFFSX6.rda
UCSFFSX7.rda
UCSFSNTVOL.rda

Number found: 35

In [94]:
# Inspect the main UCSF FreeSurfer MRI datasets

mri_candidates = [
    "UCSFFSX.rda",
    "UCSFFSX51.rda",
    "UCSFFSX6.rda",
    "UCSFFSX7.rda",
    "UCSFFSX51ALL.rda"
]

for filename in mri_candidates:

    path = (data_dir / filename).resolve()

    r_code = f'''
    load("{path.as_posix()}")

    cat("\\n==================== {filename} ====================\\n")

    obj_name <- ls()[1]
    obj <- get(obj_name)

    cat("Object:", obj_name, "\\n")
    cat("Dimensions:", paste(dim(obj), collapse=" x "), "\\n")
    cat("Number of columns:", ncol(obj), "\\n")
    cat("Columns:\\n")
    print(names(obj))
    '''

    result = subprocess.run(
        ["Rscript.exe", "-e", r_code],
        capture_output=True,
        text=True
    )

    print(result.stdout)

    if result.stderr:
        print("R messages/warnings:")
        print(result.stderr)

==================== UCSFFSX.rda ====================
Object: UCSFFSX
Dimensions: 4486 x 367
Number of columns: 367
Columns:
  [1] "ORIGPROT"     "RID"          "VISCODE"      "EXAMDATE"     "VERSION"
  [6] "LONISID"      "FLDSTRENG"    "LONIUID"      "IMAGEUID"     "RUNDATE"
 [11] "STATUS"       "OVERALLQC"    "TEMPQC"       "FRONTQC"      "PARQC"
 [16] "INSULAQC"     "OCCQC"        "BGQC"         "CWMQC"        "VENTQC"
 [21] "ST100SV"      "ST101SV"      "ST102CV"      "ST102SA"      "ST102TA"
 [26] "ST102TS"      "ST103CV"      "ST103SA"      "ST103TA"      "ST103TS"
 [31] "ST104CV"      "ST104SA"      "ST104TA"      "ST104TS"      "ST105CV"
 [36] "ST105SA"      "ST105TA"      "ST105TS"      "ST106CV"      "ST106SA"
 [41] "ST106TA"      "ST106TS"      "ST107CV"      "ST107SA"      "ST107TA"
 [46] "ST107TS"      "ST108CV"      "ST108SA"      "ST108TA"      "ST108TS"
 [51] "ST109CV"      "ST109SA"      "ST109TA"      "ST109TS"      "ST10CV"
 [56] "ST110CV"      "ST110SA"      "ST110TA"      "ST110TS"      "ST111CV"
 [61] "ST111SA"      "ST111TA"      "ST111TS"      "ST112SV"      "ST113CV"
 [66] "ST113SA"      "ST113TA"      "ST113TS"      "ST114CV"      "ST114SA"
 [71] "ST114TA"      "ST114TS"      "ST115CV"      "ST115SA"      "ST115TA"
 [76] "ST115TS"      "ST116CV"      "ST116SA"      "ST116TA"      "ST116TS"
 [81] "ST117CV"      "ST117SA"      "ST117TA"      "ST117TS"      "ST118CV"
 [86] "ST118SA"      "ST118TA"      "ST118TS"      "ST119CV"      "ST119SA"
 [91] "ST119TA"      "ST119TS"      "ST11SV"       "ST120SV"      "ST121CV"
 [96] "ST121SA"      "ST121TA"      "ST121TS"      "ST122SV"      "ST123CV"
[101] "ST123SA"      "ST123TA"      "ST123TS"      "ST124SV"      "ST125SV"
[106] "ST126SV"      "ST127SV"      "ST128SV"      "ST129CV"      "ST129SA"
[111] "ST129TA"      "ST129TS"      "ST12SV"       "ST130CV"      "ST130SA"
[116] "ST130TA"      "ST130TS"      "ST13CV"       "ST13SA"       "ST13TA"
[121] "ST13TS"       "ST14CV"       "ST14SA"       "ST14TA"       "ST14TS"
[126] "ST15CV"       "ST15SA"       "ST15TA"       "ST15TS"       "ST16SV"
[131] "ST17SV"       "ST18SV"       "ST19SV"       "ST1SV"        "ST20SV"
[136] "ST21SV"       "ST22CV"       "ST22SA"       "ST22TA"       "ST22TS"
[141] "ST23CV"       "ST23SA"       "ST23TA"       "ST23TS"       "ST24CV"
[146] "ST24SA"       "ST24TA"       "ST24TS"       "ST25CV"       "ST25SA"
[151] "ST25TA"       "ST25TS"       "ST26CV"       "ST26SA"       "ST26TA"
[156] "ST26TS"       "ST27SA"       "ST28CV"       "ST29SV"       "ST2SV"
[161] "ST30SV"       "ST31CV"       "ST31SA"       "ST31TA"       "ST31TS"
[166] "ST32CV"       "ST32SA"       "ST32TA"       "ST32TS"       "ST33SV"
[171] "ST34CV"       "ST34SA"       "ST34TA"       "ST34TS"       "ST35CV"
[176] "ST35SA"       "ST35TA"       "ST35TS"       "ST36CV"       "ST36SA"
[181] "ST36TA"       "ST36TS"       "ST37SV"       "ST38CV"       "ST38SA"
[186] "ST38TA"       "ST38TS"       "ST39CV"       "ST39SA"       "ST39TA"
[191] "ST39TS"       "ST3SV"        "ST40CV"       "ST40SA"       "ST40TA"
[196] "ST40TS"       "ST41SV"       "ST42SV"       "ST43CV"       "ST43SA"
[201] "ST43TA"       "ST43TS"       "ST44CV"       "ST44SA"       "ST44TA"
[206] "ST44TS"       "ST45CV"       "ST45SA"       "ST45TA"       "ST45TS"
[211] "ST46CV"       "ST46SA"       "ST46TA"       "ST46TS"       "ST47CV"
[216] "ST47SA"       "ST47TA"       "ST47TS"       "ST48CV"       "ST48SA"
[221] "ST48TA"       "ST48TS"       "ST49CV"       "ST49SA"       "ST49TA"
[226] "ST49TS"       "ST4SV"        "ST50CV"       "ST50SA"       "ST50TA"
[231] "ST50TS"       "ST51CV"       "ST51SA"       "ST51TA"       "ST51TS"
[236] "ST52CV"       "ST52SA"       "ST52TA"       "ST52TS"       "ST53SV"
[241] "ST54CV"       "ST54SA"       "ST54TA"       "ST54TS"       "ST55CV"
[246] "ST55SA"       "ST55TA"       "ST55TS"       "ST56CV"       "ST56SA"
[251] "ST56TA"       "ST56TS"       "ST57CV"       "ST57SA"       "ST57TA"
[256] "ST57TS"       "ST58CV"       "ST58SA"       "ST58TA"       "ST58TS"
[261] "ST59CV"       "ST59SA"       "ST59TA"       "ST59TS"       "ST5SV"
[266] "ST60CV"       "ST60SA"       "ST60TA"       "ST60TS"       "ST61SV"
[271] "ST62CV"       "ST62SA"       "ST62TA"       "ST62TS"       "ST63SV"
[276] "ST64CV"       "ST64SA"       "ST64TA"       "ST64TS"       "ST65SV"
[281] "ST66SV"       "ST67SV"       "ST68SV"       "ST69SV"       "ST6SV"
[286] "ST70SV"       "ST71SV"       "ST72CV"       "ST72SA"       "ST72TA"
[291] "ST72TS"       "ST73CV"       "ST73SA"       "ST73TA"       "ST73TS"
[296] "ST74CV"       "ST74SA"       "ST74TA"       "ST74TS"       "ST75SV"
[301] "ST76SV"       "ST77SV"       "ST78SV"       "ST79SV"       "ST7SV"
[306] "ST80SV"       "ST81CV"       "ST81SA"       "ST81TA"       "ST81TS"
[311] "ST82CV"       "ST82SA"       "ST82TA"       "ST82TS"       "ST83CV"
[316] "ST83SA"       "ST83TA"       "ST83TS"       "ST84CV"       "ST84SA"
[321] "ST84TA"       "ST84TS"       "ST85CV"       "ST85SA"       "ST85TA"
[326] "ST85TS"       "ST86SA"       "ST87CV"       "ST88SV"       "ST89SV"
[331] "ST8SV"        "ST90CV"       "ST90SA"       "ST90TA"       "ST90TS"
[336] "ST91CV"       "ST91SA"       "ST91TA"       "ST91TS"       "ST92SV"
[341] "ST93CV"       "ST93SA"       "ST93TA"       "ST93TS"       "ST94CV"
[346] "ST94SA"       "ST94TA"       "ST94TS"       "ST95CV"       "ST95SA"
[351] "ST95TA"       "ST95TS"       "ST96SV"       "ST97CV"       "ST97SA"
[356] "ST97TA"       "ST97TS"       "ST98CV"       "ST98SA"       "ST98TA"
[361] "ST98TS"       "ST99CV"       "ST99SA"       "ST99TA"       "ST99TS"
[366] "ST9SV"        "update_stamp"


==================== UCSFFSX51.rda ====================
Object: UCSFFSX51
Dimensions: 4896 x 366
Number of columns: 366
Columns:
  [1] "ORIGPROT"     "COLPROT"      "RID"          "VISCODE"      "VISCODE2"
  [6] "EXAMDATE"     "VERSION"      "LONISID"      "LONIUID"      "IMAGEUID"
 [11] "IMAGETYPE"    "RUNDATE"      "STATUS"       "OVERALLQC"    "TEMPQC"
 [16] "FRONTQC"      "PARQC"        "INSULAQC"     "OCCQC"        "BGQC"
 [21] "CWMQC"        "VENTQC"       "LHIPQC"       "RHIPQC"       "ST101SV"
 [26] "ST102CV"      "ST102SA"      "ST102TA"      "ST102TS"      "ST103CV"
 [31] "ST103SA"      "ST103TA"      "ST103TS"      "ST104CV"      "ST104SA"
 [36] "ST104TA"      "ST104TS"      "ST105CV"      "ST105SA"      "ST105TA"
 [41] "ST105TS"      "ST106CV"      "ST106SA"      "ST106TA"      "ST106TS"
 [46] "ST107CV"      "ST107SA"      "ST107TA"      "ST107TS"      "ST108CV"
 [51] "ST108SA"      "ST108TA"      "ST108TS"      "ST109CV"      "ST109SA"
 [56] "ST109TA"      "ST109TS"      "ST10CV"       "ST110CV"      "ST110SA"
 [61] "ST110TA"      "ST110TS"      "ST111CV"      "ST111SA"      "ST111TA"
 [66] "ST111TS"      "ST112SV"      "ST113CV"      "ST113SA"      "ST113TA"
 [71] "ST113TS"      "ST114CV"      "ST114SA"      "ST114TA"      "ST114TS"
 [76] "ST115CV"      "ST115SA"      "ST115TA"      "ST115TS"      "ST116CV"
 [81] "ST116SA"      "ST116TA"      "ST116TS"      "ST117CV"      "ST117SA"
 [86] "ST117TA"      "ST117TS"      "ST118CV"      "ST118SA"      "ST118TA"
 [91] "ST118TS"      "ST119CV"      "ST119SA"      "ST119TA"      "ST119TS"
 [96] "ST11SV"       "ST120SV"      "ST121CV"      "ST121SA"      "ST121TA"
[101] "ST121TS"      "ST124SV"      "ST125SV"      "ST127SV"      "ST128SV"
[106] "ST129CV"      "ST129SA"      "ST129TA"      "ST129TS"      "ST12SV"
[111] "ST130CV"      "ST130SA"      "ST130TA"      "ST130TS"      "ST13CV"
[116] "ST13SA"       "ST13TA"       "ST13TS"       "ST14CV"       "ST14SA"
[121] "ST14TA"       "ST14TS"       "ST15CV"       "ST15SA"       "ST15TA"
[126] "ST15TS"       "ST16SV"       "ST17SV"       "ST18SV"       "ST1SV"
[131] "ST21SV"       "ST23CV"       "ST23SA"       "ST23TA"       "ST23TS"
[136] "ST24CV"       "ST24SA"       "ST24TA"       "ST24TS"       "ST25CV"
[141] "ST25SA"       "ST25TA"       "ST25TS"       "ST26CV"       "ST26SA"
[146] "ST26TA"       "ST26TS"       "ST28SA"       "ST29SV"       "ST2SV"
[151] "ST30SV"       "ST31CV"       "ST31SA"       "ST31TA"       "ST31TS"
[156] "ST32CV"       "ST32SA"       "ST32TA"       "ST32TS"       "ST34CV"
[161] "ST34SA"       "ST34TA"       "ST34TS"       "ST35CV"       "ST35SA"
[166] "ST35TA"       "ST35TS"       "ST36CV"       "ST36SA"       "ST36TA"
[171] "ST36TS"       "ST37SV"       "ST38CV"       "ST38SA"       "ST38TA"
[176] "ST38TS"       "ST39CV"       "ST39SA"       "ST39TA"       "ST39TS"
[181] "ST3SV"        "ST40CV"       "ST40SA"       "ST40TA"       "ST40TS"
[186] "ST42SV"       "ST43CV"       "ST43SA"       "ST43TA"       "ST43TS"
[191] "ST44CV"       "ST44SA"       "ST44TA"       "ST44TS"       "ST45CV"
[196] "ST45SA"       "ST45TA"       "ST45TS"       "ST46CV"       "ST46SA"
[201] "ST46TA"       "ST46TS"       "ST47CV"       "ST47SA"       "ST47TA"
[206] "ST47TS"       "ST48CV"       "ST48SA"       "ST48TA"       "ST48TS"
[211] "ST49CV"       "ST49SA"       "ST49TA"       "ST49TS"       "ST4SV"
[216] "ST50CV"       "ST50SA"       "ST50TA"       "ST50TS"       "ST51CV"
[221] "ST51SA"       "ST51TA"       "ST51TS"       "ST52CV"       "ST52SA"
[226] "ST52TA"       "ST52TS"       "ST53SV"       "ST54CV"       "ST54SA"
[231] "ST54TA"       "ST54TS"       "ST55CV"       "ST55SA"       "ST55TA"
[236] "ST55TS"       "ST56CV"       "ST56SA"       "ST56TA"       "ST56TS"
[241] "ST57CV"       "ST57SA"       "ST57TA"       "ST57TS"       "ST58CV"
[246] "ST58SA"       "ST58TA"       "ST58TS"       "ST59CV"       "ST59SA"
[251] "ST59TA"       "ST59TS"       "ST5SV"        "ST60CV"       "ST60SA"
[256] "ST60TA"       "ST60TS"       "ST61SV"       "ST62CV"       "ST62SA"
[261] "ST62TA"       "ST62TS"       "ST65SV"       "ST66SV"       "ST68SV"
[266] "ST69SV"       "ST6SV"        "ST70SV"       "ST71SV"       "ST72CV"
[271] "ST72SA"       "ST72TA"       "ST72TS"       "ST73CV"       "ST73SA"
[276] "ST73TA"       "ST73TS"       "ST74CV"       "ST74SA"       "ST74TA"
[281] "ST74TS"       "ST75SV"       "ST76SV"       "ST77SV"       "ST7SV"
[286] "ST80SV"       "ST82CV"       "ST82SA"       "ST82TA"       "ST82TS"
[291] "ST83CV"       "ST83SA"       "ST83TA"       "ST83TS"       "ST84CV"
[296] "ST84SA"       "ST84TA"       "ST84TS"       "ST85CV"       "ST85SA"
[301] "ST85TA"       "ST85TS"       "ST87SA"       "ST88SV"       "ST89SV"
[306] "ST8SV"        "ST90CV"       "ST90SA"       "ST90TA"       "ST90TS"
[311] "ST91CV"       "ST91SA"       "ST91TA"       "ST91TS"       "ST93CV"
[316] "ST93SA"       "ST93TA"       "ST93TS"       "ST94CV"       "ST94SA"
[321] "ST94TA"       "ST94TS"       "ST95CV"       "ST95SA"       "ST95TA"
[326] "ST95TS"       "ST96SV"       "ST97CV"       "ST97SA"       "ST97TA"
[331] "ST97TS"       "ST98CV"       "ST98SA"       "ST98TA"       "ST98TS"
[336] "ST99CV"       "ST99SA"       "ST99TA"       "ST99TS"       "ST9SV"
[341] "ST131HS"      "ST132HS"      "ST133HS"      "ST134HS"      "ST135HS"
[346] "ST136HS"      "ST137HS"      "ST138HS"      "ST139HS"      "ST140HS"
[351] "ST141HS"      "ST142HS"      "ST143HS"      "ST144HS"      "ST145HS"
[356] "ST146HS"      "ST147SV"      "ST148SV"      "ST149SV"      "ST150SV"
[361] "ST151SV"      "ST152SV"      "ST153SV"      "ST154SV"      "ST155SV"
[366] "update_stamp"


==================== UCSFFSX6.rda ====================
Object: UCSFFSX6
Dimensions: 2270 x 347
Number of columns: 347
Columns:
  [1] "ORIGPROT"     "COLPROT"      "PTID"         "RID"          "VISCODE"
  [6] "VISCODE2"     "IMAGEUID"     "EXAMDATE"     "RUNDATE"      "VERSION"
 [11] "STATUS"       "OVERALLQC"    "TEMPQC"       "FRONTQC"      "PARQC"
 [16] "INSULAQC"     "OCCQC"        "BGQC"         "CWMQC"        "VENTQC"
 [21] "HIPPOQC"      "ST101SV"      "ST102CV"      "ST102SA"      "ST102TA"
 [26] "ST102TS"      "ST103CV"      "ST103SA"      "ST103TA"      "ST103TS"
 [31] "ST104CV"      "ST104SA"      "ST104TA"      "ST104TS"      "ST105CV"
 [36] "ST105SA"      "ST105TA"      "ST105TS"      "ST106CV"      "ST106SA"
 [41] "ST106TA"      "ST106TS"      "ST107CV"      "ST107SA"      "ST107TA"
 [46] "ST107TS"      "ST108CV"      "ST108SA"      "ST108TA"      "ST108TS"
 [51] "ST109CV"      "ST109SA"      "ST109TA"      "ST109TS"      "ST10CV"
 [56] "ST110CV"      "ST110SA"      "ST110TA"      "ST110TS"      "ST111CV"
 [61] "ST111SA"      "ST111TA"      "ST111TS"      "ST112SV"      "ST113CV"
 [66] "ST113SA"      "ST113TA"      "ST113TS"      "ST114CV"      "ST114SA"
 [71] "ST114TA"      "ST114TS"      "ST115CV"      "ST115SA"      "ST115TA"
 [76] "ST115TS"      "ST116CV"      "ST116SA"      "ST116TA"      "ST116TS"
 [81] "ST117CV"      "ST117SA"      "ST117TA"      "ST117TS"      "ST118CV"
 [86] "ST118SA"      "ST118TA"      "ST118TS"      "ST119CV"      "ST119SA"
 [91] "ST119TA"      "ST119TS"      "ST11SV"       "ST120SV"      "ST121CV"
 [96] "ST121SA"      "ST121TA"      "ST121TS"      "ST124SV"      "ST125SV"
[101] "ST127SV"      "ST128SV"      "ST129CV"      "ST129SA"      "ST129TA"
[106] "ST129TS"      "ST12SV"       "ST130CV"      "ST130SA"      "ST130TA"
[111] "ST130TS"      "ST13CV"       "ST13SA"       "ST13TA"       "ST13TS"
[116] "ST14CV"       "ST14SA"       "ST14TA"       "ST14TS"       "ST15CV"
[121] "ST15SA"       "ST15TA"       "ST15TS"       "ST16SV"       "ST17SV"
[126] "ST18SV"       "ST1SV"        "ST21SV"       "ST23CV"       "ST23SA"
[131] "ST23TA"       "ST23TS"       "ST24CV"       "ST24SA"       "ST24TA"
[136] "ST24TS"       "ST25CV"       "ST25SA"       "ST25TA"       "ST25TS"
[141] "ST26CV"       "ST26SA"       "ST26TA"       "ST26TS"       "ST28SA"
[146] "ST29SV"       "ST2SV"        "ST30SV"       "ST31CV"       "ST31SA"
[151] "ST31TA"       "ST31TS"       "ST32CV"       "ST32SA"       "ST32TA"
[156] "ST32TS"       "ST34CV"       "ST34SA"       "ST34TA"       "ST34TS"
[161] "ST35CV"       "ST35SA"       "ST35TA"       "ST35TS"       "ST36CV"
[166] "ST36SA"       "ST36TA"       "ST36TS"       "ST37SV"       "ST38CV"
[171] "ST38SA"       "ST38TA"       "ST38TS"       "ST39CV"       "ST39SA"
[176] "ST39TA"       "ST39TS"       "ST3SV"        "ST40CV"       "ST40SA"
[181] "ST40TA"       "ST40TS"       "ST42SV"       "ST43CV"       "ST43SA"
[186] "ST43TA"       "ST43TS"       "ST44CV"       "ST44SA"       "ST44TA"
[191] "ST44TS"       "ST45CV"       "ST45SA"       "ST45TA"       "ST45TS"
[196] "ST46CV"       "ST46SA"       "ST46TA"       "ST46TS"       "ST47CV"
[201] "ST47SA"       "ST47TA"       "ST47TS"       "ST48CV"       "ST48SA"
[206] "ST48TA"       "ST48TS"       "ST49CV"       "ST49SA"       "ST49TA"
[211] "ST49TS"       "ST4SV"        "ST50CV"       "ST50SA"       "ST50TA"
[216] "ST50TS"       "ST51CV"       "ST51SA"       "ST51TA"       "ST51TS"
[221] "ST52CV"       "ST52SA"       "ST52TA"       "ST52TS"       "ST53SV"
[226] "ST54CV"       "ST54SA"       "ST54TA"       "ST54TS"       "ST55CV"
[231] "ST55SA"       "ST55TA"       "ST55TS"       "ST56CV"       "ST56SA"
[236] "ST56TA"       "ST56TS"       "ST57CV"       "ST57SA"       "ST57TA"
[241] "ST57TS"       "ST58CV"       "ST58SA"       "ST58TA"       "ST58TS"
[246] "ST59CV"       "ST59SA"       "ST59TA"       "ST59TS"       "ST5SV"
[251] "ST60CV"       "ST60SA"       "ST60TA"       "ST60TS"       "ST61SV"
[256] "ST62CV"       "ST62SA"       "ST62TA"       "ST62TS"       "ST65SV"
[261] "ST66SV"       "ST68SV"       "ST69SV"       "ST6SV"        "ST70SV"
[266] "ST71SV"       "ST72CV"       "ST72SA"       "ST72TA"       "ST72TS"
[271] "ST73CV"       "ST73SA"       "ST73TA"       "ST73TS"       "ST74CV"
[276] "ST74SA"       "ST74TA"       "ST74TS"       "ST75SV"       "ST76SV"
[281] "ST77SV"       "ST7SV"        "ST80SV"       "ST82CV"       "ST82SA"
[286] "ST82TA"       "ST82TS"       "ST83CV"       "ST83SA"       "ST83TA"
[291] "ST83TS"       "ST84CV"       "ST84SA"       "ST84TA"       "ST84TS"
[296] "ST85CV"       "ST85SA"       "ST85TA"       "ST85TS"       "ST87sa"
[301] "ST88SV"       "ST89SV"       "ST8SV"        "ST90CV"       "ST90SA"
[306] "ST90TA"       "ST90TS"       "ST91CV"       "ST91SA"       "ST91TA"
[311] "ST91TS"       "ST93CV"       "ST93SA"       "ST93TA"       "ST93TS"
[316] "ST94CV"       "ST94SA"       "ST94TA"       "ST94TS"       "ST95CV"
[321] "ST95SA"       "ST95TA"       "ST95TS"       "ST96SV"       "ST97CV"
[326] "ST97SA"       "ST97TA"       "ST97TS"       "ST98CV"       "ST98SA"
[331] "ST98TA"       "ST98TS"       "ST99CV"       "ST99SA"       "ST99TA"
[336] "ST99TS"       "ST9SV"        "ST147SV"      "ST148SV"      "ST149SV"
[341] "ST150SV"      "ST151SV"      "ST152SV"      "ST153SV"      "ST154SV"
[346] "ST155SV"      "update_stamp"


==================== UCSFFSX7.rda ====================
Object: UCSFFSX7
Dimensions: 12151 x 348
Number of columns: 348
Columns:
  [1] "ORIGPROT"       "COLPROT"        "PTID"           "RID"
  [5] "VISCODE"        "VISCODE2"       "IMAGEUID"       "FIELD_STRENGTH"
  [9] "EXAMDATE"       "RUNDATE"        "STATUS"         "FSVER"
 [13] "OVERALLQC"      "TEMPQC"         "FRONTQC"        "PARQC"
 [17] "INSULAQC"       "OCCQC"          "BGQC"           "CWMQC"
 [21] "VENTQC"         "HIPPOQC"        "ST101SV"        "ST102CV"
 [25] "ST102SA"        "ST102TA"        "ST102TS"        "ST103CV"
 [29] "ST103SA"        "ST103TA"        "ST103TS"        "ST104CV"
 [33] "ST104SA"        "ST104TA"        "ST104TS"        "ST105CV"
 [37] "ST105SA"        "ST105TA"        "ST105TS"        "ST106CV"
 [41] "ST106SA"        "ST106TA"        "ST106TS"        "ST107CV"
 [45] "ST107SA"        "ST107TA"        "ST107TS"        "ST108CV"
 [49] "ST108SA"        "ST108TA"        "ST108TS"        "ST109CV"
 [53] "ST109SA"        "ST109TA"        "ST109TS"        "ST10CV"
 [57] "ST110CV"        "ST110SA"        "ST110TA"        "ST110TS"
 [61] "ST111CV"        "ST111SA"        "ST111TA"        "ST111TS"
 [65] "ST112SV"        "ST113CV"        "ST113SA"        "ST113TA"
 [69] "ST113TS"        "ST114CV"        "ST114SA"        "ST114TA"
 [73] "ST114TS"        "ST115CV"        "ST115SA"        "ST115TA"
 [77] "ST115TS"        "ST116CV"        "ST116SA"        "ST116TA"
 [81] "ST116TS"        "ST117CV"        "ST117SA"        "ST117TA"
 [85] "ST117TS"        "ST118CV"        "ST118SA"        "ST118TA"
 [89] "ST118TS"        "ST119CV"        "ST119SA"        "ST119TA"
 [93] "ST119TS"        "ST11SV"         "ST120SV"        "ST121CV"
 [97] "ST121SA"        "ST121TA"        "ST121TS"        "ST124SV"
[101] "ST125SV"        "ST127SV"        "ST128SV"        "ST129CV"
[105] "ST129SA"        "ST129TA"        "ST129TS"        "ST12SV"
[109] "ST130CV"        "ST130SA"        "ST130TA"        "ST130TS"
[113] "ST13CV"         "ST13SA"         "ST13TA"         "ST13TS"
[117] "ST14CV"         "ST14SA"         "ST14TA"         "ST14TS"
[121] "ST15CV"         "ST15SA"         "ST15TA"         "ST15TS"
[125] "ST16SV"         "ST17SV"         "ST18SV"         "ST1SV"
[129] "ST21SV"         "ST23CV"         "ST23SA"         "ST23TA"
[133] "ST23TS"         "ST24CV"         "ST24SA"         "ST24TA"
[137] "ST24TS"         "ST25CV"         "ST25SA"         "ST25TA"
[141] "ST25TS"         "ST26CV"         "ST26SA"         "ST26TA"
[145] "ST26TS"         "ST28SA"         "ST29SV"         "ST2SV"
[149] "ST30SV"         "ST31CV"         "ST31SA"         "ST31TA"
[153] "ST31TS"         "ST32CV"         "ST32SA"         "ST32TA"
[157] "ST32TS"         "ST34CV"         "ST34SA"         "ST34TA"
[161] "ST34TS"         "ST35CV"         "ST35SA"         "ST35TA"
[165] "ST35TS"         "ST36CV"         "ST36SA"         "ST36TA"
[169] "ST36TS"         "ST37SV"         "ST38CV"         "ST38SA"
[173] "ST38TA"         "ST38TS"         "ST39CV"         "ST39SA"
[177] "ST39TA"         "ST39TS"         "ST3SV"          "ST40CV"
[181] "ST40SA"         "ST40TA"         "ST40TS"         "ST42SV"
[185] "ST43CV"         "ST43SA"         "ST43TA"         "ST43TS"
[189] "ST44CV"         "ST44SA"         "ST44TA"         "ST44TS"

In [95]:
# Search ADNIMERGE2 documentation for MRI variable definitions

from pathlib import Path

package_dir = Path(
    "../Data/ADNIMERGE2/ADNIMERGE2"
).resolve()

search_terms = [
    "ST101",
    "hippocampus",
    "Hippocampus",
    "ventricle"
]

extensions = {".Rmd", ".R", ".Rd", ".txt"}

for term in search_terms:

    print("\n" + "=" * 70)
    print("SEARCH TERM:", term)
    print("=" * 70)

    found = 0

    for file in package_dir.rglob("*"):

        if not file.is_file() or file.suffix not in extensions:
            continue

        try:
            text = file.read_text(
                encoding="utf-8",
                errors="ignore"
            )
        except Exception:
            continue

        for line_number, line in enumerate(text.splitlines(), start=1):

            if term.lower() in line.lower():

                print(
                    f"{file.name} | line {line_number} | "
                    f"{line.strip()[:250]}"
                )

                found += 1

                if found >= 20:
                    break

        if found >= 20:
            break

    print("Matches shown:", found)

======================================================================
SEARCH TERM: ST101
======================================================================
UCSFASLFSCBF.Rd | line 40 | \item \strong{FSBGQC} \emph{character} QC rating of the basal ganglia. Fail affects the following regions: LeftPutamen (ST53); RightPutamen (ST112); LeftCaudate (ST16); RightCaudate (ST75); LeftPallidum (ST42); RightPallidum (ST101) , with options: P
UCSFASLFSCBF.Rd | line 343 | \item \strong{ST101MIN} \emph{numeric} Min CBF value for FreeSurfer ROI: Right-Pallidum Range value: -1722.89, ..., 1128.2
UCSFASLFSCBF.Rd | line 344 | \item \strong{ST101MAX} \emph{numeric} Max CBF value for FreeSurfer ROI: Right-Pallidum Range value: 1.7482e-05, ..., 7321.6
UCSFASLFSCBF.Rd | line 345 | \item \strong{ST101AVG} \emph{numeric} Mean CBF value for FreeSurfer ROI: Right-Pallidum Range value: -242.21, ..., 2685.41
UCSFASLFSCBF.Rd | line 346 | \item \strong{ST101SD} \emph{numeric} Standard Deviation of Mean CBF value for FreeSurfer ROI: Right-Pallidum Range value: 0.000181311, ..., 1710.97
UCSFASLFSCBF.Rd | line 347 | \item \strong{ST101CT} \emph{numeric} Count of CBF voxels in FreeSurfer ROI: Right-Pallidum Range value: 30, ..., 2947
UCSFASLFS_V2.Rd | line 554 | \item \strong{ST101MIN} \emph{numeric} Min CBF value for FreeSurfer ROI: Right-Pallidum Range value: 1, ..., 4482
UCSFASLFS_V2.Rd | line 555 | \item \strong{ST101MAX} \emph{numeric} Max CBF value for FreeSurfer ROI: Right-Pallidum Range value: 84890, ..., 754596
UCSFASLFS_V2.Rd | line 556 | \item \strong{ST101MD} \emph{numeric} Median CBF value for FreeSurfer ROI: Right-Pallidum Range value: 7, ..., 431556
UCSFASLFS_V2.Rd | line 557 | \item \strong{ST101AVG} \emph{numeric} Mean CBF value for FreeSurfer ROI: Right-Pallidum Range value: 1804.43, ..., 361694
UCSFASLFS_V2.Rd | line 558 | \item \strong{ST101SD} \emph{numeric} Standard Deviation of Mean CBF value for FreeSurfer ROI: Right-Pallidum Range value: 9834.2, ..., 226361
UCSFASLFS_V2.Rd | line 559 | \item \strong{ST101CT} \emph{numeric} Count of CBF voxels in FreeSurfer ROI: Right-Pallidum Range value: 155, ..., 1208
UCSFFSL.Rd | line 47 | \item \strong{BGQC} \emph{character} QC rating of the basal ganglia. Fail affects the following regions: LeftPutamen (ST53); RightPutamen (ST112); LeftCaudate (ST16); RightCaudate (ST75); LeftPallidum (ST42); RightPallidum (ST101) Pass/Fail
UCSFFSL.Rd | line 51 | \item \strong{ST101SV} \emph{numeric} Volume (WM Parcellation) of RightPallidum Range value: 309, ..., 2317
UCSFFSL51.Rd | line 39 | \item \strong{BGQC} \emph{character} QC rating of the basal ganglia. Fail affects the following regions: LeftPutamen (ST53); RightPutamen (ST112); LeftCaudate (ST16); RightCaudate (ST75); LeftPallidum (ST42); RightPallidum (ST101) Pass/Fail
UCSFFSL51.Rd | line 274 | \item \strong{ST101SV} \emph{numeric} Subcortical Volume (aseg.stats) of RightPallidum Range value: 831, ..., 2201
UCSFFSL51ALL.Rd | line 39 | \item \strong{BGQC} \emph{character} QC rating of the basal ganglia. Fail affects the following regions: LeftPutamen (ST53); RightPutamen (ST112); LeftCaudate (ST16); RightCaudate (ST75); LeftPallidum (ST42); RightPallidum (ST101) Pass/Fail
UCSFFSL51ALL.Rd | line 274 | \item \strong{ST101SV} \emph{numeric} Subcortical Volume (aseg.stats) of RightPallidum Range value: 831, ..., 2225
UCSFFSL51Y1.Rd | line 39 | \item \strong{BGQC} \emph{character} QC rating of the basal ganglia. Fail affects the following regions: LeftPutamen (ST53); RightPutamen (ST112); LeftCaudate (ST16); RightCaudate (ST75); LeftPallidum (ST42); RightPallidum (ST101) Pass/Fail
UCSFFSL51Y1.Rd | line 274 | \item \strong{ST101SV} \emph{numeric} Subcortical Volume (aseg.stats) of RightPallidum Range value: 785, ..., 2092
Matches shown: 20

======================================================================
SEARCH TERM: hippocampus
======================================================================
BAINMRC.Rd | line 26 | \item \strong{HIPPL01} \emph{numeric} Globally normalized CMRgl from Hippocampus_L Range value: 0.845947, ..., 1.57295
BAINMRC.Rd | line 48 | \item \strong{HIPPR01} \emph{logical} Globally normalized CMRgl from Hippocampus_R A Boolean value: TRUE/ FALSE
BAINMRC.Rd | line 271 | \item \strong{HIPPL06} \emph{logical} Hippocampus_L A Boolean value: TRUE/ FALSE
BAINMRC.Rd | line 272 | \item \strong{HIPPR06} \emph{numeric} Hippocampus_R Range value: 1.01451, ..., 1.59095
BAINMRC.Rd | line 314 | \item \strong{NL1HIPP} \emph{numeric} difference of globally normalized CMRgl from Baseline to 12 months and 12 months to 24 months from Hippocampus for 58 AD patients Range value: -0.149295, ..., 0.201397
BAIPETNMRC.Rd | line 31 | \item \strong{HIPPL01} \emph{numeric} Globally normalized CMRgl from Hippocampus_L Range value: 0.845947, ..., 1.57295
BAIPETNMRC.Rd | line 53 | \item \strong{HIPPR01} \emph{numeric} Globally normalized CMRgl from Hippocampus_R Range value: Inf, ..., -Inf
BAIPETNMRC.Rd | line 276 | \item \strong{HIPPL06} \emph{numeric} Hippocampus_L Range value: Inf, ..., -Inf
BAIPETNMRC.Rd | line 277 | \item \strong{HIPPR06} \emph{numeric} Hippocampus_R Range value: 1.01451, ..., 1.59095
BAIPETNMRC.Rd | line 318 | \item \strong{NL1HIPP} \emph{numeric} difference of globally normalized CMRgl from Baseline to 12 months and 12 months to 24 months from Hippocampus for 58 AD patients Range value: -0.149295, ..., 0.201397
DTIROI_V1.Rd | line 59 | \item \strong{AD_CGH_L} \emph{numeric} Cingulum (hippocampus) left Range value: 0.000940835, ..., 0.00171008
DTIROI_V1.Rd | line 60 | \item \strong{AD_CGH_R} \emph{numeric} Cingulum (hippocampus) right Range value: 0.000964048, ..., 0.00169439
DTIROI_V1.Rd | line 116 | \item \strong{FA_CGH_L} \emph{numeric} Cingulum (hippocampus) left Range value: 0.141236, ..., 0.314793
DTIROI_V1.Rd | line 117 | \item \strong{FA_CGH_R} \emph{numeric} Cingulum (hippocampus) right Range value: 0.161659, ..., 0.362394
DTIROI_V1.Rd | line 173 | \item \strong{MD_CGH_L} \emph{numeric} Cingulum (hippocampus) left Range value: 0.000741311, ..., 0.00148218
DTIROI_V1.Rd | line 174 | \item \strong{MD_CGH_R} \emph{numeric} Cingulum (hippocampus) right Range value: 0.000752325, ..., 0.0014515
DTIROI_V1.Rd | line 230 | \item \strong{RD_CGH_L} \emph{numeric} Cingulum (hippocampus) left Range value: 0.00063963, ..., 0.00136824
DTIROI_V1.Rd | line 231 | \item \strong{RD_CGH_R} \emph{numeric} Cingulum (hippocampus) right Range value: 0.000625422, ..., 0.00133005
NEUROPATH.Rd | line 38 | \item \strong{NPGRHA} \emph{numeric} c3. Hippocampus atrophy 0=0 None ; 1=1 Mild ; 2=2 Moderate ; 3=3 Severe ; 8=8 Not assessed ; 9=9 Missing/unknown
NEUROPATH.Rd | line 114 | \item \strong{NPTDPC} \emph{numeric} c. Hippocampus 0=0 No ; 1=1 Yes ; 8=8 Not assessed ; 9=9 Missing/unknown
Matches shown: 20

======================================================================
SEARCH TERM: Hippocampus
======================================================================
BAINMRC.Rd | line 26 | \item \strong{HIPPL01} \emph{numeric} Globally normalized CMRgl from Hippocampus_L Range value: 0.845947, ..., 1.57295
BAINMRC.Rd | line 48 | \item \strong{HIPPR01} \emph{logical} Globally normalized CMRgl from Hippocampus_R A Boolean value: TRUE/ FALSE
BAINMRC.Rd | line 271 | \item \strong{HIPPL06} \emph{logical} Hippocampus_L A Boolean value: TRUE/ FALSE
BAINMRC.Rd | line 272 | \item \strong{HIPPR06} \emph{numeric} Hippocampus_R Range value: 1.01451, ..., 1.59095
BAINMRC.Rd | line 314 | \item \strong{NL1HIPP} \emph{numeric} difference of globally normalized CMRgl from Baseline to 12 months and 12 months to 24 months from Hippocampus for 58 AD patients Range value: -0.149295, ..., 0.201397
BAIPETNMRC.Rd | line 31 | \item \strong{HIPPL01} \emph{numeric} Globally normalized CMRgl from Hippocampus_L Range value: 0.845947, ..., 1.57295
BAIPETNMRC.Rd | line 53 | \item \strong{HIPPR01} \emph{numeric} Globally normalized CMRgl from Hippocampus_R Range value: Inf, ..., -Inf
BAIPETNMRC.Rd | line 276 | \item \strong{HIPPL06} \emph{numeric} Hippocampus_L Range value: Inf, ..., -Inf
BAIPETNMRC.Rd | line 277 | \item \strong{HIPPR06} \emph{numeric} Hippocampus_R Range value: 1.01451, ..., 1.59095
BAIPETNMRC.Rd | line 318 | \item \strong{NL1HIPP} \emph{numeric} difference of globally normalized CMRgl from Baseline to 12 months and 12 months to 24 months from Hippocampus for 58 AD patients Range value: -0.149295, ..., 0.201397
DTIROI_V1.Rd | line 59 | \item \strong{AD_CGH_L} \emph{numeric} Cingulum (hippocampus) left Range value: 0.000940835, ..., 0.00171008
DTIROI_V1.Rd | line 60 | \item \strong{AD_CGH_R} \emph{numeric} Cingulum (hippocampus) right Range value: 0.000964048, ..., 0.00169439
DTIROI_V1.Rd | line 116 | \item \strong{FA_CGH_L} \emph{numeric} Cingulum (hippocampus) left Range value: 0.141236, ..., 0.314793
DTIROI_V1.Rd | line 117 | \item \strong{FA_CGH_R} \emph{numeric} Cingulum (hippocampus) right Range value: 0.161659, ..., 0.362394
DTIROI_V1.Rd | line 173 | \item \strong{MD_CGH_L} \emph{numeric} Cingulum (hippocampus) left Range value: 0.000741311, ..., 0.00148218
DTIROI_V1.Rd | line 174 | \item \strong{MD_CGH_R} \emph{numeric} Cingulum (hippocampus) right Range value: 0.000752325, ..., 0.0014515
DTIROI_V1.Rd | line 230 | \item \strong{RD_CGH_L} \emph{numeric} Cingulum (hippocampus) left Range value: 0.00063963, ..., 0.00136824
DTIROI_V1.Rd | line 231 | \item \strong{RD_CGH_R} \emph{numeric} Cingulum (hippocampus) right Range value: 0.000625422, ..., 0.00133005
NEUROPATH.Rd | line 38 | \item \strong{NPGRHA} \emph{numeric} c3. Hippocampus atrophy 0=0 None ; 1=1 Mild ; 2=2 Moderate ; 3=3 Severe ; 8=8 Not assessed ; 9=9 Missing/unknown
NEUROPATH.Rd | line 114 | \item \strong{NPTDPC} \emph{numeric} c. Hippocampus 0=0 No ; 1=1 Yes ; 8=8 Not assessed ; 9=9 Missing/unknown
Matches shown: 20

======================================================================
SEARCH TERM: ventricle
======================================================================
UCBERKELEY_AMY_6MM.Rd | line 61 | \item \strong{VENTRICLE_3RD_SUVR} \emph{numeric} 3rd-ventricle Range value: 0.356, ..., 1.213
UCBERKELEY_AMY_6MM.Rd | line 62 | \item \strong{VENTRICLE_3RD_VOLUME} \emph{numeric} 3rd-ventricle ROI size in mm^3 Range value: 474, ..., 5244
UCBERKELEY_AMY_6MM.Rd | line 63 | \item \strong{VENTRICLE_4TH_SUVR} \emph{numeric} 4th-ventricle Range value: 0.541, ..., 1.299
UCBERKELEY_AMY_6MM.Rd | line 64 | \item \strong{VENTRICLE_4TH_VOLUME} \emph{numeric} 4th-ventricle ROI size in mm^3 Range value: 561, ..., 5586
UCBERKELEY_AMY_6MM.Rd | line 65 | \item \strong{VENTRICLE_5TH_SUVR} \emph{numeric} 5th-ventricle Range value: 0.422, ..., 1.414
UCBERKELEY_AMY_6MM.Rd | line 66 | \item \strong{VENTRICLE_5TH_VOLUME} \emph{numeric} 5th-ventricle ROI size in mm^3 Range value: 1, ..., 11
UCBERKELEY_AMY_6MM.Rd | line 157 | \item \strong{LATERAL_VENTRICLE_SUVR} \emph{numeric} bilateral-lateral-ventricle Range value: 0.284, ..., 1.441
UCBERKELEY_AMY_6MM.Rd | line 158 | \item \strong{LATERAL_VENTRICLE_VOLUME} \emph{numeric} bilateral-lateral-ventricle ROI size in mm^3 Range value: 5800, ..., 146015
UCBERKELEY_AMY_6MM.Rd | line 323 | \item \strong{LEFT_LATERAL_VENTRICLE_SUVR} \emph{numeric} left-lateral-ventricle Range value: 0.273, ..., 1.457
UCBERKELEY_AMY_6MM.Rd | line 324 | \item \strong{LEFT_LATERAL_VENTRICLE_VOLUME} \emph{numeric} left-lateral-ventricle ROI size in mm^3 Range value: 3016, ..., 82443
UCBERKELEY_AMY_6MM.Rd | line 353 | \item \strong{RIGHT_LATERAL_VENTRICLE_SUVR} \emph{numeric} right-lateral-ventricle Range value: 0.263, ..., 1.456
UCBERKELEY_AMY_6MM.Rd | line 354 | \item \strong{RIGHT_LATERAL_VENTRICLE_VOLUME} \emph{numeric} right-lateral-ventricle ROI size in mm^3 Range value: 2442, ..., 71992
UCBERKELEY_TAUPVC_6MM.Rd | line 54 | \item \strong{VENTRICLE_3RD_SUVR} \emph{numeric} 3rd-ventricle Range value: 0.002, ..., 0.844
UCBERKELEY_TAUPVC_6MM.Rd | line 55 | \item \strong{VENTRICLE_3RD_VOLUME} \emph{numeric} 3rd-ventricle ROI size in mm^3 Range value: 484, ..., 5244
UCBERKELEY_TAUPVC_6MM.Rd | line 56 | \item \strong{VENTRICLE_4TH_SUVR} \emph{numeric} 4th-ventricle Range value: 0.001, ..., 0.855
UCBERKELEY_TAUPVC_6MM.Rd | line 57 | \item \strong{VENTRICLE_4TH_VOLUME} \emph{numeric} 4th-ventricle ROI size in mm^3 Range value: 739, ..., 5081
UCBERKELEY_TAUPVC_6MM.Rd | line 58 | \item \strong{VENTRICLE_5TH_SUVR} \emph{numeric} 5th-ventricle Range value: 0.185, ..., 0.655
UCBERKELEY_TAUPVC_6MM.Rd | line 59 | \item \strong{VENTRICLE_5TH_VOLUME} \emph{numeric} 5th-ventricle ROI size in mm^3 Range value: 1, ..., 11
UCBERKELEY_TAUPVC_6MM.Rd | line 148 | \item \strong{LATERAL_VENTRICLE_SUVR} \emph{numeric} bilateral-lateral-ventricle Range value: 0.005, ..., 1.263
UCBERKELEY_TAUPVC_6MM.Rd | line 149 | \item \strong{LATERAL_VENTRICLE_VOLUME} \emph{numeric} bilateral-lateral-ventricle ROI size in mm^3 Range value: 5800, ..., 138561
Matches shown: 20

In [96]:
from pathlib import Path

# Find UCSFFSX7.rda anywhere inside the ADNIMERGE2 folder
base = Path("../Data/ADNIMERGE2").resolve()

matches = list(base.rglob("UCSFFSX7.rda"))

print("Found:", len(matches))

for p in matches:
    print(p)

Found: 1
C:\Users\anura\Desktop\MCI_AD_XAI_Project\Data\ADNIMERGE2\ADNIMERGE2\data\UCSFFSX7.rda

In [97]:
import subprocess
from pathlib import Path

r_file = Path(
    r"C:\Users\anura\Desktop\MCI_AD_XAI_Project\Data\ADNIMERGE2\ADNIMERGE2\data\UCSFFSX7.rda"
)

output_file = Path(
    r"C:\Users\anura\Desktop\MCI_AD_XAI_Project\Data\UCSFFSX7_from_R.csv"
)

r_script = f'''
load("{r_file.as_posix()}")
obj <- get("UCSFFSX7")
write.csv(obj, "{output_file.as_posix()}", row.names=FALSE)
'''

script_file = Path("../Data/export_ucsfsx7.R").resolve()
script_file.write_text(r_script, encoding="utf-8")

rscript = r"C:\Users\anura\.conda\envs\mci_ad_xai\Scripts\Rscript.exe"

result = subprocess.run(
    [rscript, str(script_file)],
    capture_output=True,
    text=True
)

print("Return code:", result.returncode)

if result.stdout:
    print("\nR output:")
    print(result.stdout)

if result.stderr:
    print("\nR messages/errors:")
    print(result.stderr)

print("\nCSV created:", output_file.exists())
print("Location:", output_file)

Return code: 0

CSV created: True
Location: C:\Users\anura\Desktop\MCI_AD_XAI_Project\Data\UCSFFSX7_from_R.csv

In [98]:
import pandas as pd

mri = pd.read_csv("../Data/UCSFFSX7_from_R.csv")

print("Shape:", mri.shape)

print("\nFirst 30 columns:")
for col in mri.columns[:30]:
    print(col)

print("\nPotential hippocampus/temporal variables:")
keywords = ["hipp", "entorh", "temporal", "amyg", "parahipp"]

for col in mri.columns:
    if any(k in col.lower() for k in keywords):
        print(col)

Shape: (12151, 348)

First 30 columns:
ORIGPROT
COLPROT
PTID
RID
VISCODE
VISCODE2
IMAGEUID
FIELD_STRENGTH
EXAMDATE
RUNDATE
STATUS
FSVER
OVERALLQC
TEMPQC
FRONTQC
PARQC
INSULAQC
OCCQC
BGQC
CWMQC
VENTQC
HIPPOQC
ST101SV
ST102CV
ST102SA
ST102TA
ST102TS
ST103CV
ST103SA
ST103TA

Potential hippocampus/temporal variables:
HIPPOQC

C:\Users\anura\AppData\Local\Temp\ipykernel_10748\1969087491.py:3: DtypeWarning: Columns (0: OVERALLQC, 1: TEMPQC, 2: FRONTQC, 3: PARQC, 4: INSULAQC, 5: OCCQC, 6: BGQC, 7: CWMQC, 8: VENTQC, 9: HIPPOQC) have mixed types. Specify dtype option on import or set low_memory=False.
  mri = pd.read_csv("../Data/UCSFFSX7_from_R.csv")

In [99]:
from pathlib import Path

package_dir = Path(
    r"C:\Users\anura\Desktop\MCI_AD_XAI_Project\Data\ADNIMERGE2\ADNIMERGE2"
)

term = "HIPPOQC"

print("Searching documentation for:", term)
print("=" * 70)

found = 0

for file in package_dir.rglob("*"):
    if not file.is_file() or file.suffix not in {".Rd", ".Rmd", ".R", ".txt"}:
        continue

    try:
        text = file.read_text(encoding="utf-8", errors="ignore")
    except Exception:
        continue

    for line_number, line in enumerate(text.splitlines(), start=1):
        if term.lower() in line.lower():
            print(f"\n{file.name} | line {line_number}")
            print(line.strip())

            found += 1

            if found >= 30:
                break

    if found >= 30:
        break

print("\nMatches shown:", found)

Searching documentation for: HIPPOQC
======================================================================

UCSFFSX6.Rd | line 41
\item \strong{HIPPOQC} \emph{character} QC rating of the hippocampus. Fail affects the following regions: LeftFusiform (ST26); RightFusiform (ST85); LeftEntorhinal (ST24); RightEntorhinal (ST83); LeftParahippocampal (ST44); RightParahippocampal (ST103); LeftAmygdala (ST12); RightAmygdala (ST71) , with options: Pass, Fail

UCSFFSX7.Rd | line 42
\item \strong{HIPPOQC} \emph{character} QC rating of the hippocampus. Fail affects the following regions: LeftFusiform (ST26); RightFusiform (ST85); LeftEntorhinal (ST24); RightEntorhinal (ST83); LeftParahippocampal (ST44); RightParahippocampal (ST103); LeftAmygdala (ST12); RightAmygdala (ST71) , with options: Pass, Fail

data.R | line 19335
#' \item \strong{HIPPOQC} \emph{character} QC rating of the hippocampus. Fail affects the following regions: LeftFusiform (ST26); RightFusiform (ST85); LeftEntorhinal (ST24); RightEntorhinal (ST83); LeftParahippocampal (ST44); RightParahippocampal (ST103); LeftAmygdala (ST12); RightAmygdala (ST71) , with options: Pass, Fail

data.R | line 19699
#' \item \strong{HIPPOQC} \emph{character} QC rating of the hippocampus. Fail affects the following regions: LeftFusiform (ST26); RightFusiform (ST85); LeftEntorhinal (ST24); RightEntorhinal (ST83); LeftParahippocampal (ST44); RightParahippocampal (ST103); LeftAmygdala (ST12); RightAmygdala (ST71) , with options: Pass, Fail

Matches shown: 4

In [100]:
from pathlib import Path

package_dir = Path(
    r"C:\Users\anura\Desktop\MCI_AD_XAI_Project\Data\ADNIMERGE2\ADNIMERGE2"
)

print("Searching UCSFFSX7 documentation for hippocampus-related ST variables")
print("=" * 80)

rd_file = package_dir / "man" / "UCSFFSX7.Rd"

if rd_file.exists():
    lines = rd_file.read_text(
        encoding="utf-8",
        errors="ignore"
    ).splitlines()

    for i, line in enumerate(lines):
        if "Hippocamp" in line or "hippocamp" in line:
            start = max(0, i - 2)
            end = min(len(lines), i + 3)

            print(f"\n--- Around line {i + 1} ---")
            for j in range(start, end):
                print(f"{j + 1}: {lines[j]}")
else:
    print("UCSFFSX7.Rd not found at:")
    print(rd_file)

Searching UCSFFSX7 documentation for hippocampus-related ST variables
================================================================================

--- Around line 33 ---
31: \item \strong{STATUS} \emph{character} partial = No QC, not final. Complete = QC and finalized. , with options: partial, complete
32: \item \strong{FSVER} \emph{character} Specific version of FreeSurfer used. All FS 7.x results are compatible. , with options: 7.2.0, 7.4.1
33: \item \strong{OVERALLQC} \emph{character} An overall quality rating. Refer to additional QC variables for Partial rating. , with options: Partial, Pass, Hippocampus Only, Fail
34: \item \strong{TEMPQC} \emph{character} QC rating of temporal lobe. Fail affects the following regions: LeftTemporalPole (ST60); RightTemporalPole (ST119); LeftFusiform (ST26); RightFusiform (ST85); LeftSuperiorTemporal (ST58); RightSuperiorTemporal (ST117); LeftInferiorTemporal (ST32); RightInferiorTemporal (ST91); LeftMiddleTemporal (ST40); RightMiddleTemporal (ST99) , with options: Fail, Pass
35: \item \strong{FRONTQC} \emph{character} QC rating of the frontal lobe. Fail affects the following regions: LeftFrontalPole (ST25); RightFrontalPole (ST84); LeftPrecentral (ST51); RightPrecentral (ST110); LeftSuperiorFrontal (ST56); RightSuperiorFrontal (ST115); LeftCaudalMiddleFrontal (ST15); RightCaudalMiddleFrontal (ST74); LeftRostralMiddleFrontal (ST55); RightRostralMiddleFrontal (ST114); LeftMedialOrbitofrontal (ST39); RightMedialOrbitofrontal (ST98) , with options: Pass, Fail

--- Around line 42 ---
40: \item \strong{CWMQC} \emph{character} QC rating of the cerebral WM. Fail affects the following regions: LeftCerebralWM (ST20); RightCerebralWM (ST79); LeftCorticalWM (ST150); RightCorticalWM (ST151); CorticalWM (ST152); LeftHemisphereWM (ST28); RightHemisphereWM (ST87) , with options: Pass, Fail
41: \item \strong{VENTQC} \emph{character} QC rating of the ventricles. Fail affects the following regions: LeftLateralVentricle (ST37); RightLateralVentricle (ST96); LeftInferiorLateralVentricle (ST30); RightInferiorLateralVentricle (ST89); ThirdVentricle (ST127); FourthVentricle (ST9); FifthVentrical (ST8); LeftChoroidPlexus (ST21); RightChoroidPlexus (ST80) , with options: Pass, Fail
42: \item \strong{HIPPOQC} \emph{character} QC rating of the hippocampus. Fail affects the following regions: LeftFusiform (ST26); RightFusiform (ST85); LeftEntorhinal (ST24); RightEntorhinal (ST83); LeftParahippocampal (ST44); RightParahippocampal (ST103); LeftAmygdala (ST12); RightAmygdala (ST71) , with options: Pass, Fail
43: \item \strong{ST101SV} \emph{numeric} Subcortical Volume (aseg.stats) of RightPallidum Range value: 881.8, ..., 3097.5
44: \item \strong{ST102CV} \emph{numeric} Cortical Volume (aparc.stats) of RightParacentral Range value: 1589, ..., 9285

--- Around line 48 ---
46: \item \strong{ST102TA} \emph{numeric} Thickness Average (aparc.stats) of RightParacentral Range value: 1.263, ..., 3.162
47: \item \strong{ST102TS} \emph{numeric} Thickness Stardard Deviation (aparc.stats) of RightParacentral Range value: 0.361, ..., 1.006
48: \item \strong{ST103CV} \emph{numeric} Cortical Volume (aparc.stats) of RightParahippocampal Range value: 491, ..., 4818
49: \item \strong{ST103SA} \emph{numeric} Surface Area (aparc.stats) of RightParahippocampal Range value: 262, ..., 3128
50: \item \strong{ST103TA} \emph{numeric} Thickness Average (aparc.stats) of RightParahippocampal Range value: 1.334, ..., 3.36

--- Around line 49 ---
47: \item \strong{ST102TS} \emph{numeric} Thickness Stardard Deviation (aparc.stats) of RightParacentral Range value: 0.361, ..., 1.006
48: \item \strong{ST103CV} \emph{numeric} Cortical Volume (aparc.stats) of RightParahippocampal Range value: 491, ..., 4818
49: \item \strong{ST103SA} \emph{numeric} Surface Area (aparc.stats) of RightParahippocampal Range value: 262, ..., 3128
50: \item \strong{ST103TA} \emph{numeric} Thickness Average (aparc.stats) of RightParahippocampal Range value: 1.334, ..., 3.36
51: \item \strong{ST103TS} \emph{numeric} Thickness Stardard Deviation (aparc.stats) of RightParahippocampal Range value: 0.339, ..., 1.194

--- Around line 50 ---
48: \item \strong{ST103CV} \emph{numeric} Cortical Volume (aparc.stats) of RightParahippocampal Range value: 491, ..., 4818
49: \item \strong{ST103SA} \emph{numeric} Surface Area (aparc.stats) of RightParahippocampal Range value: 262, ..., 3128
50: \item \strong{ST103TA} \emph{numeric} Thickness Average (aparc.stats) of RightParahippocampal Range value: 1.334, ..., 3.36
51: \item \strong{ST103TS} \emph{numeric} Thickness Stardard Deviation (aparc.stats) of RightParahippocampal Range value: 0.339, ..., 1.194
52: \item \strong{ST104CV} \emph{numeric} Cortical Volume (aparc.stats) of RightParsOpercularis Range value: 944, ..., 7417

--- Around line 51 ---
49: \item \strong{ST103SA} \emph{numeric} Surface Area (aparc.stats) of RightParahippocampal Range value: 262, ..., 3128
50: \item \strong{ST103TA} \emph{numeric} Thickness Average (aparc.stats) of RightParahippocampal Range value: 1.334, ..., 3.36
51: \item \strong{ST103TS} \emph{numeric} Thickness Stardard Deviation (aparc.stats) of RightParahippocampal Range value: 0.339, ..., 1.194
52: \item \strong{ST104CV} \emph{numeric} Cortical Volume (aparc.stats) of RightParsOpercularis Range value: 944, ..., 7417
53: \item \strong{ST104SA} \emph{numeric} Surface Area (aparc.stats) of RightParsOpercularis Range value: 755, ..., 2512

--- Around line 167 ---
165: \item \strong{ST26TS} \emph{numeric} Thickness Stardard Deviation (aparc.stats) of LeftFusiform Range value: 0.423, ..., 0.988
166: \item \strong{ST28SA} \emph{numeric} Surface Area (aparc.stats) of LeftHemisphereWM Range value: 48668.9, ..., 110776
167: \item \strong{ST29SV} \emph{numeric} Subcortical Volume (aseg.stats) of LeftHippocampus Range value: 1188.7, ..., 5684.6
168: \item \strong{ST2SV} \emph{numeric} Subcortical Volume (aseg.stats) of CorpusCallosumAnterior Range value: 32.9, ..., 1872.9
169: \item \strong{ST30SV} \emph{numeric} Subcortical Volume (aseg.stats) of LeftInferiorLateralVentricle Range value: 54.5, ..., 9047.8

--- Around line 209 ---
207: \item \strong{ST43TA} \emph{numeric} Thickness Average (aparc.stats) of LeftParacentral Range value: 1.359, ..., 2.877
208: \item \strong{ST43TS} \emph{numeric} Thickness Stardard Deviation (aparc.stats) of LeftParacentral Range value: 0.367, ..., 0.982
209: \item \strong{ST44CV} \emph{numeric} Cortical Volume (aparc.stats) of LeftParahippocampal Range value: 21, ..., 7224
210: \item \strong{ST44SA} \emph{numeric} Surface Area (aparc.stats) of LeftParahippocampal Range value: 17, ..., 4381
211: \item \strong{ST44TA} \emph{numeric} Thickness Average (aparc.stats) of LeftParahippocampal Range value: 0.96, ..., 3.564

--- Around line 210 ---
208: \item \strong{ST43TS} \emph{numeric} Thickness Stardard Deviation (aparc.stats) of LeftParacentral Range value: 0.367, ..., 0.982
209: \item \strong{ST44CV} \emph{numeric} Cortical Volume (aparc.stats) of LeftParahippocampal Range value: 21, ..., 7224
210: \item \strong{ST44SA} \emph{numeric} Surface Area (aparc.stats) of LeftParahippocampal Range value: 17, ..., 4381
211: \item \strong{ST44TA} \emph{numeric} Thickness Average (aparc.stats) of LeftParahippocampal Range value: 0.96, ..., 3.564
212: \item \strong{ST44TS} \emph{numeric} Thickness Stardard Deviation (aparc.stats) of LeftParahippocampal Range value: 0.175, ..., 1.192

--- Around line 211 ---
209: \item \strong{ST44CV} \emph{numeric} Cortical Volume (aparc.stats) of LeftParahippocampal Range value: 21, ..., 7224
210: \item \strong{ST44SA} \emph{numeric} Surface Area (aparc.stats) of LeftParahippocampal Range value: 17, ..., 4381
211: \item \strong{ST44TA} \emph{numeric} Thickness Average (aparc.stats) of LeftParahippocampal Range value: 0.96, ..., 3.564
212: \item \strong{ST44TS} \emph{numeric} Thickness Stardard Deviation (aparc.stats) of LeftParahippocampal Range value: 0.175, ..., 1.192
213: \item \strong{ST45CV} \emph{numeric} Cortical Volume (aparc.stats) of LeftParsOpercularis Range value: 1377, ..., 8539

--- Around line 212 ---
210: \item \strong{ST44SA} \emph{numeric} Surface Area (aparc.stats) of LeftParahippocampal Range value: 17, ..., 4381
211: \item \strong{ST44TA} \emph{numeric} Thickness Average (aparc.stats) of LeftParahippocampal Range value: 0.96, ..., 3.564
212: \item \strong{ST44TS} \emph{numeric} Thickness Stardard Deviation (aparc.stats) of LeftParahippocampal Range value: 0.175, ..., 1.192
213: \item \strong{ST45CV} \emph{numeric} Cortical Volume (aparc.stats) of LeftParsOpercularis Range value: 1377, ..., 8539
214: \item \strong{ST45SA} \emph{numeric} Surface Area (aparc.stats) of LeftParsOpercularis Range value: 856, ..., 3410

--- Around line 322 ---
320: \item \strong{ST85TS} \emph{numeric} Thickness Stardard Deviation (aparc.stats) of RightFusiform Range value: 0.425, ..., 1.021
321: \item \strong{ST87sa} \emph{numeric} Surface Area (aparc.stats) of RightHemisphereWM Range value: 55054.4, ..., 109909
322: \item \strong{ST88SV} \emph{numeric} Subcortical Volume (aseg.stats) of RightHippocampus Range value: 1047.6, ..., 5567.9
323: \item \strong{ST89SV} \emph{numeric} Subcortical Volume (aseg.stats) of RightInferiorLateralVentricle Range value: 34.4, ..., 12740.1
324: \item \strong{ST8SV} \emph{numeric} Subcortical Volume (aseg.stats) of FifthVentricle Range value: 1, ..., 25.1

In [101]:
import pandas as pd

# Load MRI data
mri = pd.read_csv(
    "../Data/UCSFFSX7_from_R.csv",
    low_memory=False
)

# Load our final 997-person cohort
cohort = pd.read_csv(
    "../Data/final_cohort.csv"
)

# Convert dates
mri["EXAMDATE"] = pd.to_datetime(mri["EXAMDATE"], errors="coerce")
cohort["MCI_DATE"] = pd.to_datetime(cohort["MCI_DATE"], errors="coerce")

# Keep only the MRI variables we identified
hippo = mri[
    ["PTID", "RID", "VISCODE", "VISCODE2", "EXAMDATE",
     "STATUS", "HIPPOQC", "ST29SV", "ST88SV"]
].copy()

# Keep MRI performed on or before first MCI date
merged = hippo.merge(
    cohort[["PTID", "MCI_DATE"]],
    on="PTID",
    how="inner"
)

baseline_mri = merged[
    merged["EXAMDATE"].notna() &
    (merged["EXAMDATE"] <= merged["MCI_DATE"])
].copy()

# Select the latest MRI before/on MCI date
baseline_mri = (
    baseline_mri
    .sort_values(["PTID", "EXAMDATE"])
    .drop_duplicates("PTID", keep="last")
)

print("Cohort participants:", len(cohort))
print("Participants with MRI record:", baseline_mri["PTID"].nunique())

print("\nLeft hippocampus (ST29SV):")
print(
    baseline_mri["ST29SV"].notna().sum(),
    "available"
)

print("\nRight hippocampus (ST88SV):")
print(
    baseline_mri["ST88SV"].notna().sum(),
    "available"
)

print("\nHIPPOQC:")
print(baseline_mri["HIPPOQC"].value_counts(dropna=False))

print("\nMRI STATUS:")
print(baseline_mri["STATUS"].value_counts(dropna=False))

Cohort participants: 997
Participants with MRI record: 584

Left hippocampus (ST29SV):
583 available

Right hippocampus (ST88SV):
583 available

HIPPOQC:
HIPPOQC
NaN     578
Pass      5
Fail      1
Name: count, dtype: int64

MRI STATUS:
STATUS
partial     578
complete      6
Name: count, dtype: int64

In [102]:
import pandas as pd

# Load previously created baseline datasets
cohort = pd.read_csv("../Data/final_cohort.csv")

demo = pd.read_csv("../Data/PTDEMOG_demographics_from_R.csv")

adas = pd.read_csv("../Data/ADAS_from_R.csv")
cdr = pd.read_csv("../Data/CDR_from_R.csv")
mmse = pd.read_csv("../Data/MMSE_from_R.csv")
moca = pd.read_csv("../Data/MOCA_from_R.csv")
faq = pd.read_csv("../Data/FAQ_from_R.csv")

# Convert dates
cohort["MCI_DATE"] = pd.to_datetime(cohort["MCI_DATE"])
demo["VISDATE"] = pd.to_datetime(demo["VISDATE"])
adas["VISDATE"] = pd.to_datetime(adas["VISDATE"])
cdr["VISDATE"] = pd.to_datetime(cdr["VISDATE"])
mmse["VISDATE"] = pd.to_datetime(mmse["VISDATE"])
moca["VISDATE"] = pd.to_datetime(moca["VISDATE"])
faq["VISDATE"] = pd.to_datetime(faq["VISDATE"])

print("Cohort size:", len(cohort))

print("\nExpected baseline feature availability:")
print("--------------------------------------")
print("Demographics:")
print("  Gender:       986 / 997")
print("  Education:    986 / 997")
print("  Ethnicity:    986 / 997")
print("  Race:         986 / 997")
print("  Age:          993 / 997")
print("  APOE:         991 / 997")

print("\nClinical:")
print("  CDRGLOBAL:    992 / 997")
print("  CDRSB:        991 / 997")
print("  MMSE:         993 / 997")
print("  ADAS11:       535 / 997")
print("  ADAS13:       532 / 997")
print("  FAQTOTAL:     520 / 997")
print("  MOCA:         previously ~194 / 997")

print("\nMRI:")
print("  Left hippocampus:  583 / 997")
print("  Right hippocampus: 583 / 997")

Cohort size: 997

Expected baseline feature availability:
--------------------------------------
Demographics:
  Gender:       986 / 997
  Education:    986 / 997
  Ethnicity:    986 / 997
  Race:         986 / 997
  Age:          993 / 997
  APOE:         991 / 997

Clinical:
  CDRGLOBAL:    992 / 997
  CDRSB:        991 / 997
  MMSE:         993 / 997
  ADAS11:       535 / 997
  ADAS13:       532 / 997
  FAQTOTAL:     520 / 997
  MOCA:         previously ~194 / 997

MRI:
  Left hippocampus:  583 / 997
  Right hippocampus: 583 / 997

In [103]:
import pandas as pd

# Load cohort and demographic data
cohort = pd.read_csv("../Data/final_cohort.csv")
demo = pd.read_csv("../Data/PTDEMOG_demographics_from_R.csv")

# Convert dates
cohort["MCI_DATE"] = pd.to_datetime(cohort["MCI_DATE"])
demo["VISDATE"] = pd.to_datetime(demo["VISDATE"])

# Keep demographic records occurring on or before first MCI date
demo_merge = demo.merge(
    cohort[["PTID", "MCI_DATE"]],
    on="PTID",
    how="inner"
)

demo_before_mci = demo_merge[
    demo_merge["VISDATE"].notna() &
    (demo_merge["VISDATE"] <= demo_merge["MCI_DATE"])
].copy()

# Select the latest available demographic record before/on MCI date
demo_baseline = (
    demo_before_mci
    .sort_values(["PTID", "VISDATE"])
    .drop_duplicates("PTID", keep="last")
)

# Keep only the variables we need
demo_baseline = demo_baseline[
    [
        "PTID",
        "RID",
        "VISDATE",
        "PTGENDER",
        "PTEDUCAT",
        "PTETHCAT",
        "PTRACCAT"
    ]
].copy()

print("Cohort participants:", cohort["PTID"].nunique())
print("Demographic baseline records:", demo_baseline["PTID"].nunique())

print("\nMissing values:")
print(
    demo_baseline[
        ["PTGENDER", "PTEDUCAT", "PTETHCAT", "PTRACCAT"]
    ].isna().sum()
)

print("\nSelected demographic baseline visits:")
print(demo_baseline["VISDATE"].describe())

print("\nFirst 10 records:")
display(demo_baseline.head(10))

Cohort participants: 997
Demographic baseline records: 993

Missing values:
PTGENDER    7
PTEDUCAT    7
PTETHCAT    7
PTRACCAT    7
dtype: int64

Selected demographic baseline visits:
count                           993
mean     2011-08-07 03:01:16.132930
min             2005-08-18 00:00:00
25%             2006-11-13 00:00:00
50%             2011-07-28 00:00:00
75%             2012-07-19 00:00:00
max             2024-06-25 00:00:00
Name: VISDATE, dtype: object

First 10 records:

,PTID,RID,VISDATE,PTGENDER,PTEDUCAT,PTETHCAT,PTRACCAT
175,002_S_0729,729,2006-07-06,Female,16.0,Not Hispanic or Latino,White
189,002_S_0782,782,2006-07-26,Male,16.0,Not Hispanic or Latino,White
231,002_S_0954,954,2006-09-26,Female,14.0,Not Hispanic or Latino,White
284,002_S_1070,1070,2006-11-14,Male,14.0,Not Hispanic or Latino,White
300,002_S_1155,1155,2006-12-04,Male,20.0,Not Hispanic or Latino,White
327,002_S_1268,1268,2007-01-24,Male,20.0,Not Hispanic or Latino,White
413,002_S_2010,2010,2010-06-10,Female,20.0,Not Hispanic or Latino,More than one race
442,002_S_2073,2073,2010-08-26,Female,20.0,Not Hispanic or Latino,White
799,002_S_4171,4171,2011-08-04,Male,16.0,Not Hispanic or Latino,White
833,002_S_4229,4229,2011-09-06,Male,15.0,Not Hispanic or Latino,White

In [104]:
import pandas as pd

# Load cohort, demographic baseline, and ADSL
cohort = pd.read_csv("../Data/final_cohort.csv")
demo_baseline = pd.read_csv("../Data/PTDEMOG_demographics_from_R.csv")
adsl = pd.read_csv("../Data/ADSL_from_R.csv")

# Convert dates
cohort["MCI_DATE"] = pd.to_datetime(cohort["MCI_DATE"])
demo_baseline["VISDATE"] = pd.to_datetime(demo_baseline["VISDATE"])

# Re-create the latest demographic record before/on MCI date
demo_merge = demo_baseline.merge(
    cohort[["PTID", "MCI_DATE"]],
    on="PTID",
    how="inner"
)

demo_before_mci = demo_merge[
    demo_merge["VISDATE"].notna() &
    (demo_merge["VISDATE"] <= demo_merge["MCI_DATE"])
].copy()

demo_baseline_selected = (
    demo_before_mci
    .sort_values(["PTID", "VISDATE"])
    .drop_duplicates("PTID", keep="last")
)

demo_baseline_selected = demo_baseline_selected[
    [
        "PTID",
        "RID",
        "VISDATE",
        "PTGENDER",
        "PTEDUCAT",
        "PTETHCAT",
        "PTRACCAT"
    ]
]

# Add AGE and APOE from ADSL using RID = SUBJID
age_apoe = adsl[
    ["SUBJID", "AGE", "APOE"]
].copy()

age_apoe["SUBJID"] = pd.to_numeric(
    age_apoe["SUBJID"],
    errors="coerce"
)

demo_baseline_selected["RID"] = pd.to_numeric(
    demo_baseline_selected["RID"],
    errors="coerce"
)

demo_baseline_selected = demo_baseline_selected.merge(
    age_apoe,
    left_on="RID",
    right_on="SUBJID",
    how="left"
)

# Display availability
print("Participants:", len(demo_baseline_selected))

print("\nAge available:",
      demo_baseline_selected["AGE"].notna().sum())

print("APOE available:",
      demo_baseline_selected["APOE"].notna().sum())

print("\nAge summary:")
print(demo_baseline_selected["AGE"].describe())

print("\nAPOE distribution:")
print(demo_baseline_selected["APOE"].value_counts(dropna=False))

print("\nFirst 10 records:")
display(
    demo_baseline_selected[
        [
            "PTID", "RID", "AGE",
            "PTGENDER", "PTEDUCAT",
            "PTETHCAT", "PTRACCAT", "APOE"
        ]
    ].head(10)
)

Participants: 993

Age available: 993
APOE available: 991

Age summary:
count    993.000000
mean      72.814602
std        7.307407
min       55.000000
25%       68.000000
50%       73.000000
75%       78.100000
max       91.400000
Name: AGE, dtype: float64

APOE distribution:
APOE
ε3/ε3    462
ε3/ε4    349
ε4/ε4     93
ε2/ε3     64
ε2/ε4     23
NaN        2
Name: count, dtype: int64

First 10 records:

,PTID,RID,AGE,PTGENDER,PTEDUCAT,PTETHCAT,PTRACCAT,APOE
0,002_S_0729,729,65.2,Female,16.0,Not Hispanic or Latino,White,ε3/ε4
1,002_S_0782,782,81.6,Male,16.0,Not Hispanic or Latino,White,ε3/ε3
2,002_S_0954,954,69.4,Female,14.0,Not Hispanic or Latino,White,ε3/ε4
3,002_S_1070,1070,73.7,Male,14.0,Not Hispanic or Latino,White,ε3/ε3
4,002_S_1155,1155,57.9,Male,20.0,Not Hispanic or Latino,White,ε3/ε3
5,002_S_1268,1268,82.7,Male,20.0,Not Hispanic or Latino,White,ε3/ε4
6,002_S_2010,2010,62.9,Female,20.0,Not Hispanic or Latino,More than one race,ε3/ε4
7,002_S_2073,2073,63.4,Female,20.0,Not Hispanic or Latino,White,ε3/ε3
8,002_S_4171,4171,69.4,Male,16.0,Not Hispanic or Latino,White,ε3/ε3
9,002_S_4229,4229,66.4,Male,15.0,Not Hispanic or Latino,White,ε3/ε3

In [105]:
import pandas as pd

# Load cohort
cohort = pd.read_csv("../Data/final_cohort.csv")
cohort["MCI_DATE"] = pd.to_datetime(cohort["MCI_DATE"])

def get_baseline_measure(
    filename,
    value_column
):
    """
    Select the latest available measurement on or before
    each participant's first MCI date.
    """

    df = pd.read_csv(
        filename,
        low_memory=False
    )

    df["VISDATE"] = pd.to_datetime(
        df["VISDATE"],
        errors="coerce"
    )

    merged = df.merge(
        cohort[["PTID", "MCI_DATE"]],
        on="PTID",
        how="inner"
    )

    before_mci = merged[
        merged["VISDATE"].notna() &
        (merged["VISDATE"] <= merged["MCI_DATE"])
    ].copy()

    baseline = (
        before_mci
        .sort_values(["PTID", "VISDATE"])
        .drop_duplicates("PTID", keep="last")
    )

    return baseline[
        ["PTID", "VISDATE", value_column]
    ].copy()


# CDR
cdr_base = get_baseline_measure(
    "../Data/CDR_from_R.csv",
    "CDGLOBAL"
)

cdrsb_base = get_baseline_measure(
    "../Data/CDR_from_R.csv",
    "CDRSB"
)

# MMSE
mmse_base = get_baseline_measure(
    "../Data/MMSE_from_R.csv",
    "MMSCORE"
)


print("Baseline clinical feature availability")
print("=" * 50)

print(
    "CDR Global:",
    cdr_base[value_column if False else "CDGLOBAL"].notna().sum(),
    "/ 997"
)

print(
    "CDR-SB:",
    cdrsb_base["CDRSB"].notna().sum(),
    "/ 997"
)

print(
    "MMSE:",
    mmse_base["MMSCORE"].notna().sum(),
    "/ 997"
)

print("\nCDR Global summary:")
print(cdr_base["CDGLOBAL"].describe())

print("\nCDR-SB summary:")
print(cdrsb_base["CDRSB"].describe())

print("\nMMSE summary:")
print(mmse_base["MMSCORE"].describe())

Baseline clinical feature availability
==================================================
CDR Global: 992 / 997
CDR-SB: 991 / 997
MMSE: 993 / 997

CDR Global summary:
count    992.000000
mean       0.491431
std        0.090837
min       -1.000000
25%        0.500000
50%        0.500000
75%        0.500000
max        1.000000
Name: CDGLOBAL, dtype: float64

CDR-SB summary:
count    991.000000
mean       1.471241
std        0.919997
min        0.000000
25%        1.000000
50%        1.500000
75%        2.000000
max        6.000000
Name: CDRSB, dtype: float64

MMSE summary:
count    993.000000
mean      27.644512
std        1.852829
min       19.000000
25%       26.000000
50%       28.000000
75%       29.000000
max       30.000000
Name: MMSCORE, dtype: float64

In [106]:
import pandas as pd

cdr = pd.read_csv(
    "../Data/CDR_from_R.csv",
    low_memory=False
)

print("CDGLOBAL unique values:")
print(
    cdr["CDGLOBAL"]
    .value_counts(dropna=False)
    .sort_index()
)

print("\nCDRSB unique values:")
print(
    cdr["CDRSB"]
    .value_counts(dropna=False)
    .sort_index()
)

CDGLOBAL unique values:
CDGLOBAL
-1.0      86
 0.0    5409
 0.5    6880
 1.0    1592
 2.0     391
 3.0      98
 NaN     161
Name: count, dtype: int64

CDRSB unique values:
CDRSB
0.0     4877
0.5     1807
0.7        1
1.0     1519
1.5     1138
2.0      859
2.5      677
3.0      522
3.5      450
4.0      385
4.5      390
5.0      363
5.5      167
6.0      281
6.5       39
7.0      182
7.5       11
8.0      144
8.5        2
9.0      101
9.5        5
10.0     111
10.5       1
11.0      80
11.5       1
12.0      68
12.5       1
13.0      47
14.0      36
15.0      26
16.0      33
17.0      25
18.0      23
NaN      245
Name: count, dtype: int64

In [107]:
from pathlib import Path

package_dir = Path(
    r"C:\Users\anura\Desktop\MCI_AD_XAI_Project\Data\ADNIMERGE2\ADNIMERGE2"
)

term = "CDGLOBAL"

print("Searching ADNIMERGE2 documentation for:", term)
print("=" * 70)

found = 0

for file in package_dir.rglob("*"):
    if not file.is_file() or file.suffix not in {".Rd", ".Rmd", ".R", ".txt"}:
        continue

    try:
        text = file.read_text(
            encoding="utf-8",
            errors="ignore"
        )
    except Exception:
        continue

    for line_number, line in enumerate(text.splitlines(), start=1):
        if term.lower() in line.lower():
            print(f"\n{file.name} | line {line_number}")
            print(line.strip())

            found += 1

            if found >= 20:
                break

    if found >= 20:
        break

print("\nMatches shown:", found)

Searching ADNIMERGE2 documentation for: CDGLOBAL
======================================================================

ADSL.Rd | line 55
\item \strong{CDGLOBAL} \emph{numeric} Baseline CDR Global Score Range value: 0, ..., 2

CDR.Rd | line 72
\item \strong{CDGLOBAL} \emph{numeric} Global CDR

data.R | line 3991
#' \item \strong{CDGLOBAL} \emph{numeric} Global CDR

data.R | line 21168
#' \item \strong{CDGLOBAL} \emph{numeric} Baseline CDR Global Score Range value: 0, ..., 2

utils.R | line 494
"CDCARE", "CDGLOBAL", "CDRSB"

ADNI-Enrollment.Rmd | line 111
"DX", "APOE", "ADASTT13", "CDGLOBAL", "CDRSB", "MMSCORE",

ADNI-Enrollment.Rmd | line 154
"AGE", "EDUC", "ADASTT13", "CDGLOBAL",

ADNIMERGE2-Analysis-Meta-Specs.Rmd | line 245
variable = "CDGLOBAL", type = "float", length = "1", label = "Baseline CDR Global Score", sig_dig = 1,

ADNIMERGE2-Analysis-Meta-Specs.Rmd | line 246
origin = "Predecessor", derivation = "QS.QSSTRESC where QS.QSTESTCD=CDGLOBAL and QSBLFL = 'Y'."

ADNIMERGE2-Analysis-Meta-Specs.Rmd | line 924
"ADASTT11", "ADASTT13", "CDGLOBAL", "CDRSB", "DIGITSCR",

ADNIMERGE2-Derived-Data.Rmd | line 1284
QSTESTCD = "CDGLOBAL",

ADNIMERGE2-Derived-Data.Rmd | line 1447
select(all_of(qs_com_cols), CDGLOBAL, CDRSB) %>%

ADNIMERGE2-Derived-Data.Rmd | line 1450
cols = c(CDGLOBAL, CDRSB),

ADNI-Enrollment.R | line 81
"DX", "APOE", "ADASTT13", "CDGLOBAL", "CDRSB", "MMSCORE",

ADNI-Enrollment.R | line 123
"AGE", "EDUC", "ADASTT13", "CDGLOBAL",

ADNI-Enrollment.Rmd | line 111
"DX", "APOE", "ADASTT13", "CDGLOBAL", "CDRSB", "MMSCORE",

ADNI-Enrollment.Rmd | line 154
"AGE", "EDUC", "ADASTT13", "CDGLOBAL",

ADNIMERGE2-Analysis-Meta-Specs.R | line 215
variable = "CDGLOBAL", type = "float", length = "1", label = "Baseline CDR Global Score", sig_dig = 1,

ADNIMERGE2-Analysis-Meta-Specs.R | line 216
origin = "Predecessor", derivation = "QS.QSSTRESC where QS.QSTESTCD=CDGLOBAL and QSBLFL = 'Y'."

ADNIMERGE2-Analysis-Meta-Specs.R | line 865
"ADASTT11", "ADASTT13", "CDGLOBAL", "CDRSB", "DIGITSCR",

Matches shown: 20

In [108]:
from pathlib import Path

package_dir = Path(
    r"C:\Users\anura\Desktop\MCI_AD_XAI_Project\Data\ADNIMERGE2\ADNIMERGE2"
)

terms = ["-1", "missing", "unknown", "CDGLOBAL"]

print("Searching CDR documentation for -1 / missing-value coding")
print("=" * 75)

rd_files = list(package_dir.rglob("CDR*.Rd"))

for file in rd_files:
    print(f"\nFILE: {file.name}")
    
    lines = file.read_text(
        encoding="utf-8",
        errors="ignore"
    ).splitlines()

    for i, line in enumerate(lines):
        if any(term.lower() in line.lower() for term in terms):
            print(f"{i+1}: {line.strip()}")

Searching CDR documentation for -1 / missing-value coding
===========================================================================

FILE: CDR.Rd
72: \item \strong{CDGLOBAL} \emph{numeric} Global CDR

In [109]:
import pandas as pd

# Load the final 997-participant cohort
cohort = pd.read_csv("../Data/final_cohort.csv")

# Load previously extracted baseline clinical tables
cdr = pd.read_csv("../Data/CDR_from_R.csv", low_memory=False)
mmse = pd.read_csv("../Data/MMSE_from_R.csv", low_memory=False)

# Convert dates
cohort["MCI_DATE"] = pd.to_datetime(cohort["MCI_DATE"])
cdr["VISDATE"] = pd.to_datetime(cdr["VISDATE"], errors="coerce")
mmse["VISDATE"] = pd.to_datetime(mmse["VISDATE"], errors="coerce")


# Function to select the latest measurement before/on first MCI
def get_baseline(df, value_column):

    merged = df.merge(
        cohort[["PTID", "MCI_DATE"]],
        on="PTID",
        how="inner"
    )

    before_mci = merged[
        merged["VISDATE"].notna() &
        (merged["VISDATE"] <= merged["MCI_DATE"])
    ].copy()

    baseline = (
        before_mci
        .sort_values(["PTID", "VISDATE"])
        .drop_duplicates("PTID", keep="last")
    )

    return baseline[["PTID", value_column]]


# Extract baseline values
cdr_base = get_baseline(cdr, "CDGLOBAL")
cdrsb_base = get_baseline(cdr, "CDRSB")
mmse_base = get_baseline(mmse, "MMSCORE")


# Create clinical feature table
clinical_base = cohort[["PTID"]].copy()

clinical_base = clinical_base.merge(
    cdr_base,
    on="PTID",
    how="left"
)

clinical_base = clinical_base.merge(
    cdrsb_base,
    on="PTID",
    how="left"
)

clinical_base = clinical_base.merge(
    mmse_base,
    on="PTID",
    how="left"
)


# Treat undocumented -1 as missing
clinical_base["CDGLOBAL"] = clinical_base["CDGLOBAL"].replace(
    -1, pd.NA
)


print("Clinical baseline table shape:", clinical_base.shape)

print("\nMissing values:")
print(clinical_base.isna().sum())

print("\nCDR Global distribution:")
print(
    clinical_base["CDGLOBAL"]
    .value_counts(dropna=False)
    .sort_index()
)

print("\nCDR-SB summary:")
print(clinical_base["CDRSB"].describe())

print("\nMMSE summary:")
print(clinical_base["MMSCORE"].describe())

Clinical baseline table shape: (997, 4)

Missing values:
PTID        0
CDGLOBAL    6
CDRSB       6
MMSCORE     4
dtype: int64

CDR Global distribution:
CDGLOBAL
0.0      19
0.5     967
1.0       5
NaN       5
<NA>      1
Name: count, dtype: int64

CDR-SB summary:
count    991.000000
mean       1.471241
std        0.919997
min        0.000000
25%        1.000000
50%        1.500000
75%        2.000000
max        6.000000
Name: CDRSB, dtype: float64

MMSE summary:
count    993.000000
mean      27.644512
std        1.852829
min       19.000000
25%       26.000000
50%       28.000000
75%       29.000000
max       30.000000
Name: MMSCORE, dtype: float64

In [110]:
import pandas as pd

# Load cohort
cohort = pd.read_csv("../Data/final_cohort.csv")
cohort["MCI_DATE"] = pd.to_datetime(cohort["MCI_DATE"])


def get_baseline_measure(filename, value_column):

    df = pd.read_csv(
        filename,
        low_memory=False
    )

    df["VISDATE"] = pd.to_datetime(
        df["VISDATE"],
        errors="coerce"
    )

    merged = df.merge(
        cohort[["PTID", "MCI_DATE"]],
        on="PTID",
        how="inner"
    )

    before_mci = merged[
        merged["VISDATE"].notna() &
        (merged["VISDATE"] <= merged["MCI_DATE"])
    ].copy()

    baseline = (
        before_mci
        .sort_values(["PTID", "VISDATE"])
        .drop_duplicates("PTID", keep="last")
    )

    return baseline[["PTID", value_column]]


# Extract baseline measurements
adas11_base = get_baseline_measure(
    "../Data/ADAS_from_R.csv",
    "TOTSCORE"
)

adas13_base = get_baseline_measure(
    "../Data/ADAS_from_R.csv",
    "TOTAL13"
)

faq_base = get_baseline_measure(
    "../Data/FAQ_from_R.csv",
    "FAQTOTAL"
)

moca_base = get_baseline_measure(
    "../Data/MOCA_from_R.csv",
    "MOCA"
)


# Combine
additional = cohort[["PTID"]].copy()

for table in [
    adas11_base,
    adas13_base,
    faq_base,
    moca_base
]:
    additional = additional.merge(
        table,
        on="PTID",
        how="left"
    )


print("Additional clinical feature availability")
print("=" * 55)

for col in ["TOTSCORE", "TOTAL13", "FAQTOTAL", "MOCA"]:
    available = additional[col].notna().sum()
    percentage = available / len(additional) * 100

    print(
        f"{col:10s}: {available:3d} / {len(additional)} "
        f"({percentage:.1f}%)"
    )


print("\nSummary statistics:")
print(additional[
    ["TOTSCORE", "TOTAL13", "FAQTOTAL", "MOCA"]
].describe())

Additional clinical feature availability
=======================================================
TOTSCORE  : 535 / 997 (53.7%)
TOTAL13   : 532 / 997 (53.4%)
FAQTOTAL  : 520 / 997 (52.2%)
MOCA      :  32 / 997 (3.2%)

Summary statistics:
         TOTSCORE     TOTAL13    FAQTOTAL       MOCA
count  535.000000  532.000000  520.000000  32.000000
mean    10.133963   16.386579    3.086538  22.656250
std      4.556918    6.752195    4.164513   3.054445
min      1.000000    1.000000    0.000000  15.000000
25%      6.670000   11.000000    0.000000  22.000000
50%      9.670000   16.330000    1.000000  23.000000
75%     13.000000   21.000000    4.000000  25.000000
max     28.670000   39.670000   22.000000  27.000000

In [111]:
import pandas as pd

# Load cohort and additional clinical features
cohort = pd.read_csv("../Data/final_cohort.csv")

additional = pd.read_csv("../Data/additional_clinical_baseline.csv") \
    if __import__("os").path.exists("../Data/additional_clinical_baseline.csv") \
    else None

# If the saved file does not exist, recreate the additional table
if additional is None:

    cohort["MCI_DATE"] = pd.to_datetime(cohort["MCI_DATE"])

    def get_baseline(filename, value_column):

        df = pd.read_csv(filename, low_memory=False)
        df["VISDATE"] = pd.to_datetime(
            df["VISDATE"], errors="coerce"
        )

        merged = df.merge(
            cohort[["PTID", "MCI_DATE"]],
            on="PTID",
            how="inner"
        )

        before = merged[
            merged["VISDATE"].notna() &
            (merged["VISDATE"] <= merged["MCI_DATE"])
        ]

        return (
            before
            .sort_values(["PTID", "VISDATE"])
            .drop_duplicates("PTID", keep="last")
            [["PTID", value_column]]
        )

    additional = cohort[["PTID"]].copy()

    for filename, column in [
        ("../Data/ADAS_from_R.csv", "TOTSCORE"),
        ("../Data/ADAS_from_R.csv", "TOTAL13"),
        ("../Data/FAQ_from_R.csv", "FAQTOTAL"),
    ]:
        additional = additional.merge(
            get_baseline(filename, column),
            on="PTID",
            how="left"
        )


# Add outcome
analysis = cohort[
    ["PTID", "AD_CONVERSION_2YR"]
].merge(
    additional,
    on="PTID",
    how="left"
)

print("Missingness by outcome group")
print("=" * 60)

for col in ["TOTSCORE", "TOTAL13", "FAQTOTAL"]:

    table = pd.crosstab(
        analysis["AD_CONVERSION_2YR"],
        analysis[col].isna(),
        normalize="index"
    ) * 100

    table.columns = ["Available (%)", "Missing (%)"]

    print(f"\n{col}")
    print(table.round(1))

Missingness by outcome group
============================================================

TOTSCORE
                   Available (%)  Missing (%)
AD_CONVERSION_2YR
0                           47.6         52.4
1                           98.3          1.7

TOTAL13
                   Available (%)  Missing (%)
AD_CONVERSION_2YR
0                           47.5         52.5
1                           96.6          3.4

FAQTOTAL
                   Available (%)  Missing (%)
AD_CONVERSION_2YR
0                           46.2         53.8
1                           95.8          4.2

In [112]:
import pandas as pd

# -----------------------------
# 1. Load cohort
# -----------------------------
cohort = pd.read_csv("../Data/final_cohort.csv")

# -----------------------------
# 2. Load demographic data
# -----------------------------
demo = pd.read_csv(
    "../Data/PTDEMOG_demographics_from_R.csv"
)

cohort["MCI_DATE"] = pd.to_datetime(cohort["MCI_DATE"])
demo["VISDATE"] = pd.to_datetime(
    demo["VISDATE"],
    errors="coerce"
)

# Match demographic records before/on first MCI
demo_merge = demo.merge(
    cohort[["PTID", "MCI_DATE"]],
    on="PTID",
    how="inner"
)

demo_before = demo_merge[
    demo_merge["VISDATE"].notna() &
    (demo_merge["VISDATE"] <= demo_merge["MCI_DATE"])
].copy()

demo_base = (
    demo_before
    .sort_values(["PTID", "VISDATE"])
    .drop_duplicates("PTID", keep="last")
)

demo_base = demo_base[
    [
        "PTID",
        "RID",
        "PTGENDER",
        "PTEDUCAT",
        "PTETHCAT",
        "PTRACCAT"
    ]
]

# -----------------------------
# 3. Load ADSL
# -----------------------------
adsl = pd.read_csv(
    "../Data/ADSL_from_R.csv"
)

adsl["SUBJID"] = pd.to_numeric(
    adsl["SUBJID"],
    errors="coerce"
)

demo_base["RID"] = pd.to_numeric(
    demo_base["RID"],
    errors="coerce"
)

# Add Age + APOE
demo_base = demo_base.merge(
    adsl[["SUBJID", "AGE", "APOE"]],
    left_on="RID",
    right_on="SUBJID",
    how="left"
)

# -----------------------------
# 4. Load clinical features
# -----------------------------
cdr = pd.read_csv(
    "../Data/CDR_from_R.csv",
    low_memory=False
)

mmse = pd.read_csv(
    "../Data/MMSE_from_R.csv",
    low_memory=False
)

cdr["VISDATE"] = pd.to_datetime(
    cdr["VISDATE"],
    errors="coerce"
)

mmse["VISDATE"] = pd.to_datetime(
    mmse["VISDATE"],
    errors="coerce"
)


def get_baseline(df, value_column):

    merged = df.merge(
        cohort[["PTID", "MCI_DATE"]],
        on="PTID",
        how="inner"
    )

    before = merged[
        merged["VISDATE"].notna() &
        (merged["VISDATE"] <= merged["MCI_DATE"])
    ].copy()

    base = (
        before
        .sort_values(["PTID", "VISDATE"])
        .drop_duplicates("PTID", keep="last")
    )

    return base[["PTID", value_column]]


cdr_global = get_baseline(
    cdr,
    "CDGLOBAL"
)

cdr_sb = get_baseline(
    cdr,
    "CDRSB"
)

mmse_base = get_baseline(
    mmse,
    "MMSCORE"
)

# -----------------------------
# 5. Combine everything
# -----------------------------
primary = cohort[
    ["PTID", "MCI_DATE", "AD_CONVERSION_2YR"]
].copy()

primary = primary.merge(
    demo_base[
        [
            "PTID",
            "AGE",
            "PTGENDER",
            "PTEDUCAT",
            "PTETHCAT",
            "PTRACCAT",
            "APOE"
        ]
    ],
    on="PTID",
    how="left"
)

primary = primary.merge(
    cdr_global,
    on="PTID",
    how="left"
)

primary = primary.merge(
    cdr_sb,
    on="PTID",
    how="left"
)

primary = primary.merge(
    mmse_base,
    on="PTID",
    how="left"
)

# Treat undocumented -1 CDR Global as missing
primary["CDGLOBAL"] = primary["CDGLOBAL"].replace(
    -1,
    pd.NA
)

# Save
primary.to_csv(
    "../Data/primary_features.csv",
    index=False
)

print("Primary feature table created!")
print("Shape:", primary.shape)

print("\nColumns:")
print(primary.columns.tolist())

print("\nMissing values:")
print(primary.isna().sum())

Primary feature table created!
Shape: (997, 12)

Columns:
['PTID', 'MCI_DATE', 'AD_CONVERSION_2YR', 'AGE', 'PTGENDER', 'PTEDUCAT', 'PTETHCAT', 'PTRACCAT', 'APOE', 'CDGLOBAL', 'CDRSB', 'MMSCORE']

Missing values:
PTID                  0
MCI_DATE              0
AD_CONVERSION_2YR     0
AGE                   4
PTGENDER             11
PTEDUCAT             11
PTETHCAT             11
PTRACCAT             11
APOE                  6
CDGLOBAL              6
CDRSB                 6
MMSCORE               4
dtype: int64

In [113]:
import pandas as pd

primary = pd.read_csv(
    "../Data/primary_features.csv"
)

categorical_cols = [
    "PTGENDER",
    "PTETHCAT",
    "PTRACCAT",
    "APOE"
]

for col in categorical_cols:

    print("\n" + "=" * 60)
    print(col)
    print("=" * 60)

    print(
        primary[col]
        .value_counts(dropna=False)
    )

============================================================
PTGENDER
============================================================
PTGENDER
Male      575
Female    411
NaN        11
Name: count, dtype: int64

============================================================
PTETHCAT
============================================================
PTETHCAT
Not Hispanic or Latino    946
Hispanic or Latino         36
NaN                        11
Unknown                     4
Name: count, dtype: int64

============================================================
PTRACCAT
============================================================
PTRACCAT
White                                        897
Black or African American                     50
Asian                                         22
NaN                                           11
More than one race                            10
Unknown                                        5
Native Hawaiian or Other Pacific Islander      1
American Indian or Alaskan Native              1
Name: count, dtype: int64

============================================================
APOE
============================================================
APOE
ε3/ε3    462
ε3/ε4    349
ε4/ε4     93
ε2/ε3     64
ε2/ε4     23
NaN        6
Name: count, dtype: int64

In [114]:
import pandas as pd

# Load primary feature table
primary = pd.read_csv(
    "../Data/primary_features.csv"
)

primary["MCI_DATE"] = pd.to_datetime(
    primary["MCI_DATE"]
)

# Load MRI
mri = pd.read_csv(
    "../Data/UCSFFSX7_from_R.csv",
    low_memory=False
)

mri["EXAMDATE"] = pd.to_datetime(
    mri["EXAMDATE"],
    errors="coerce"
)

# Keep relevant MRI variables
mri_small = mri[
    [
        "PTID",
        "RID",
        "VISCODE",
        "VISCODE2",
        "EXAMDATE",
        "ST29SV",
        "ST88SV"
    ]
].copy()

# Match MRI to our cohort
mri_merge = mri_small.merge(
    primary[
        ["PTID", "MCI_DATE"]
    ],
    on="PTID",
    how="inner"
)

# Only MRI performed before/on first MCI
mri_before_mci = mri_merge[
    mri_merge["EXAMDATE"].notna() &
    (mri_merge["EXAMDATE"] <= mri_merge["MCI_DATE"])
].copy()

# Select latest MRI before/on MCI
mri_baseline = (
    mri_before_mci
    .sort_values(["PTID", "EXAMDATE"])
    .drop_duplicates("PTID", keep="last")
)

# Keep MRI features
mri_baseline = mri_baseline[
    ["PTID", "ST29SV", "ST88SV"]
].copy()

# Rename for readability
mri_baseline = mri_baseline.rename(
    columns={
        "ST29SV": "LEFT_HIPPOCAMPUS_VOLUME",
        "ST88SV": "RIGHT_HIPPOCAMPUS_VOLUME"
    }
)

# Merge with primary table
mri_features = primary.merge(
    mri_baseline,
    on="PTID",
    how="left"
)

# Save
mri_features.to_csv(
    "../Data/mri_enhanced_features.csv",
    index=False
)

print("MRI-enhanced feature table created!")
print("Shape:", mri_features.shape)

print("\nMRI availability:")
print(
    mri_features[
        [
            "LEFT_HIPPOCAMPUS_VOLUME",
            "RIGHT_HIPPOCAMPUS_VOLUME"
        ]
    ].notna().sum()
)

print("\nMRI missingness:")
print(
    mri_features[
        [
            "LEFT_HIPPOCAMPUS_VOLUME",
            "RIGHT_HIPPOCAMPUS_VOLUME"
        ]
    ].isna().sum()
)

print("\nHippocampal volume summary:")
print(
    mri_features[
        [
            "LEFT_HIPPOCAMPUS_VOLUME",
            "RIGHT_HIPPOCAMPUS_VOLUME"
        ]
    ].describe()
)

MRI-enhanced feature table created!
Shape: (997, 14)

MRI availability:
LEFT_HIPPOCAMPUS_VOLUME     583
RIGHT_HIPPOCAMPUS_VOLUME    583
dtype: int64

MRI missingness:
LEFT_HIPPOCAMPUS_VOLUME     414
RIGHT_HIPPOCAMPUS_VOLUME    414
dtype: int64

Hippocampal volume summary:
       LEFT_HIPPOCAMPUS_VOLUME  RIGHT_HIPPOCAMPUS_VOLUME
count               583.000000                583.000000
mean               3397.170497               3482.317324
std                 537.934885                573.441723
min                1543.200000               1160.800000
25%                3014.100000               3097.150000
50%                3415.500000               3486.600000
75%                3787.700000               3863.400000
max                4885.500000               5300.600000

In [115]:
import pandas as pd
import numpy as np

# Load MRI-enhanced dataset
df = pd.read_csv(
    "../Data/mri_enhanced_features.csv"
)

# Create APOE epsilon-4 carrier variable
def apoe4_carrier(genotype):
    if pd.isna(genotype):
        return np.nan

    return int("ε4" in genotype)

df["APOE_E4_CARRIER"] = df["APOE"].apply(apoe4_carrier)

# Save updated dataset
df.to_csv(
    "../Data/final_modeling_dataset.csv",
    index=False
)

print("Final modeling dataset")
print("=" * 60)

print("Shape:", df.shape)

print("\nOutcome:")
print(
    df["AD_CONVERSION_2YR"]
    .value_counts()
)

print("\nAPOE genotype:")
print(
    df["APOE"]
    .value_counts(dropna=False)
)

print("\nAPOE ε4 carrier:")
print(
    df["APOE_E4_CARRIER"]
    .value_counts(dropna=False)
)

print("\nMissing values:")
print(df.isna().sum())

print("\nNumeric feature summary:")
numeric_cols = [
    "AGE",
    "PTEDUCAT",
    "CDGLOBAL",
    "CDRSB",
    "MMSCORE",
    "LEFT_HIPPOCAMPUS_VOLUME",
    "RIGHT_HIPPOCAMPUS_VOLUME"
]

print(df[numeric_cols].describe().T)

Final modeling dataset
============================================================
Shape: (997, 15)

Outcome:
AD_CONVERSION_2YR
0    878
1    119
Name: count, dtype: int64

APOE genotype:
APOE
ε3/ε3    462
ε3/ε4    349
ε4/ε4     93
ε2/ε3     64
ε2/ε4     23
NaN        6
Name: count, dtype: int64

APOE ε4 carrier:
APOE_E4_CARRIER
0.0    526
1.0    465
NaN      6
Name: count, dtype: int64

Missing values:
PTID                          0
MCI_DATE                      0
AD_CONVERSION_2YR             0
AGE                           4
PTGENDER                     11
PTEDUCAT                     11
PTETHCAT                     11
PTRACCAT                     11
APOE                          6
CDGLOBAL                      6
CDRSB                         6
MMSCORE                       4
LEFT_HIPPOCAMPUS_VOLUME     414
RIGHT_HIPPOCAMPUS_VOLUME    414
APOE_E4_CARRIER               6
dtype: int64

Numeric feature summary:
                          count         mean         std     min      25%  \
AGE                       993.0    72.814602    7.307407    55.0    68.00
PTEDUCAT                  986.0    16.023327    2.700717     6.0    14.00
CDGLOBAL                  991.0     0.492936    0.077528     0.0     0.50
CDRSB                     991.0     1.471241    0.919997     0.0     1.00
MMSCORE                   993.0    27.644512    1.852829    19.0    26.00
LEFT_HIPPOCAMPUS_VOLUME   583.0  3397.170497  537.934885  1543.2  3014.10
RIGHT_HIPPOCAMPUS_VOLUME  583.0  3482.317324  573.441723  1160.8  3097.15

                             50%     75%     max
AGE                         73.0    78.1    91.4
PTEDUCAT                    16.0    18.0    20.0
CDGLOBAL                     0.5     0.5     1.0
CDRSB                        1.5     2.0     6.0
MMSCORE                     28.0    29.0    30.0
LEFT_HIPPOCAMPUS_VOLUME   3415.5  3787.7  4885.5
RIGHT_HIPPOCAMPUS_VOLUME  3486.6  3863.4  5300.6

In [116]:
import pandas as pd

from sklearn.model_selection import train_test_split

# Load final dataset
df = pd.read_csv(
    "../Data/final_modeling_dataset.csv"
)

# -----------------------------
# Primary feature set
# -----------------------------

primary_features = [
    "AGE",
    "PTGENDER",
    "PTEDUCAT",
    "PTETHCAT",
    "PTRACCAT",
    "APOE",
    "CDGLOBAL",
    "CDRSB",
    "MMSCORE"
]

X = df[primary_features].copy()
y = df["AD_CONVERSION_2YR"].copy()

# -----------------------------
# Stratified train/test split
# -----------------------------

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    stratify=y,
    random_state=42
)

print("Dataset split")
print("=" * 50)

print("Total participants:", len(df))
print("Training participants:", len(X_train))
print("Testing participants:", len(X_test))

print("\nTraining outcome:")
print(y_train.value_counts())

print("\nTraining outcome percentage:")
print(
    (y_train.value_counts(normalize=True) * 100)
    .round(2)
)

print("\nTesting outcome:")
print(y_test.value_counts())

print("\nTesting outcome percentage:")
print(
    (y_test.value_counts(normalize=True) * 100)
    .round(2)
)

Dataset split
==================================================
Total participants: 997
Training participants: 797
Testing participants: 200

Training outcome:
AD_CONVERSION_2YR
0    702
1     95
Name: count, dtype: int64

Training outcome percentage:
AD_CONVERSION_2YR
0    88.08
1    11.92
Name: proportion, dtype: float64

Testing outcome:
AD_CONVERSION_2YR
0    176
1     24
Name: count, dtype: int64

Testing outcome percentage:
AD_CONVERSION_2YR
0    88.0
1    12.0
Name: proportion, dtype: float64

In [117]:
import pandas as pd

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

# Numerical features
numeric_features = [
    "AGE",
    "PTEDUCAT",
    "CDGLOBAL",
    "CDRSB",
    "MMSCORE"
]

# Categorical features
categorical_features = [
    "PTGENDER",
    "PTETHCAT",
    "PTRACCAT",
    "APOE"
]

# Numerical preprocessing
numeric_transformer = Pipeline(
    steps=[
        ("imputer", SimpleImputer(strategy="median")),
        ("scaler", StandardScaler())
    ]
)

# Categorical preprocessing
categorical_transformer = Pipeline(
    steps=[
        ("imputer", SimpleImputer(strategy="most_frequent")),
        ("onehot", OneHotEncoder(
            handle_unknown="ignore",
            sparse_output=False
        ))
    ]
)

# Combine preprocessing
preprocessor = ColumnTransformer(
    transformers=[
        ("num", numeric_transformer, numeric_features),
        ("cat", categorical_transformer, categorical_features)
    ]
)

# Fit ONLY on training data
X_train_processed = preprocessor.fit_transform(X_train)

# Transform test data using training-fitted preprocessing
X_test_processed = preprocessor.transform(X_test)

print("Preprocessing completed")
print("=" * 50)

print("Original training shape:", X_train.shape)
print("Processed training shape:", X_train_processed.shape)

print("Original testing shape:", X_test.shape)
print("Processed testing shape:", X_test_processed.shape)

print("\nProcessed data type:")
print(X_train_processed.dtype)

Preprocessing completed
==================================================
Original training shape: (797, 9)
Processed training shape: (797, 22)
Original testing shape: (200, 9)
Processed testing shape: (200, 22)

Processed data type:
float64